# -*- coding: utf-8 -*-
"""
Per-city content. Every field below is hand-written for that specific community.
Nothing here is generated from a template string — this is deliberate, because
near-duplicate city pages are the single fastest way to get a local site
filtered out of the index.

Facts (highways, landmarks, populations, incorporation dates) are sourced from
Washington County / Visit Washington County / WisDOT public information.
"""

CITIES = [
{
 "slug": "hartford-wi",
 "name": "Hartford",
 "county": "Washington County",
 "zip": "53027",
 "drive": "Home base",
 "lat": 43.3219, "lng": -88.3762,
 "title": "Auto Detailing in Hartford, WI | Sudz Up Detailing",
 "meta": "Auto detailing in Hartford, WI from the shop on WI-83. Interior details from $135, full interior + exterior from $200. Call or text 414-286-1609.",
 "h1": "Auto Detailing in Hartford, Wisconsin",
 "lede": "We are based on WI-83 in Hartford. This is the town we work in every day, and it is the one place where we can usually fit a vehicle in on short notice.",
 "glance": [("Base", "2948 WI-83"), ("ZIP", "53027"), ("Travel time", "Local"), ("Booking notice", "Often same week")],
 "body": [
   ("Detailing in the town we actually work out of",
    ["Sudz Up Detailing operates from 2948 WI-83, which puts us a few minutes from downtown Hartford in either direction. Every vehicle we detail comes through here, so Hartford customers get the shortest turnaround we offer and the most scheduling flexibility.",
     "Hartford sits in the rolling hills of the Kettle Moraine, and the town's growth over the last decade has changed what we see roll in. Newer subdivisions on the edges of the city mean a lot of daily commuter mileage down WI-83 and Highway 60 toward Milwaukee and Waukesha. That is a specific kind of wear: highway grit in the lower panels, sun-baked dash tops from cars that sit in park-and-ride lots, and coffee and food debris in the console from people eating on the road.",
     "The historic downtown is a different story again. Cars that mostly do short trips around Main Street and the mill pond never get their engines fully warm in winter, which means interior moisture never really clears. Those are the vehicles that show up in March with a musty smell and salt rings on the carpet, and they need extraction rather than a surface wipe."]),
   ("What Hartford roads do to a vehicle",
    ["WI-83 and Highway 60 both get heavy winter salt and brine treatment. Brine is the part people underestimate. It is sprayed as a liquid before a storm, it dries into a white film, and it wicks into door jambs, rocker panels, and the seams where your carpet meets the sill plate. Because it is applied ahead of the weather, your car picks it up on perfectly dry days when you would never think to wash.",
     "In spring, the Rubicon River corridor and the farm fields on the west side of town throw a lot of fine dust. It settles into the dash vents and the seat stitching, where a vacuum alone will not reach it. We use compressed air and detail brushes to lift it out before it gets driven deeper into the foam.",
     "Then there is Pike Lake. The state park unit is minutes from town, and from June through August we pull a genuinely surprising amount of sand out of Hartford vehicles. Wet sand tracked onto carpet dries into a crust that a household vacuum will skate right over."]),
   ("Turnaround and scheduling",
    ["Because Hartford is our home base, we can usually work around your schedule rather than the other way around. Drop-offs are straightforward, and for regular customers we can often accommodate a short-notice request when something comes up.",
     "If you are selling a vehicle, tell us when you are listing it. A full interior and exterior detail is the cheapest thing you can do to a car before photographs, and we would rather sequence it a day or two before your listing goes live than have it sit and collect dust in a driveway for two weeks."]),
 ],
 "faq": [
   ("Where exactly is Sudz Up Detailing in Hartford?", "We are at 2948 WI-83, Hartford, WI 53027. Call or text 414-286-1609 before heading over so we can confirm we are on site and ready for your vehicle."),
   ("Can I get a same-week appointment in Hartford?", "Usually, yes. Hartford is our base, so local vehicles are the easiest for us to slot in. Call or text 414-286-1609 and we will tell you honestly what we have open."),
   ("Do you detail vehicles that have been sitting all winter?", "Yes, and those are often the ones that benefit most. Salt residue, moisture and a stale smell build up over a Wisconsin winter. A full interior with extraction resets it rather than masking it."),
 ],
},
{
 "slug": "west-bend-wi",
 "name": "West Bend",
 "county": "Washington County",
 "zip": "53090 / 53095",
 "drive": "About 20 minutes",
 "lat": 43.4253, "lng": -88.1834,
 "title": "Auto Detailing in West Bend, WI | Sudz Up Detailing",
 "meta": "Car detailing for West Bend, WI drivers. Interior details from $135, full interior + exterior from $200. Short drive from the county seat. Call 414-286-1609.",
 "h1": "Auto Detailing for West Bend, Wisconsin",
 "lede": "West Bend is the largest community we serve and about a twenty minute run from our shop in Hartford. It is worth the drive, and here is what we typically find in a West Bend vehicle.",
 "glance": [("County seat", "Washington County"), ("ZIPs", "53090 / 53095"), ("Population", "About 31,700"), ("From our shop", "~20 minutes")],
 "body": [
   ("The county seat brings different mileage",
    ["West Bend is by a wide margin the biggest city in Washington County, and it functions as the county's employment centre. That means a lot of the vehicles we see from West Bend are doing real daily mileage rather than weekend errands, and the wear patterns reflect that.",
     "High-mileage commuter cars share a set of problems: driver's seat bolster wear from getting in and out twice a day, a polished shiny patch on the steering wheel, dirt ground into the driver's floor mat far worse than the other three, and a door sill that has been stepped on a thousand times. We treat the driver's quarter of the cabin as its own job. It is the part you look at every day and the part that a rushed detail always skips.",
     "The city sits on the Milwaukee River, and the low ground near the water holds humidity longer than the higher parts of the county. Vehicles that park outside near the river through spring can develop condensation under floor mats. If you have ever lifted a mat and found the carpet underneath damp, that is what we are extracting."]),
   ("Farmers market, Regner Park and the reality of a family car",
    ["West Bend's farmers market has been voted the best in Wisconsin, and it shows up in the vehicles. Produce leaks. Flats of berries tip over. A bag of mulch splits in the cargo area. These are the stains people live with for months because they do not know whether they can be lifted.",
     "Most of them can. Organic staining from fruit, soil and plant matter responds well to hot water extraction if it has not been sitting for a year and been repeatedly ground in. The honest caveat is that some dyes, particularly from dark berries on light carpet, leave a shadow even after the bulk of the stain comes out. We will tell you before we start whether we think we can get all of it or most of it.",
     "Regner Park in summer produces the other West Bend classic: wet swimsuits and towels on the back seat, which is how you get a smell that does not come out with an air freshener. That is a moisture problem in the seat foam, and the fix is extraction plus proper drying, not fragrance."]),
   ("Making the drive worth it",
    ["Since West Bend is a drive for us rather than a walk, we suggest booking the full interior and exterior service rather than splitting work across two visits. It is better value for the trip and gets your vehicle fully reset in one go.",
     "If several people at your workplace or on your street want vehicles done, mention it when you call. Grouping West Bend vehicles into the same window is easier for us and we would rather do that than run the route twice."]),
 ],
 "faq": [
   ("Do you come to West Bend or do I drive to Hartford?", "Vehicles are detailed at our Hartford location on WI-83, roughly a twenty minute drive from West Bend. Call or text 414-286-1609 to arrange a time that works around your schedule."),
   ("Can you get farmers market and produce stains out of carpet?", "Usually a large majority of it. Organic staining responds well to hot water extraction. Dark fruit dye on light carpet can leave a faint shadow, and we will tell you upfront if we think that is likely."),
   ("How much is detailing for a West Bend family SUV?", "SUVs and trucks are $150 for the Sudz Quick Clean and $250 for the full Sudz Up VIP Clean. Condition affects final pricing, so call or text 414-286-1609 for a straight quote."),
 ],
},
{
 "slug": "slinger-wi",
 "name": "Slinger",
 "county": "Washington County",
 "zip": "53086",
 "drive": "About 10 minutes",
 "lat": 43.3336, "lng": -88.2848,
 "title": "Auto Detailing in Slinger, WI | Sudz Up Detailing",
 "meta": "Auto detailing for Slinger, WI. Race night dust, ski hill salt and family SUVs. Interior from $135, full detail from $200. Call or text 414-286-1609.",
 "h1": "Auto Detailing for Slinger, Wisconsin",
 "lede": "Slinger is about ten minutes east of our shop. Between the Speedway and Little Switzerland, it produces two of the most distinctive vehicle messes in the county.",
 "glance": [("County", "Washington County"), ("ZIP", "53086"), ("Landmarks", "Slinger Speedway, Little Switzerland"), ("From our shop", "~10 minutes")],
 "body": [
   ("Race night is hard on a vehicle",
    ["Slinger Speedway sits near the junction of Highway 144 and US 41, and it bills itself as the world's fastest quarter-mile oval. If you have parked in the infield or the outer lots on a race night, you already know what comes home with you.",
     "Track dust is not ordinary road dust. It is fine, it is loaded with rubber particulate and it carries a smell. It settles on every horizontal surface, works into the headliner, and gets tracked onto carpet and seats by everyone climbing back in. Because the particles are so fine, wiping a dusty dash with a dry cloth mostly just redistributes it and can put fine scratches into soft-touch plastics.",
     "Our approach on a post-race interior is compressed air first to lift dust out of vents, seams and switchgear, then vacuum, then a damp treatment on hard surfaces so we are pulling the residue off rather than pushing it around. Fabric seats that took a full season of race nights usually need extraction to get the smell out, not just a surface clean."]),
   ("Ski hill winters and salted lots",
    ["Little Switzerland puts a very different load on a car. Ski and snowboard gear means wet boots in the footwell, which is the fastest way to get salt slush directly into carpet backing. It also means gear in the cargo area, edges of skis and boards scraping trim, and roof racks that channel meltwater down the rear glass and tailgate seams.",
     "The winter problem in Slinger is compounded because Highway 41 and 144 both carry heavy brine treatment. A car that spends a Saturday at the hill and a weekday commute on 41 picks up salt from two directions. Left alone through spring, that dries into the white crust across the door sills and lower door skins that most people assume is permanent. It generally is not, but it does need proper cleaning rather than a hose."]),
   ("What we recommend for Slinger drivers",
    ["If you are a regular at the Speedway, a mid-season interior detail is worth more than one at the end of the year. Track dust that sits in fabric all summer gets driven deeper with every trip and becomes markedly harder to remove.",
     "For winter sports vehicles, we would rather see you in late March or early April, once the salt season is genuinely over. Detailing in January is satisfying for about a week and then you are back where you started."]),
 ],
 "faq": [
   ("Can you get race track dust out of a car interior?", "Yes. Track dust is fine and works into vents, seams and fabric, so we use compressed air to lift it before vacuuming rather than wiping it around. Fabric seats that absorbed a full season usually need hot water extraction as well."),
   ("How far is Slinger from your shop?", "About ten minutes. We are at 2948 WI-83 in Hartford, an easy run west from Slinger."),
   ("When should I book a winter clean-up?", "Late March or early April, once salt treatment on 41 and 144 has genuinely finished for the season. Detailing mid-winter looks great briefly and then the salt comes straight back."),
 ],
},
{
 "slug": "germantown-wi",
 "name": "Germantown",
 "county": "Washington County",
 "zip": "53022",
 "drive": "About 25 minutes",
 "lat": 43.2286, "lng": -88.1120,
 "title": "Auto Detailing in Germantown, WI | Sudz Up Detailing",
 "meta": "Car detailing for Germantown, WI commuters. Interior from $135, full interior + exterior from $200. Serving the 41/45 corridor. Call 414-286-1609.",
 "h1": "Auto Detailing for Germantown, Wisconsin",
 "lede": "Germantown sits on the busiest highway corridor in the county. That shapes almost everything about how the vehicles we see from there wear.",
 "glance": [("County", "Washington County"), ("ZIP", "53022"), ("Corridor", "US 41 / US 45"), ("From our shop", "~25 minutes")],
 "body": [
   ("Highway miles leave a signature",
    ["Germantown is the southern gateway of Washington County and it lives on the US 41 and US 45 corridor into Milwaukee. More of the vehicles we detail from Germantown are high-mileage highway cars than from anywhere else we serve, and highway miles produce a distinctive kind of dirt.",
     "At sustained speed, road film gets driven into paint rather than settling on it. The lower third of the doors, the rear bumper and the area behind the wheel arches collect a dark, greasy layer that is a mix of tyre particulate, brake dust and oily road residue. A regular wash lightens it but leaves the surface feeling gritty. Getting it properly off is the difference between a car that looks clean and one that feels clean when you run a hand over it.",
     "Bug and tar impact on the front end is heavier here too. From late spring through early autumn, sustained highway running loads up the front bumper, mirrors and windscreen surround. Bug residue is mildly acidic and it does etch clear coat if it bakes on across a hot summer, so this is a genuine paint preservation issue rather than a cosmetic one."]),
   ("Commuter interiors",
    ["A car that does an hour a day on 45 becomes a second room. We see travel mugs that have leaked into the console and gone unnoticed, phone mount marks on the dash, sunglasses and cables in every cubby, and an accumulation of receipts and wrappers in the door pockets.",
     "The other consistent Germantown finding is dash and upper door card fade. Long stretches sitting in exposed lots plus daily sun through a windscreen at commuting hours is hard on plastics. Our vinyl, rubber and plastic treatment on the Quick Clean is doing real work here — it is not just for appearance, it puts a layer back on surfaces that are drying out.",
     "If you eat in the car, say so. It changes what we bring. Dairy and protein spills that have gone unnoticed under a seat rail need to be found and extracted, and there is no point in us cleaning around a problem you already know about."]),
   ("Booking from the south end of the county",
    ["Germantown is about twenty-five minutes from our shop on WI-83, which makes it one of the longer runs we do. For that reason we would rather book the full interior and exterior service so the trip resets the whole vehicle.",
     "If you are already coming north on 41 for other reasons, the drive is genuinely short. A number of Germantown customers drop a vehicle on their way to something else in Hartford or West Bend and collect it later."]),
 ],
 "faq": [
   ("Do you serve Germantown from Hartford?", "Yes. Germantown is about twenty-five minutes from our shop at 2948 WI-83 in Hartford. Call or text 414-286-1609 to arrange a time."),
   ("Can you remove bug residue baked onto the front bumper?", "In most cases, yes. Bug residue is mildly acidic and needs proper chemical dwell time and safe agitation rather than scrubbing. If it has etched the clear coat over a full summer, some marking can remain, and we will be straight with you about that."),
   ("Is a full detail worth it on a high-mileage commuter car?", "Often more so than on a low-mileage one. Highway film, dash drying and driver's-side wear all accumulate faster, and a full interior and exterior service addresses all three at once."),
 ],
},
{
 "slug": "richfield-wi",
 "name": "Richfield",
 "county": "Washington County",
 "zip": "53017",
 "drive": "About 15 minutes",
 "lat": 43.2400, "lng": -88.2320,
 "title": "Auto Detailing in Richfield, WI | Sudz Up Detailing",
 "meta": "Auto detailing for Richfield, WI. Rural roads, Kettle Moraine dust and Holy Hill traffic. Interior from $135, full detail from $200. Call 414-286-1609.",
 "h1": "Auto Detailing for Richfield, Wisconsin",
 "lede": "Richfield kept its rural character while growing to nearly twelve thousand residents. The mix of gravel side roads and highway commuting gives its vehicles a split personality.",
 "glance": [("County", "Washington County"), ("ZIP", "53017"), ("Incorporated", "2008"), ("From our shop", "~15 minutes")],
 "body": [
   ("Two kinds of dirt in the same vehicle",
    ["Richfield sits near where US 45 meets US 41, with the Kettle Moraine on its western edge and roughly three hundred acres of parkland inside village limits. It was only incorporated in 2008 and it deliberately held onto its rural feel, which means a lot of properties sit on unpaved drives and township gravel roads.",
     "That produces a combination we do not see everywhere. The upper body and glass carry highway film from 41 and 45, while the lower panels, wheel wells and rocker area carry heavy dust and gravel spatter from the last mile home. Detailing one and not the other leaves an obvious line.",
     "Gravel road dust is also unusually persistent inside the cabin. It is dry, fine and electrostatic, so it clings to the dash top, the instrument cluster lens and the inside of the windscreen. That interior windscreen haze that scatters headlights at night is almost always this. It needs a proper two-stage glass clean, because a single pass with a household spray tends to smear it into a worse film."]),
   ("Holy Hill, the Art Farm and seasonal traffic",
    ["The Holy Hill area and the Art Farm in the Hubertus neighbourhood bring real seasonal traffic through Richfield, and autumn is the peak. Colour season means a lot of vehicles on wet leaf-covered back roads.",
     "Wet leaves are worth a specific mention. Leaf tannin will stain paint and, more commonly, will stain the plastic and rubber trim around the windscreen cowl and roof channels if leaves sit in there through a damp autumn. It leaves brown streaking that people often mistake for rust bleed. Clearing the cowl and channels is part of a proper exterior service and it is not something a drive-through wash touches.",
     "Muddy footwear from trails and parkland is the interior counterpart. Dried mud on carpet is straightforward if it is actually dried — we vacuum the solids out first. Attacking wet mud with water immediately drives it into the carpet backing and makes the job significantly harder."]),
   ("Practical advice for Richfield vehicles",
    ["If you live at the end of a gravel drive, do not judge your car's condition on how it looks in the garage. Look at the lower doors and behind the rear wheels in daylight. That is where the mileage actually shows.",
     "For autumn, we would rather see vehicles after leaf fall has finished than during it. Clearing the cowl and channels once, properly, beats doing it three times while the trees are still dropping."]),
 ],
 "faq": [
   ("Do you clean the inside of the windscreen properly?", "Yes. Interior glass haze from gravel road dust and off-gassing plastics is one of the most common things people notice at night. We use a two-stage method because a single wipe usually smears it into a worse film."),
   ("Can you get leaf stains off trim and paint?", "Usually. Leaf tannin staining on cowl trim and roof channels responds to proper cleaning if it is caught within a season. Long-term staining that has sat for years may lighten rather than disappear entirely."),
   ("How far is Richfield from your shop?", "About fifteen minutes from our location at 2948 WI-83 in Hartford."),
 ],
},
{
 "slug": "jackson-wi",
 "name": "Jackson",
 "county": "Washington County",
 "zip": "53037",
 "drive": "About 20 minutes",
 "lat": 43.3225, "lng": -88.1670,
 "title": "Auto Detailing in Jackson, WI | Sudz Up Detailing",
 "meta": "Auto detailing for Jackson, WI. Family vehicles, commuter cars and resale prep. Interior from $135, full detail from $200. Call or text 414-286-1609.",
 "h1": "Auto Detailing for Jackson, Wisconsin",
 "lede": "Jackson is one of the fastest growing communities in Washington County, about seven miles south of West Bend. Growing communities mean family vehicles, and family vehicles mean interiors.",
 "glance": [("County", "Washington County"), ("ZIP", "53037"), ("Population", "Just over 7,000"), ("From our shop", "~20 minutes")],
 "body": [
   ("Family vehicles are an interior problem",
    ["Jackson has grown quickly and it skews toward young families. The vehicle that reflects that is the three-row SUV or minivan, and it is genuinely the hardest kind of interior to detail properly.",
     "The reason is access. Second and third row footwells, the gaps beside child seat bases, seat rails, and the cargo area under the load floor all collect debris that never gets vacuumed because it is awkward to reach. Crushed snacks work down into seat seams. Juice goes into the carpet under a car seat and stays there because nobody removes the seat to look.",
     "We take child seats out where we can do so safely, because cleaning around one is close to pointless. If you would rather refit them yourself for peace of mind, tell us and we will leave them out for you rather than guess. That is your call, not ours, and we would rather ask."]),
   ("Odour is usually a moisture problem",
    ["The most common request we get from Jackson households is about smell. Sour milk, forgotten food, wet sports kit, or a spill nobody can locate. Almost always the answer is that liquid went into carpet or seat foam, and bacteria have been working on it since.",
     "Air fresheners do not solve this. Neither does shampooing the surface. What works is finding the source, extracting the contamination out of the foam and backing with hot water extraction, and then drying it thoroughly so you do not simply create a damp environment for the problem to restart.",
     "We are honest about the limits. If a spill has soaked through carpet into the sound deadening underneath and been left for a year, we can substantially improve it but a guarantee of total elimination would not be truthful."]),
   ("Resale prep before you list",
    ["Jackson turns over vehicles fairly often as families grow. If you are selling, book the full interior and exterior service before you photograph the car, not after you list it.",
     "The interior is what closes a private sale. Buyers forgive a stone chip. They do not forgive a stained third row and a smell, because both suggest the vehicle was not looked after. It is the highest-return few hundred dollars you can spend on a private sale."]),
 ],
 "faq": [
   ("Do you remove child seats to clean underneath?", "We can, where it is safe to do so, because cleaning around a child seat achieves very little. If you would prefer to refit them yourself, we will leave them out for you — many parents prefer that."),
   ("Can you get the sour smell out of a minivan?", "In most cases, substantially. Odour is almost always liquid in carpet or seat foam rather than an air problem, so we locate the source and extract it. Spills that soaked into sound deadening a year ago can be improved a lot but not always eliminated entirely."),
   ("Should I detail before selling my vehicle?", "Yes, and before you take the listing photographs. A clean interior does more to close a private sale than almost anything else at that price point."),
 ],
},
{
 "slug": "kewaskum-wi",
 "name": "Kewaskum",
 "county": "Washington County",
 "zip": "53040",
 "drive": "About 30 minutes",
 "lat": 43.5175, "lng": -88.2290,
 "title": "Auto Detailing in Kewaskum, WI | Sudz Up Detailing",
 "meta": "Auto detailing for Kewaskum, WI. Kettle Moraine trail dirt, ski hill salt and lake sand. Interior from $135, full detail from $200. Call 414-286-1609.",
 "h1": "Auto Detailing for Kewaskum, Wisconsin",
 "lede": "Kewaskum calls itself the gateway to the Kettle Moraine, and that is exactly the problem. Recreation vehicles come back dirtier than commuter vehicles, every time.",
 "glance": [("County", "Washington County"), ("ZIP", "53040"), ("Known for", "Gateway to the Kettle Moraine"), ("From our shop", "~30 minutes")],
 "body": [
   ("Recreation country is hard on interiors",
    ["Kewaskum sits at the north end of the county with the Kettle Moraine State Forest, the Eisenbahn State Trail, Sunburst ski hill, Hon-E-Kor golf course and the lakes at Mauthe and Long all within easy reach. Camping, hiking and the Ice Age Trail are minutes away.",
     "Every one of those activities puts something specific in a vehicle. Trail mud and boot grit in the footwells. Bike wheels and chain grease against the cargo carpet. Wet dogs, which is a category of its own. Golf shoes with soil packed into the spikes. Ski and board gear dripping meltwater through the whole cabin.",
     "The hardest of these is dog. Dog hair works into fabric weave in a way that vacuuming alone does not resolve, and it needs mechanical agitation — rubber tooling and brushes — to bring it up before it can be extracted. The dander and the wet-dog smell are separate problems again, and both live in the seat foam rather than in the air."]),
   ("Lake sand and the drying question",
    ["Long Lake and Mauthe Lake generate the same sand problem as Pike Lake does closer to us, and Kewaskum vehicles usually have more of it because the trips are longer and the gear is heavier.",
     "The rule with sand is to get it out before it dries and grinds. Sand is abrasive. Every time you sit on a seat with dry sand in the weave, you are effectively sanding your own upholstery. Over a few summers this genuinely wears fabric thin on the seat base, and that is not something a detail can reverse.",
     "The other Kewaskum reality is that gear gets stored in vehicles between outings. A wet towel or damp life jacket left in a closed cargo area for a week in July creates mildew in the carpet. If that has happened, tell us. Mildew needs a different treatment than ordinary soil and it is worth doing correctly the first time."]),
   ("Worth planning around the drive",
    ["Kewaskum is about thirty minutes from our shop, the longest regular run we make. We are happy to do it, but we would suggest making it count with the full interior and exterior service rather than a quick refresh.",
     "The natural rhythm for Kewaskum vehicles is twice a year: once in late spring after the salt season, and once in early autumn after the summer lake and trail season. That timing catches both of the seasonal problems at the point where they have finished rather than mid-cycle."]),
 ],
 "faq": [
   ("Can you get dog hair out of fabric seats?", "Yes, though it takes mechanical agitation with rubber tooling and brushes to lift hair out of the weave before extraction. Vacuuming alone does not do it. Dander and odour are separate issues that live in the seat foam."),
   ("Do you handle mildew from wet gear left in a car?", "Yes, and it needs a different treatment from ordinary soil. Tell us when you book so we come prepared, because mildew is worth doing properly the first time."),
   ("Is it worth the drive from Kewaskum?", "That is your call, but most Kewaskum customers book the full interior and exterior service so the trip resets the whole vehicle in one visit rather than two."),
 ],
},
{
 "slug": "allenton-wi",
 "name": "Allenton",
 "county": "Washington County",
 "zip": "53002",
 "drive": "About 12 minutes",
 "lat": 43.4147, "lng": -88.3456,
 "title": "Auto Detailing in Allenton, WI | Sudz Up Detailing",
 "meta": "Auto detailing for Allenton, WI. Farm dust, work trucks and highway commuting. Interior from $135, full detail from $200. Call or text 414-286-1609.",
 "h1": "Auto Detailing for Allenton, Wisconsin",
 "lede": "Allenton is a small community on the US 41 corridor north of Hartford, surrounded by working farmland. Work vehicles outnumber show vehicles here, and we detail accordingly.",
 "glance": [("County", "Washington County"), ("ZIP", "53002"), ("Corridor", "US 41"), ("From our shop", "~12 minutes")],
 "body": [
   ("Work trucks deserve a proper detail",
    ["A lot of what comes to us from Allenton is a working pickup. There is a persistent idea that a work truck is not worth detailing because it will just get dirty again. We would push back on that gently. A truck that is your workplace for fifty hours a week is exactly the vehicle where a clean cabin makes a daily difference, and it is usually the one carrying the most abrasive material.",
     "Work truck interiors have a distinct profile. Dried mud in the driver's footwell in layers. Fine agricultural or construction dust across the dash and in every vent. Tool marks and grease on the seat bolster where you slide in. Sawdust or feed in the seat seams. A rubber floor mat that has never been lifted.",
     "The single most valuable thing we do on a work truck is get under and behind things. Sliding the seats fully forward and back to reach the rails, lifting mats to clean the carpet or vinyl underneath, and clearing the vents with compressed air. That is where the material actually is."]),
   ("Farm dust is abrasive and persistent",
    ["The fields around Allenton generate serious dust at planting and harvest. Agricultural dust is different from road dust because it carries organic matter, which means it holds moisture and can start to smell in a warm cabin.",
     "It also gets everywhere. Dust drawn in through the ventilation system settles behind the dash vents and in the blower housing, so it re-emerges every time you turn the fan on. We clear what is reachable, but if your cabin air filter has not been changed in years, that is worth doing at the same time. We will tell you if it looks like the cause rather than pretend the interior clean alone will fix it.",
     "US 41 runs right past, so Allenton vehicles get highway film on top of the farm dust. Same split-personality issue as Richfield: the top half and the bottom half of the vehicle need different attention."]),
   ("Straight pricing for work vehicles",
    ["Trucks are $150 for the Sudz Quick Clean and $250 for the full Sudz Up VIP Clean. If a vehicle is genuinely heavily soiled we will say so before we start and give you a revised figure, rather than quoting a low number and adjusting it at collection.",
     "For a work truck that gets used hard, the Quick Clean two or three times a year is often better value than one big annual detail. It keeps material from building up to the point where it needs extraction."]),
 ],
 "faq": [
   ("Is it worth detailing a work truck?", "We think so. A truck you spend fifty hours a week in is exactly where a clean cabin pays off daily, and work vehicles usually carry the most abrasive material. Regular Quick Cleans often serve better than one big annual detail."),
   ("Can you get farm dust out of the vents?", "We clear what is reachable with compressed air. If dust has built up in the blower housing and cabin filter, we will tell you honestly, because an interior clean alone will not stop it re-emerging."),
   ("What does a truck detail cost?", "The Sudz Quick Clean is $150 for trucks and SUVs, and the full Sudz Up VIP Clean is $250. Heavily soiled vehicles are quoted before we start, not after."),
 ],
},
{
 "slug": "colgate-wi",
 "name": "Colgate",
 "county": "Washington County",
 "zip": "53017",
 "drive": "About 18 minutes",
 "lat": 43.2136, "lng": -88.2445,
 "title": "Auto Detailing in Colgate, WI | Sudz Up Detailing",
 "meta": "Auto detailing for Colgate, WI. Rural properties, long drives and gravel. Interior from $135, full detail from $200. Call or text 414-286-1609.",
 "h1": "Auto Detailing for Colgate, Wisconsin",
 "lede": "Colgate is a small unincorporated community in the south of the county, sharing the 53017 ZIP with Richfield. Rural, quiet, and hard on the lower half of a vehicle.",
 "glance": [("County", "Washington County"), ("ZIP", "53017"), ("Character", "Rural / unincorporated"), ("From our shop", "~18 minutes")],
 "body": [
   ("Long private drives change what needs cleaning",
    ["Colgate properties tend to sit back from the road on long drives, many of them gravel or crushed stone. That last quarter mile does more to a vehicle than most people realise.",
     "Loose stone kicks up into the rocker panels, the lower doors and behind the wheel arches. Over years this produces stone chipping along the leading edge of the rear arches and the bottom of the doors — the classic rural vehicle wear pattern. We cannot undo chips, but a proper exterior wash and polish removes the ground-in dust that makes them look worse than they are and puts a protective layer over the surrounding paint.",
     "The other consequence is dust intrusion. Driving a gravel surface pulls dust up behind the vehicle and into the cabin through the rear of the car, which is why hatchbacks and SUVs from rural addresses so often have a dusty cargo area even when the front looks clean. Lifting the load floor and cleaning the spare wheel well is part of doing this properly."]),
   ("Wildlife, wet seasons and the underside",
    ["Rural southern Washington County means deer, and it means vehicles that live under trees. Sap and bird residue are a real paint concern here rather than a nuisance. Both are acidic and both will etch clear coat if they bake in summer sun for weeks.",
     "The practical advice is that these need removing promptly rather than at the next detail. If you find sap on a panel, it comes off far more easily in the first few days than after a month. We can remove most of it later, but etching that has already happened is permanent and no polish reverses it.",
     "Spring thaw on unpaved drives produces the messiest interiors of the year in Colgate. Frozen mud in the treads of boots melts in a warm footwell and goes straight into carpet backing. That is an extraction job, not a vacuum job."]),
   ("How we schedule rural addresses",
    ["Colgate is about eighteen minutes from us. If you are on a long or rough drive, mention it when you call. It occasionally affects how we plan the exterior work, particularly if the vehicle will pick up dust again on the way home.",
     "For rural vehicles we generally suggest the full service. Cleaning the interior while the lower exterior stays caked in dust means the car looks half done and the dust migrates straight back in."]),
 ],
 "faq": [
   ("Can you fix stone chips from a gravel drive?", "Detailing does not repair chips. What a proper exterior wash and polish does is remove the ground-in dust that makes chipping look worse than it is, and protect the surrounding paint. We would rather be clear about that than oversell it."),
   ("Do you clean the cargo area and spare wheel well?", "Yes. Rural vehicles pull dust in through the back of the car, so the cargo area is often dirtier than the front. Lifting the load floor is part of a proper interior service."),
   ("How quickly should sap be removed?", "As soon as you notice it. Sap and bird residue are acidic and etch clear coat in summer sun. We can remove the deposit later, but etching that has already occurred is permanent."),
 ],
},
{
 "slug": "erin-wi",
 "name": "Erin",
 "county": "Washington County",
 "zip": "53027",
 "drive": "About 10 minutes",
 "lat": 43.2286, "lng": -88.3234,
 "title": "Auto Detailing in Erin, WI | Sudz Up Detailing",
 "meta": "Auto detailing for the Town of Erin, WI. Golf traffic, country roads and Kettle Moraine dust. Interior from $135, full detail from $200. Call 414-286-1609.",
 "h1": "Auto Detailing for the Town of Erin, Wisconsin",
 "lede": "Erin is rural Washington County at its most scenic, and it is home to Erin Hills, the public course that hosted the 2017 U.S. Open. Golf traffic gives its vehicles a specific signature.",
 "glance": [("County", "Washington County"), ("Mail ZIP", "53027 (Hartford)"), ("Landmark", "Erin Hills golf course"), ("From our shop", "~10 minutes")],
 "body": [
   ("Golf is surprisingly hard on a car",
    ["Erin Hills brought national attention to this corner of the county when it hosted the 2017 U.S. Open, and the course draws steady traffic through the season. Golf produces a very consistent set of vehicle problems and almost nobody anticipates them.",
     "Shoes are the main one. Soft spikes pack soil and grass into the sole, and that goes straight into the driver's footwell and the cargo area. Grass staining on carpet is genuinely difficult because chlorophyll is a dye rather than a soil, and it binds to fibre. We can usually lift most of it, but a heavy fresh grass stain on light carpet may not come out completely, and we would rather say that upfront.",
     "Bags in the cargo area are the second. A wet bag after a rain-shortened round sits in a closed boot and creates exactly the damp environment that produces a musty smell within days. Trolleys and pull carts scuff the cargo trim and load lip. And the cargo carpet takes the brunt of everything, which is why we treat it as a primary surface rather than an afterthought."]),
   ("Country roads and the Kettle Moraine",
    ["Away from the course, Erin is winding rural road through Kettle Moraine terrain. That means more time on surfaces with loose material at the edges, and more overhanging tree cover than most of the county.",
     "Tree cover is a mixed blessing. It keeps paint out of direct sun, which is good, but it means sap, bird residue and leaf litter, which is not. Vehicles parked routinely under trees in Erin come to us with a dulled finish caused by a long accumulation of organic deposit rather than by any single event. Those respond very well to a proper wash and polish — the improvement is often more dramatic than the owner expects.",
     "Winter on Erin's back roads is a genuine consideration too. Township roads see less treatment than the state highways, which means more packed snow and less brine, but also more sand. Sand in the footwells through February is standard here."]),
   ("What we suggest for Erin vehicles",
    ["If you golf regularly, an interior service at the end of the season is the one that matters. A season of soil, grass and damp bags in the cargo area is a real accumulation and it is far easier to reset once than to chase all summer.",
     "For vehicles that live under trees, the full interior and exterior service once or twice a year does considerably more for the paint than people expect. The change after removing years of organic film is usually the thing customers comment on."]),
 ],
 "faq": [
   ("Can you get grass stains out of car carpet?", "Usually most of it. Chlorophyll behaves like a dye rather than a soil, so it binds to fibre. Heavy fresh staining on light carpet may not come out completely and we will tell you that before starting rather than after."),
   ("Is Erin within your service area?", "Yes. The Town of Erin is about ten minutes from our shop at 2948 WI-83 in Hartford, and much of it carries a Hartford 53027 mailing address."),
   ("My car is dull from parking under trees. Can that be fixed?", "In most cases the improvement is significant. Dulling from accumulated sap, pollen and organic film responds very well to a proper wash and polish. Etching that has already damaged clear coat cannot be reversed."),
 ],
},
{
 "slug": "rubicon-wi",
 "name": "Rubicon",
 "county": "Dodge County",
 "zip": "53078",
 "drive": "About 12 minutes",
 "lat": 43.3097, "lng": -88.4762,
 "title": "Auto Detailing in Rubicon, WI | Sudz Up Detailing",
 "meta": "Auto detailing for Rubicon, WI in Dodge County. Farm country, work vehicles and country roads. Interior from $135, full detail from $200. Call 414-286-1609.",
 "h1": "Auto Detailing for Rubicon, Wisconsin",
 "lede": "Rubicon is just over the line into Dodge County, west of Hartford. It is farm country, and farm country vehicles have needs that a car wash does not address.",
 "glance": [("County", "Dodge County"), ("ZIP", "53078"), ("Character", "Agricultural"), ("From our shop", "~12 minutes")],
 "body": [
   ("Just across the county line, and closer than you think",
    ["A lot of Rubicon residents assume a Hartford business is out of range because it is in a different county. It is not — you are about twelve minutes from our shop on WI-83, which is closer than several of the Washington County communities we serve regularly.",
     "The Rubicon River gives the town its name, and the surrounding land is predominantly agricultural. That sets the pattern for what we see: pickups and older sedans that do a mix of field access, township gravel and highway running toward Hartford or Watertown.",
     "The defining characteristic of a Rubicon vehicle is layered soil. It is not one type of dirt applied once. It is field dust, then rain, then more dust, then road salt, built up over seasons. Layered soil needs to be removed in stages rather than blasted at, because taking a pressure washer to a heavily built-up lower panel drives grit sideways across paint."]),
   ("Agricultural exposure is chemically different",
    ["Farm environments expose vehicles to things ordinary commuter cars never encounter. Fertiliser dust is corrosive. Lime dust is alkaline and dries into a stubborn white film that ordinary car shampoo struggles with. Manure exposure is both a staining and an odour problem, and it needs to be dealt with promptly rather than left.",
     "None of this is a reason to be embarrassed about the state of a vehicle. It is a reason to tell us what the vehicle has actually been exposed to when you book, so we bring the right chemistry. There is a real difference between the products that handle general road grime and those that deal with alkaline lime film, and guessing wastes both our time.",
     "Interior-wise, the constant is heavy footwell soil and dust through the ventilation. Same as Allenton: the material is in the vents and under the mats, not just on the surfaces you can see."]),
   ("Straightforward for a rural budget",
    ["We keep two packages and no upsell ladder, which suits how people out here buy. The Quick Clean at $135 for cars and $150 for trucks handles the interior. The VIP at $200 and $250 does interior and exterior together.",
     "If a vehicle is genuinely rough, we quote it before we touch it. We would rather tell you a real number at the start than surprise you at collection, and if we think the honest answer is that a vehicle needs more than we can deliver in one visit, we will say that too."]),
 ],
 "faq": [
   ("Do you serve Dodge County?", "Yes. Rubicon is about twelve minutes from our shop at 2948 WI-83 in Hartford, which makes it closer than several Washington County communities we serve."),
   ("Can you clean lime and fertiliser film off a vehicle?", "Usually, but tell us when you book. Alkaline lime film needs different chemistry from ordinary road grime, and turning up prepared makes a real difference to the result."),
   ("My truck is genuinely filthy. Will you turn it away?", "No. We will quote it honestly before we start rather than after. If we think it needs more than one visit to put right, we will tell you that too."),
 ],
},
{
 "slug": "neosho-wi",
 "name": "Neosho",
 "county": "Dodge County",
 "zip": "53059",
 "drive": "About 18 minutes",
 "lat": 43.3006, "lng": -88.5170,
 "title": "Auto Detailing in Neosho, WI | Sudz Up Detailing",
 "meta": "Auto detailing for Neosho, WI in Dodge County. Small village, rural roads, honest pricing. Interior from $135, full detail from $200. Call 414-286-1609.",
 "h1": "Auto Detailing for Neosho, Wisconsin",
 "lede": "Neosho is a small Dodge County village west of Hartford. There is not much in the way of detailing options out that way, which is exactly why we list it.",
 "glance": [("County", "Dodge County"), ("ZIP", "53059"), ("Character", "Small village"), ("From our shop", "~18 minutes")],
 "body": [
   ("A genuine gap in coverage",
    ["Small villages tend to get overlooked by service businesses, and detailing is no exception. Most detailers in the region concentrate on the Milwaukee side of Washington County, which leaves the western communities driving a long way or going without.",
     "Neosho is about eighteen minutes from our shop in Hartford. That is a shorter run than plenty of people make for a haircut. We list it as a service area because we actually serve it, not to pad a page with place names, which is a common enough tactic that it is worth saying plainly.",
     "Vehicles from Neosho follow the rural Dodge County pattern: a mix of township gravel, county trunk highway and the run east on Highway 60 or 16 toward Hartford and Oconomowoc. Longer average trips than the suburban communities, on rougher surfaces."]),
   ("Longer trips, older vehicles, real wear",
    ["Rural households keep vehicles longer, and there is a lot to be said for that. It also means the vehicles we see from villages like Neosho often have genuine age on them: ten to fifteen years, high mileage, and an interior that has never had more than a vacuum.",
     "Those are satisfying vehicles to work on because the improvement is dramatic. Seat fabric that has looked permanently grey for years is very often just heavily soiled rather than worn out, and extraction brings back a colour the owner had forgotten. Dash plastics that have gone chalky respond well to proper VRP treatment.",
     "We will be straight about what age does not undo. Cracked dash tops from years of sun, headliner sag, worn-through seat bolsters and clear coat that has already failed are beyond what detailing addresses. Anyone telling you otherwise is selling something. What we can do is make everything that is still sound look genuinely good."]),
   ("Worth the short drive",
    ["Because Neosho is a run for both of us, we suggest the full interior and exterior package. It is better value for a single trip and there is no sense in doing half a job on a vehicle that came eighteen minutes to get here.",
     "Call or text 414-286-1609 and we will give you a straight price and an honest read on what your vehicle will look like afterwards. If we think the result will not justify the money, we will tell you that instead of taking the booking."]),
 ],
 "faq": [
   ("Do you really cover Neosho?", "Yes. It is about eighteen minutes from our shop at 2948 WI-83 in Hartford. We list communities we actually serve rather than padding a list with place names."),
   ("Can an older, high-mileage interior be improved?", "Usually a great deal. Seat fabric that has looked permanently grey is very often just heavily soiled rather than worn out. Cracked dash tops, sagging headliners and failed clear coat are beyond what detailing addresses, and we will say so."),
   ("Will you tell me if a detail is not worth it?", "Yes. If we do not think the result will justify the cost on a particular vehicle, we would rather say that than take the booking."),
 ],
},
]
