# -*- coding: utf-8 -*-
"""
Make-specific pages: /makes/<slug>/

Rule: a make gets a page only when the vehicle genuinely differs in a way
that changes the work -- paint hardness or thickness, body material, a
specific interior material, a design feature that traps water or dirt, or an
ownership pattern that produces a distinct wear profile. "People who own X
care about their cars" is not a reason. Brand names are used descriptively;
no affiliation is implied and none exists.

Not a matrix. There are no make x service or make x city pages, and there
should not be.
"""

MAKES = [
{
 "slug": "tesla",
 "name": "Tesla",
 "nav": "Tesla",
 "title": "Tesla Paint Correction, Ceramic Coating & Interior Detailing in Hartford, WI | Sudz Up",
 "meta": "Tesla detailing in Hartford, WI. Why Tesla paint marks so easily, why coating early matters more than on any other make, vegan leather care, and the glass roof. Call 414-286-1609.",
 "h1": "Tesla Detailing",
 "lede": "Tesla paint is the softest and thinnest we regularly work on, and that single fact changes the advice for everything else about the car.",
 "glance": [("Paint", "Soft, thin \u2014 assess first"), ("Coating", "As early as possible"), ("Interior", "Synthetic leather"), ("Roof", "Glass, not paint")],
 "body": [
   ("The paint",
    ["Tesla clear coat is widely understood in the detailing trade to be softer and thinner than most European and many domestic finishes. Soft means it marks easily \u2014 a brush wash or a careless drying towel leaves visible marring on a Tesla that would not show on a Porsche. Thin means there is less clear coat to remove when correcting that marring, so correction has to be conservative and the number of corrections over the car's life is lower.",
     "Practically: a Tesla that has been through automatic washes for two years usually has more visible swirling than a comparable-age car of most other makes, and correcting it fully may not be safe. We measure paint depth across every panel before touching one, and we will tell you where the paint says to stop rather than where the defect does."]),
   ("Why coating early matters more here",
    ["On most cars a coating is a good idea. On a Tesla it is close to essential, and the reason is the paint above. A coated surface takes the contact that would otherwise mark the clear coat, and it releases dirt with far less scrubbing, which is what a soft finish needs most.",
     "The timing argument is also stronger. A new Tesla needs decontamination and usually light correction for delivery marring, then a coating, and the job is close to the starting price. A two-year-old uncoated Tesla needs correction that has to be conservative because of the thickness, and the result is limited by how much can safely come off. Coat it in the first month if at all possible."]),
   ("The interior",
    ["Tesla interiors use a synthetic leather rather than hide, and it behaves differently. It does not need conditioning \u2014 conditioners intended for real leather sit on it and attract dirt. It is more resistant to staining than hide but it marks from dye transfer, particularly from dark denim onto light seats, and that transfer sets if it is left.",
     "The minimalist cabin means one large screen and a lot of piano-black and matte surfaces, all of which show fingerprints and scratch under anything abrasive. They get dedicated products and their own cloths."]),
   ("The glass roof",
    ["A large glass roof is not paint and does not get treated as paint \u2014 no clay, no polish. What it does do is collect the same fallout and mineral spotting a roof panel would, and hard-water rings on tinted glass are obvious from inside. It gets a glass-specific decontamination and a glass sealant, which keeps water sheeting off it.",
     "Our <a href=\"/services/ceramic-coating/\">coating page</a> covers the process and the <a href=\"/services/paint-correction/\">correction page</a> covers why clear coat is finite. On a Tesla both apply with more force than usual."]),
 ],
 "faq": [
   ("Is Tesla paint really that soft?", "In our experience and by broad trade consensus, yes \u2014 softer and thinner than most makes. It marks more easily and there is less clear coat to correct with. We measure before we polish."),
   ("Should I coat a new Tesla?", "Yes, as early as possible. A coating takes the contact that would mark the soft clear coat, and the job is smallest before any marring has accumulated."),
   ("Do Tesla seats need leather conditioner?", "No. They are synthetic, and conditioner for hide sits on top and attracts dirt. They need a suitable cleaner and, for light seats, attention to dye transfer from clothing."),
   ("Can you polish the glass roof?", "No, and it should not be. It gets glass-specific decontamination for mineral spotting and a glass sealant."),
 ],
},
{
 "slug": "porsche",
 "name": "Porsche",
 "nav": "Porsche",
 "title": "Porsche Paint Correction, Ceramic Coating & Detailing in Hartford, WI | Sudz Up",
 "meta": "Porsche detailing in Hartford, WI. Hard paint that corrects well, PCCB and painted calipers, the summer-car marring pattern and storage prep. One vehicle at a time. Call 414-286-1609.",
 "h1": "Porsche Detailing",
 "lede": "Porsche paint is among the hardest we work on, which is good news for correction and bad news for anyone who assumes it therefore does not need care.",
 "glance": [("Paint", "Hard \u2014 corrects well"), ("Usage", "Often seasonal"), ("Wheels", "Painted / ceramic calipers"), ("Storage", "Clean going in")],
 "body": [
   ("Hard paint, and what that means",
    ["German finishes generally, and Porsche in particular, cure hard. That makes them resistant to light marring \u2014 the drying towel that would mark a Tesla often does not mark a 911 \u2014 and it makes them respond well to correction, because the surface can take a proper cut and refine to a high gloss.",
     "It does not make them immune. Hard paint marks less easily but it still marks, and because Porsches are so often washed by hand by attentive owners, the hand-care marring pattern \u2014 a swirl from a reloaded mitt, a towel that touched the sill \u2014 is what we most often correct on them. It corrects cleanly. It also comes back if the method does not change."]),
   ("Wheels and brakes",
    ["Porsche wheels are frequently painted or diamond-cut, and the calipers behind them are painted, sometimes yellow, red or green. Aggressive wheel cleaners strip caliper paint and dull diamond-cut faces. Ceramic composite brakes produce far less dust than iron, but the dust they do produce is harder and embeds more readily.",
     "Wheels and calipers get pH-appropriate cleaners, dedicated brushes, and a proper iron decontamination rather than a strong acid. A wheel coating afterward makes the dust release with a rinse and protects the caliper finish."]),
   ("The seasonal-car pattern",
    ["Many Porsches in our area are good-weather cars, and a good-weather car has a specific problem: it is cared for more per mile than a daily and that care is where the marring comes from. It is also frequently stored for five months, and it needs to go into storage decontaminated and protected or it comes out with new marks that happened in the dark.",
     "The right rhythm is correction and coating in spring before the first drive, a rinse-and-inspect routine through summer that does not involve a dry duster, and full storage prep in November. The <a href=\"/services/paint-correction/chenequa-wi/\">summer-car correction page</a> and the <a href=\"/guides/winter-storage-prep-for-a-collector-car/\">storage guide</a> cover both ends."]),
   ("Interiors",
    ["Porsche leather is high quality and usually well coated, and it responds to a proper clean-then-condition sequence. Alcantara on wheels, headliners and seat inserts needs a dry method \u2014 water mats it. Piano-black and aluminium trim get non-abrasive products and their own cloths. It is a surface-by-surface interior, and the <a href=\"/vehicles/leather-and-luxury-interiors/\">luxury interior page</a> covers the approach."]),
 ],
 "faq": [
   ("Is Porsche paint easy to correct?", "Relatively, yes. It is hard, it takes a proper cut and refines to a high gloss. Hand-care marring on a well-kept Porsche corrects cleanly."),
   ("How do you clean painted calipers?", "With pH-appropriate cleaners and dedicated brushes, not strong acids, which strip caliper paint. A wheel coating afterward protects them."),
   ("Should a seasonal Porsche be coated?", "Yes, in spring after correction. It is what keeps hand-care through summer from putting the marring back, and it is what the car should go into storage wearing."),
 ],
},
{
 "slug": "land-rover-range-rover",
 "name": "Land Rover & Range Rover",
 "nav": "Land Rover / Range Rover",
 "title": "Range Rover & Land Rover Interior Detailing & Paint Care in Hartford, WI | Sudz Up",
 "meta": "Range Rover and Land Rover detailing in Hartford, WI. Leather-heavy interiors, real wood, large glass, trail and lake use, and the water-trapping design details. Call 414-286-1609.",
 "h1": "Land Rover & Range Rover Detailing",
 "lede": "A Range Rover is a luxury interior on a vehicle that its owners actually take places, and those two facts are in constant tension.",
 "glance": [("Interior", "Leather-heavy, real wood"), ("Usage", "Trail, lake, towing"), ("Design", "Water-trapping recesses"), ("Approach", "Surface by surface")],
 "body": [
   ("A leather interior that goes off-road",
    ["Range Rover cabins are leather on almost every surface \u2014 seats, dash, doors, console \u2014 and it is good leather with a coated finish that responds to proper care. The problem is what the vehicle does: lake weekends, trail heads, towing, dogs. Sunscreen, lake water, mud and dog hair land on leather that was designed for a very different life.",
     "The care is the same as any coated leather \u2014 pH-appropriate cleaner, gentle agitation, a conditioner that penetrates \u2014 but the frequency has to match the use. A Range Rover that does the lake all summer needs leather attention at the end of it, not once a year. <a href=\"/services/interior-protection/\">Leather coating</a> before the season is what keeps sunscreen on a sacrificial layer instead of in the topcoat."]),
   ("Wood, and the things that damage it",
    ["Real wood veneer trim has a lacquer finish that clouds under abrasive cleaners and dulls under silicone-heavy dressings. It gets a non-abrasive product and a soft cloth and nothing else. On older vehicles the lacquer may have crazed; that is a refinish, not a clean, and we will say so."]),
   ("Where water collects",
    ["Land Rover body design leaves recesses that hold water: the tailgate hinge area, the roof rail channels, the door bottom seams, and the lower tailgate on split-tailgate models. After a wash or a rain those recesses drain slowly onto paint that was already dried, leaving drip lines and, over time, mineral rings.",
     "We blow those recesses out with compressed air after washing and before drying, which is a small step that most washes skip and that prevents most of the drip staining owners see. It matters more on a coated vehicle, where drips on the coating rinse off but drips left to dry repeatedly on the same spot still leave a mark."]),
   ("Large glass and the panoramic roof",
    ["A lot of glass area means a lot of surface for mineral spotting and interior film. The panoramic roof gets glass-specific decontamination and a sealant. Interior glass on a vehicle that carries dogs and wet gear takes on more film than average and gets a two-stage clean.",
     "The <a href=\"/vehicles/suv-detailing/\">SUV page</a> covers third rows, cargo areas and load floors, all of which apply. The <a href=\"/vehicles/leather-and-luxury-interiors/\">luxury interior page</a> covers the surface-by-surface approach."]),
 ],
 "faq": [
   ("How often does Range Rover leather need attention?", "It depends on use. A lake-and-trail vehicle needs it at the end of each season, not annually. Leather coating before the season keeps sunscreen and lake water on a sacrificial layer."),
   ("Why do I get drip lines under the tailgate after washing?", "Body recesses hold water and drain slowly onto dried paint. We blow them out with compressed air before drying, which prevents most of it."),
   ("Can you restore crazed wood trim?", "No \u2014 crazed lacquer is a refinish. We clean and protect intact veneer; we will tell you when it is beyond that."),
 ],
},
{
 "slug": "jeep-wrangler",
 "name": "Jeep Wrangler",
 "nav": "Jeep Wrangler",
 "title": "Jeep Wrangler Detailing in Hartford, WI \u2014 Soft Tops, Drain Plugs & Trail Mud | Sudz Up",
 "meta": "Jeep Wrangler detailing in Hartford, WI. Soft top care, hard top removal and storage, the interior drain plugs, trail and beach use, and why a Wrangler cabin gets wet on purpose. Call 414-286-1609.",
 "h1": "Jeep Wrangler Detailing",
 "lede": "A Wrangler is the only vehicle we work on that was designed to have its interior hosed out, and that changes almost everything about how it should be cleaned.",
 "glance": [("Interior", "Designed to get wet"), ("Top", "Soft or hard, both need care"), ("Drains", "Plugs in the floor"), ("Use", "Trail, beach, doors off")],
 "body": [
   ("An interior that is meant to get wet",
    ["Wrangler floors have drain plugs and the carpet is designed to be removable or, on many trims, absent. The interior can be rinsed. That is a genuine advantage for trail mud and beach sand and it is a genuine trap, because rinsing an interior that then does not fully dry produces exactly the damp-and-organic combination that grows mould.",
     "So the rule is that a Wrangler interior can be washed, and must be dried, and the plugs must be pulled to let it drain and then replaced. Carpet, where fitted, comes out and dries separately. The rubber floor underneath gets cleaned and dressed. We do this on every Wrangler and we check the plugs are back in, because a missing plug is a floor full of road spray."]),
   ("Soft tops",
    ["A soft top is fabric or vinyl over a frame, with plastic windows. Fabric tops take a specific cleaner and a fabric protectant that restores water repellency \u2014 detergent strips it and the top starts wetting through. Vinyl tops take a vinyl cleaner and a UV protectant, matte, because a glossy dressing on a soft top attracts dust and looks wrong.",
     "The plastic windows are the fragile part. They scratch under anything abrasive, they haze under UV, and they crack when folded cold. They get a plastic-specific cleaner and polish, never glass cleaner with ammonia, and they are cleaned before the top is folded, not after."]),
   ("Hard tops, doors off, and storage",
    ["Hard tops and doors come off, and the seals they leave behind take grit and UV all summer. Seals get cleaned and conditioned so they still seal in October. The top and doors in storage get cleaned before they go in, because dirt on a stored panel bonds over a summer.",
     "Doors-off driving fills the cabin with everything on the road, and a Wrangler that has done a summer open needs the dry-then-wet sequence \u2014 compressed air through every gap, then the rinse, then a proper dry."]),
   ("Trail, beach and paint",
    ["Wranglers go places that scratch paint. Pinstriping from brush on trails, sand blasting on beach runs, and rock rash on the lower panels. Light pinstriping corrects; deeper scratches through the clear do not, and on a trail vehicle the honest answer is often to correct what is safe and coat the result so the next season's contact marks the coating rather than the paint.",
     "The <a href=\"/vehicles/truck-detailing/\">truck page</a> covers underside and arch cleaning, which on a Wrangler after a trail season is the most contaminated part of the vehicle."]),
 ],
 "faq": [
   ("Can you hose out a Wrangler interior?", "Yes, and it must then be dried properly with the drain plugs pulled and replaced. Rinsing without drying is how a Wrangler cabin grows mould."),
   ("How do you clean a soft top?", "Fabric tops get a fabric cleaner and a repellency protectant; vinyl tops a vinyl cleaner and matte UV protectant. The plastic windows get plastic-specific products only, and are cleaned before folding."),
   ("Will trail pinstriping polish out?", "Light pinstriping, yes. Scratches through the clear coat, no. On a trail vehicle we correct what is safe and coat it so next season's contact marks the coating."),
 ],
},
{
 "slug": "ford-f-150",
 "name": "Ford F-150",
 "nav": "Ford F-150",
 "title": "Ford F-150 Detailing in Hartford, WI \u2014 Aluminum Body, Work Cabs & Beds | Sudz Up",
 "meta": "Ford F-150 detailing in Hartford, WI. What an aluminum body changes about paint care, why the bed still corrodes, work-truck cab wear and the tailgate step. Call 414-286-1609.",
 "h1": "Ford F-150 Detailing",
 "lede": "The F-150 has had an aluminum body for a decade, and most owners have never had anyone explain what that changes about looking after it.",
 "glance": [("Body", "Aluminum since 2015"), ("Frame & bed", "Still steel"), ("Cab", "Work-truck wear"), ("Bed", "Liner + drains")],
 "body": [
   ("Aluminum body, steel everything else",
    ["Since the 2015 model year, F-150 cabs and beds have been aluminum. Aluminum does not rust the way steel does, and the visible body panels on an F-150 will not develop the rocker and arch rot that older steel trucks do. That is real, and it is where the good news ends.",
     "The frame is steel. The underside components are steel. Fasteners and brackets are steel. And where steel and aluminum meet, galvanic corrosion can occur if the joint is wet and salted \u2014 which in Wisconsin it is, for five months. So the underside of an F-150 needs the same winter attention as any truck, and arguably more care about keeping the dissimilar-metal joints clean. The paint on the aluminum panels behaves like any paint: it marks, it takes fallout, it needs decontamination and protection."]),
   ("The bed",
    ["The bed is aluminum too, and it dents more easily than steel did, which is why the factory bed liner options matter. A spray-in liner holds liquid in its texture and absorbs oil into its surface. A drop-in liner traps water and grit between itself and the bed, where it sits.",
     "We clean beds with the liner out where it comes out, the floor underneath addressed, and the drain holes cleared. The tailgate step and the integrated tailgate work surface collect grit in their mechanisms and get blown out."]),
   ("Work cab wear",
    ["Most F-150s in our area work. The cab takes workwear abrasion on the driver's bolster, boot scuffs on the sill, tool grease on the door card, and the food and drink of a working day in the console. The rear seat, on crew cabs, is a shelf for gear and the floor beneath it has never seen a vacuum.",
     "We treat the driver's quarter as its own job, blow out the console and cupholders with compressed air, fold the rear seat both ways, and check the under-seat storage that most owners have never opened. The <a href=\"/vehicles/truck-detailing/\">truck page</a> covers the full approach."]),
   ("Fleet and lease",
    ["A lot of F-150s are fleet units or lease returns, and both come back on a checklist. The <a href=\"/commercial/fleet-detailing/\">fleet page</a> covers scheduled resets; the <a href=\"/guides/lease-return-inspection-what-gets-charged/\">lease return guide</a> covers which items on a work truck's inspection are addressable and which are repair."]),
 ],
 "faq": [
   ("Does an aluminum F-150 need rust protection?", "The body panels will not rust. The frame, underside components and fasteners are steel and still do, and the joints between steel and aluminum can corrode galvanically when wet and salted. The underside still needs winter attention."),
   ("Is F-150 paint different because the body is aluminum?", "The paint behaves like any paint. It marks, takes fallout, and needs decontamination and protection the same way."),
   ("Do you clean under a drop-in bed liner?", "Yes. Drop-ins trap water and grit against the bed floor, and it is one of the most neglected surfaces on a truck."),
 ],
},
{
 "slug": "corvette",
 "name": "Chevrolet Corvette",
 "nav": "Corvette",
 "title": "Corvette Detailing in Hartford, WI \u2014 Composite Panels, Low Cars & Seasonal Storage | Sudz Up",
 "meta": "Corvette detailing in Hartford, WI. Composite body panels and what they mean for correction, a low car's lower-panel exposure, the removable roof, and going into storage clean. Call 414-286-1609.",
 "h1": "Corvette Detailing",
 "lede": "A Corvette's panels are not metal, and that changes how heat, correction and dents behave in ways most owners have never had spelled out.",
 "glance": [("Body", "Composite panels"), ("Height", "Low \u2014 front takes the road"), ("Roof", "Removable"), ("Usage", "Seasonal")],
 "body": [
   ("Composite panels and correction",
    ["Corvette bodies are composite \u2014 fibreglass on older cars, sheet-moulded compound and carbon on newer ones \u2014 and the paint over composite behaves differently under a polisher from paint over steel. Composite does not conduct heat away from the surface the way metal does, so a polisher held in one place builds heat faster and the paint can be damaged before the operator feels it. Panel edges and body lines are thinner and heat faster still.",
     "So correction on a Corvette is done with more pad movement, lower speeds where the panel needs it, and an infrared thermometer on the surface. It is not harder. It is different, and a shop that corrects a Corvette the way it corrects a sedan will eventually burn one."]),
   ("A low car takes the road on its face",
    ["The front bumper, the lower valance and the leading edge of the bonnet on a Corvette sit closer to the road than on almost anything else, and they take stone chips, road tar and bug impact at a rate a taller car does not. Bug residue on a summer of highway miles is protein that etches if it bakes, and on a low front it bakes.",
     "Front-end decontamination \u2014 tar and bug removal before iron and clay \u2014 is a larger part of a Corvette detail than usual. Paint protection film on the front is worth a conversation on a car driven regularly; a coating on the rest is what makes the bugs rinse off rather than etch."]),
   ("The removable roof",
    ["Targa panels and convertible tops come off and go in the boot or the garage, and the seals they leave behind take UV and grit. Seals get cleaned and conditioned so they still seal in September. Stored panels get cleaned before storage because a summer of dirt on a stored panel bonds. On convertibles the fabric top takes a fabric cleaner and a repellency protectant, and the rear window \u2014 glass or plastic depending on generation \u2014 gets the right product for which."]),
   ("Seasonal, and stored",
    ["Most Corvettes here are good-weather cars, with the hand-care marring pattern that comes from being looked after between drives and a five-month storage period every year. Correction and coating in spring, no dry dusting through summer, and full decontamination and protection before storage in November. Our <a href=\"/guides/winter-storage-prep-for-a-collector-car/\">storage guide</a> and the <a href=\"/services/paint-correction/chenequa-wi/\">summer-car correction page</a> cover both."]),
 ],
 "faq": [
   ("Is Corvette paint harder to correct?", "Not harder \u2014 different. Composite panels do not shed heat like metal, so the polisher builds surface temperature faster. More pad movement, lower speeds where needed, and a thermometer on the panel."),
   ("Why does my front end look worse than the rest of the car?", "It is closer to the road. Chips, tar and bug impact land there at a higher rate, and bug protein etches when it bakes on a low front in sun."),
   ("Should a seasonal Corvette be coated?", "Yes, in spring after correction, and it should go into storage wearing it. It is what keeps hand-care through summer from putting marring back and what protects the paint over five months in the dark."),
 ],
},
{
 "slug": "subaru",
 "name": "Subaru",
 "nav": "Subaru",
 "title": "Subaru Detailing in Hartford, WI \u2014 Soft Paint, Outdoor Owners & Dog Hair | Sudz Up",
 "meta": "Subaru detailing in Hartford, WI. Soft, easily marked paint, the outdoor-household cabin, dog hair in the cargo area, roof rack drip lines and why coating a Subaru early pays. Call 414-286-1609.",
 "h1": "Subaru Detailing",
 "lede": "Subarus have soft paint and owners who take them outdoors, which is a combination that produces the most predictable wear pattern of any make we see.",
 "glance": [("Paint", "Soft \u2014 marks easily"), ("Owners", "Outdoor, dogs, racks"), ("Cabin", "Back-forward wear"), ("Coating", "Early, on the roof too")],
 "body": [
   ("Soft paint",
    ["Japanese finishes generally, and Subaru's in particular, are soft by trade consensus. A drying towel, a duster, a brush wash \u2014 each marks a Subaru more visibly than it would a German car. The upside is that soft paint corrects easily and finishes to a high gloss. The downside is that it re-marks just as easily, so correction without a change in wash method is a year's reprieve.",
     "Coating a Subaru is therefore worth more than usual, and coating the roof matters more than on most cars, because the roof is where the rack goes."]),
   ("The rack",
    ["Most Subarus we see carry a roof rack, a cargo box, a bike rack or a kayak, and rack loading on soft paint leaves the directional scratching that a standard correction never looks for \u2014 along the rails, under the tower feet, on the rear pillars where things are leaned. Rain running off the rack leaves drip lines on the paint below each foot.",
     "The <a href=\"/services/paint-correction/delafield-wi/\">rack-loading correction page</a> and the <a href=\"/services/exterior-detailing/hartland-wi/\">rack and drip-line page</a> cover both in detail. On a Subaru they apply with extra force."]),
   ("The cabin of an outdoor household",
    ["Dog hair is the Subaru signature. It weaves into cargo-area carpet and rear-seat fabric and a vacuum removes the top layer and leaves the rest. It needs a rubber brush or a dedicated hair tool to lift it against the pile before vacuuming, and on a cargo area that has carried a dog for years that step is most of the job.",
     "Behind the hair is the rest of the outdoor profile: trail mud in the rear footwells, wet gear in the boot, the spare well under the load floor collecting whatever drained through. The <a href=\"/guides/pet-hair-and-odor-in-cars/\">pet hair guide</a> covers the home routine; the <a href=\"/vehicles/suv-detailing/\">SUV page</a> covers the load floor and the back-forward wear pattern."]),
   ("Windscreens and the cabin filter",
    ["Subaru windscreens are large and the cabin intake on many models sits where it pulls in road dust and pollen readily. The interior glass takes on film fast and the filter loads fast, and on an outdoor vehicle that also carries a dog the filter is often the single largest improvement to how the cabin smells. We check it on every Subaru."]),
 ],
 "faq": [
   ("Is Subaru paint soft?", "By trade consensus, yes. It marks easily and corrects easily. A coating is worth more than usual because it takes the contact that would otherwise mark the paint."),
   ("How do you get dog hair out of a Subaru cargo area?", "A rubber brush or hair tool worked against the pile to lift the woven hair, then vacuum. A vacuum alone takes the top layer and leaves the rest."),
   ("Should I coat the roof?", "Yes, especially on a Subaru with a rack. The roof takes rack contact and drip lines, and a coating makes both far less likely to mark soft paint."),
 ],
},
]
