# -*- coding: utf-8 -*-
"""
Service page content, hand-written per service.

Anti-overlap rule: each page OWNS a different depth, and links rather than
re-explains when it needs a concept another page owns.

  full-detail          -> sequence and time
  interior-detailing   -> surfaces and extraction
  exterior-detailing   -> decontamination
  odor-removal         -> source vs. mask
  paint-correction     -> defects and measurement
  ceramic-coating      -> chemistry and lifespan
  interior-protection  -> prevention

PRICING STILL NEEDED FROM GIO (marked "Quoted" below rather than invented):
  - exterior-detailing standalone (previously only sold inside the VIP package)
  - paint-correction (genuinely condition-dependent; quoting per vehicle is
    defensible, but confirm he wants it presented that way)
  - interior-protection
"""

SERVICES = [
{
 "slug": "full-detail",
 "name": "Full Interior & Exterior Detail",
 "nav": "Full Detail",
 "price": "From $200",
 "title": "Full Interior & Exterior Car Detailing in Hartford, WI | Sudz Up Detailing",
 "meta": "Full interior and exterior auto detailing in Hartford, WI. $200 cars, $250 SUVs and trucks. A full day on one vehicle, done in the right order. Call or text 414-286-1609.",
 "h1": "Full Interior & Exterior Detail",
 "lede": "One vehicle, one day, everything in the right order. This is the service that resets a car completely rather than improving parts of it.",
 "card": "The complete reset \u2014 interior and exterior, done in sequence over a full day.",
 "glance": [("Cars", "$200"), ("SUVs & trucks", "$250"), ("Typical time", "Most of a day"), ("Best month", "April or September")],
 "body": [
   ("Why order is the whole job",
    ["Almost anyone can clean a car. The difference between a detail and a long wash is sequence, and sequence is the thing that cannot be rushed or reordered without losing the result.",
     "We work outside-in and dry-to-wet. The exterior gets decontaminated first, because that work throws fallout and because the wheels and arches are the dirtiest thing on the vehicle and you do not want that migrating inward. Then the interior gets dry work \u2014 compressed air, brushes, vacuum \u2014 before any moisture is introduced. Then wet interior work. Then glass, last, because glass shows every mistake made before it.",
     "Get that order wrong and you produce a car that looks worse than one cleaned carelessly. Shampoo the carpet before dusting the dash and you settle dust onto a damp surface. Do the glass early and you finish the job by breathing on it and smearing it. The sequence is not a preference, it is the difference between the work holding and not."]),
   ("What a full day actually buys you",
    ["The honest reason this service costs more than the sum of its parts is time, and specifically uninterrupted time on one vehicle. We do not run three cars in parallel and rotate between them.",
     "That matters because most of the value in detailing is in dwell time and in the second pass. Chemicals need to sit. Carpet needs to be extracted, allowed to release, and extracted again. Panels need to be assessed after they are clean, which is the only point at which you can actually see what is wrong with them. None of that survives a schedule that has another car waiting.",
     "It also means we find things. A full day on a vehicle turns up the water ingress under a mat, the seat rail that has never been cleaned, the door seal that has torn. We tell you about all of it, including the parts we cannot fix."]),
   ("The exterior half",
    ["The exterior side is a full decontamination rather than a wash: wheels and arches first, a proper two-bucket hand wash, chemical iron removal, a clay stage to pull bonded contamination out of the clear coat, and then protection.",
     "The clay stage is the one people have never had done and cannot un-feel afterwards. Run your hand over your bonnet through a plastic bag. That grit is embedded contamination, and no amount of washing removes it. It is also what makes paint feel rough and look flat even when it is clean. The full explanation of that process lives on the <a href=\"/services/exterior-detailing/\">exterior detailing page</a>.",
     "What this service does not include is machine polishing to remove swirls and scratches. That is <a href=\"/services/paint-correction/\">paint correction</a>, it is a separate discipline, and it takes considerably longer than a day on its own. We will tell you honestly whether your paint would benefit."]),
   ("The interior half",
    ["Everything from our <a href=\"/services/interior-detailing/\">interior service</a> is included, with the extra time a full day allows. Seats move fully fore and aft so the rails and the carpet beneath get done. Mats come out and get treated separately from the carpet they were covering, which is almost always the dirtier of the two.",
     "Compressed air comes before the vacuum, not after. A vacuum nozzle cannot generate airflow inside a three-millimetre gap, so seat seams, belt buckle recesses, console gaps and vents get blown out first and then collected.",
     "Hard surfaces get cleaned and then treated to a matte finish rather than a gloss. A shiny dash reflects into the windscreen and is genuinely distracting when the sun is low, which on a Wisconsin winter afternoon is most of the drive home."]),
   ("Who this is actually for",
    ["Three situations make the full detail obviously worth it rather than a nice-to-have.",
     "Selling or trading a vehicle. It is the cheapest thing you can do to a car before photographs, and it changes what a buyer believes about how the car was maintained. Sequence it a day or two before the listing goes live rather than two weeks ahead.",
     "Coming out of a Wisconsin winter. Five months of brine, interior moisture and salt in the carpet backing is exactly what a full reset is for, and April is when doing it actually holds.",
     "And buying a used car. You do not know who was in it or what they did in it. One full detail at the start gives you a known baseline and, frankly, makes it feel like yours."]),
 ],
 "faq": [
   ("How long does a full detail take?",
    "Most of a working day for a typical car, longer for a large or heavily soiled vehicle. We book one vehicle at a time rather than rotating between several, which is the main reason the result holds better than a faster service."),
   ("Do I need to leave the vehicle with you?",
    "Yes, for the day. Call or text 414-286-1609 to arrange drop-off and we will give you an honest pick-up time rather than an optimistic one."),
   ("Does this remove scratches and swirl marks?",
    "No. That is paint correction, a separate machine-polishing process. The full detail cleans, decontaminates and protects the paint but does not remove defects from it. We will tell you if we think your paint would benefit from correction."),
   ("Is it worth doing on an older or high-mileage car?",
    "Often more worth it than on a new one, because there is more to recover. We will be straight with you before we start about what will come back and what will not \u2014 a twelve year old interior can look genuinely excellent, but some wear is permanent and we would rather you know that up front."),
   ("What is the best time of year to book one?",
    "April, once road salt season is finished, or September if your priority is protection heading into winter. Our <a href=\"/guides/wisconsin-car-care-by-month/\">month-by-month guide</a> explains why, and why March is the most common timing mistake."),
 ],
 "related": ['interior-detailing', 'exterior-detailing', 'ceramic-coating'],
},
{
 "slug": "interior-detailing",
 "name": "Interior Detailing",
 "nav": "Interior Detailing",
 "price": "From $135",
 "title": "Interior Car Detailing in Hartford, WI | Sudz Up Detailing",
 "meta": "Interior car detailing in Hartford, WI. Compressed air, full vacuum, hot water extraction, VRP treatment and glass. $135 cars, $150 SUVs and trucks. Call 414-286-1609.",
 "h1": "Interior Detailing",
 "lede": "The inside of a car is where you actually spend your time, and it is the half that a car wash cannot touch. This is the service most people genuinely need.",
 "card": "Compressed air, deep vacuum, extraction, surface treatment and glass \u2014 the interior done properly.",
 "glance": [("Cars", "$135"), ("SUVs & trucks", "$150"), ("Typical time", "1\u20132 hours"), ("Best month", "January")],
 "body": [
   ("The vacuum is not the quick part",
    ["Most of the time on an interior detail goes into vacuuming, and most of that goes into places a normal vacuum has never reached.",
     "Seats get moved fully forward and fully back. The carpet under the seat rails collects more debris than any other surface in a vehicle and it is the single most commonly skipped area, because reaching it means moving seats twice.",
     "Floor mats come out and get done separately from the carpet underneath. That carpet is frequently dirtier than the mat that was covering it, which surprises people every time.",
     "Cargo areas get the load floor lifted and the spare wheel well cleared. On SUVs and estates that space collects an extraordinary amount of grit and it is almost never touched by anyone."]),
   ("Compressed air comes first",
    ["This is the step that separates a detail from a thorough clean, and it happens before the vacuum rather than after.",
     "A vacuum works by moving air across a surface. Inside a three-millimetre gap \u2014 a seat seam, a belt buckle recess, the channel where the console meets the carpet, a vent louvre \u2014 there is no airflow to move. The nozzle sits over the gap and nothing happens. You can vacuum a seam for a minute and remove nothing from inside it.",
     "Compressed air solves it by working the other direction: blow the debris out into the open cabin, then collect it. It is loud, it is messy, and it is the reason a detailed interior stays clean longer than a vacuumed one. Debris left in seams migrates back out over the following weeks, which is why a rushed clean looks like it did not last."]),
   ("Extraction, and why surface cleaning fails",
    ["Carpet and cloth upholstery are not surfaces, they are depth. The visible fibres are the top of a structure that goes down to a backing layer, and almost everything that matters \u2014 salt, spilled liquid, embedded dirt, moisture \u2014 lives below the part you can see.",
     "Hot water extraction injects solution into that depth and pulls it back out under vacuum along with whatever it has dissolved. Wiping, scrubbing or spraying works the top layer only, which is why a stain treated on the surface reappears a week later. It did not come back. It wicked upward from the backing as the carpet dried, which is exactly what it was always going to do.",
     "In Wisconsin this matters more than it does most places, because what is in the backing is largely road salt. Salt is hygroscopic \u2014 it draws moisture in \u2014 so it keeps a carpet damp, which is what produces the smell people notice in February and blame on a spill they cannot find."]),
   ("Surface treatment, and why we finish matte",
    ["Vinyl, rubber and plastic treatment is the step people misunderstand most. It is not a shine product. Its job is to clean hard surfaces properly and then replace protection on plastics that lose plasticiser to UV over time.",
     "Untreated dashboards in Wisconsin have a hard life. Years of sun through a windscreen dries the surface out, and once it goes chalky and starts to craze, no product reverses it. Treatment slows that considerably, but only if it is done before the damage rather than after.",
     "We finish matte rather than glossy on purpose. A glossy dash reflects into the windscreen and is genuinely distracting at low sun angles. If you want the wet-look finish, say so and we will do it \u2014 but we will not do it by default."]),
   ("Glass, and the film nobody talks about",
    ["Interior glass is the other tell of whether a detail was done properly. Windscreens develop a film from plastic off-gassing combined with road dust and, in older vehicles, years of accumulated residue.",
     "That film is why oncoming headlights scatter and dazzle at night, and most people have adapted to it so gradually that they no longer notice it is there. It is also why a single pass with a household glass spray usually makes things worse \u2014 it dissolves the film and redistributes it into streaks instead of removing it.",
     "We do interior glass in two stages for that reason. It is a small thing that changes night driving noticeably."]),
   ("What this service does not include",
    ["Spot stain treatment is included \u2014 a coffee ring, a scuff on a door card, a patch on a seat base. Widespread staining across multiple surfaces is a bigger job and we will quote it honestly rather than pretend it fits.",
     "Deep odor work is also separate. If a vehicle smells of smoke, pets, or mildew from a leak, the smell has a source and cleaning the interior does not necessarily remove it. That is <a href=\"/services/odor-removal/\">odor removal</a>, and it is a different process.",
     "If you want the exterior done as well, the <a href=\"/services/full-detail/\">full detail</a> covers both and costs less than booking the two separately."]),
 ],
 "faq": [
   ("What is the difference between this and a car wash vacuum?",
    "Depth and sequence. A wash vacuum works the surfaces you can see. This service uses compressed air to clear seams a vacuum physically cannot reach, moves the seats to get the carpet beneath them, and extracts carpet rather than cleaning its surface."),
   ("Will you get old stains out?",
    "Sometimes completely, sometimes substantially. Water-based spills caught within days usually come out fully; coffee and soda respond well; grease and oil need a solvent approach and often come out. Ink, dye transfer from clothing and heavy grass staining are the hardest, and there the honest answer is often major improvement rather than total removal. We will tell you which one you are looking at before we start."),
   ("How long does the interior stay clean?",
    "Longer than you would expect, and the compressed air step is why. Debris left in seams works its way back out over the following weeks, so a clean that skipped that step looks like it failed after a fortnight when really it was never finished."),
   ("Is January really the best month for this?",
    "For interiors, yes. That is when salt is actively sitting in the carpet backing and when trapped winter moisture is at its worst, so the work has the most to remove and the most lasting effect. It is also our quietest month, so it is the easiest time to get booked in."),
   ("Do you do third rows and cargo areas?",
    "Yes, both, and the load floor gets lifted and the spare well cleared. SUVs, minivans and trucks are $150 rather than $135 because there is genuinely more of them, not as a surcharge."),
 ],
 "related": ['full-detail', 'odor-removal', 'interior-protection'],
},
{
 "slug": "exterior-detailing",
 "name": "Exterior Detailing",
 "nav": "Exterior Detailing",
 "price": "Quoted",
 "title": "Exterior Car Detailing & Decontamination in Hartford, WI | Sudz Up Detailing",
 "meta": "Exterior detailing in Hartford, WI. Two-bucket hand wash, chemical iron removal, clay decontamination and protection \u2014 not a car wash. Call or text 414-286-1609.",
 "h1": "Exterior Detailing",
 "lede": "The difference between this and a car wash is not effort. It is decontamination \u2014 removing what is chemically bonded to your paint rather than what is sitting on top of it.",
 "card": "Two-bucket hand wash, iron removal, clay decontamination and protection.",
 "glance": [("Price", "Quoted"), ("Method", "Two-bucket hand wash"), ("Key stage", "Iron + clay decon"), ("Best month", "April")],
 "body": [
   ("Washing and decontaminating are different jobs",
    ["A wash removes what is loose. Decontamination removes what has bonded. Almost every driver has only ever had the first one done, which is why paint that is genuinely clean still feels rough and looks flat.",
     "Test it yourself. Wash the car, dry it, then put your hand inside a thin plastic bag and run it lightly over the bonnet or the boot lid. What you feel as grit is not dirt sitting on the surface \u2014 it is contamination embedded in and bonded to the clear coat. Soap will never move it, and no amount of washing harder will either.",
     "That embedded layer is also what scatters light. It is the reason a clean car can still look dull, and the reason wax applied over it never delivers what the bottle promised. You are protecting the contamination, not the paint."]),
   ("Iron fallout, and why Wisconsin paint gets it badly",
    ["The worst of that bonded layer is iron. Brake dust is hot metal particles that embed into clear coat and then corrode in place, which is what those tiny rust-coloured specks on light-coloured paint actually are.",
     "A chemical iron remover dissolves them. It is the step that makes people uncomfortable the first time they watch it, because as it reacts the whole car runs purple. That colour is the chemical bonding with dissolved iron, and the amount of it coming off a car that has never had this done is genuinely startling.",
     "Wisconsin vehicles get this worse than most for two reasons: winter braking on treated roads produces a lot of dust, and brine keeps the paint surface damp for longer, which gives the particles more opportunity to corrode into place rather than blow off."]),
   ("The clay stage",
    ["After the chemical work, clay handles what is left \u2014 tar, overspray, rail dust, tree sap residue and industrial fallout that iron remover does not touch.",
     "Clay works mechanically. Lubricated and drawn across the surface, it shears bonded contamination off level with the clear coat. It is slow and it is done panel by panel by hand, and it is the single biggest reason a properly decontaminated car feels like glass afterwards.",
     "This is also the stage that determines whether anything applied afterwards works. Wax, sealant or a <a href=\"/services/ceramic-coating/\">ceramic coating</a> all bond to whatever surface they meet. Apply protection over contamination and it bonds to the contamination, then fails early when that layer lets go."]),
   ("Two buckets, and why the method matters more than the soap",
    ["Almost all wash-induced swirl marks come from one thing: putting a dirty mitt back onto the paint. The two-bucket method exists to break that cycle \u2014 one bucket of clean solution, one to rinse the mitt into, with grit guards so what comes off the car stays at the bottom.",
     "Wheels and arches are done first, with dedicated tools that never touch paint. They are by a wide margin the dirtiest part of a vehicle and cross-contaminating from them is how careful people still put scratches into their own paint.",
     "This is also the honest argument against automatic washes. A touchless wash cannot decontaminate, so it does nothing about the bonded layer. A brush wash drags whatever the previous vehicle left on the brushes across your clear coat. Neither is a disaster occasionally, but doing it weekly for years is how a car accumulates the swirl pattern that eventually needs <a href=\"/services/paint-correction/\">correction</a> to remove."]),
   ("What this service does and does not fix",
    ["It fixes contamination, roughness, dullness caused by embedded fallout, and it leaves protected paint that stays cleaner and releases dirt more easily.",
     "It does not fix defects in the clear coat itself. Swirl marks, wash scratches, water spot etching and oxidation are damage to the surface rather than something sitting on it, and removing them means removing a controlled amount of clear coat with a machine polisher. That is <a href=\"/services/paint-correction/\">paint correction</a>.",
     "Decontamination is a prerequisite for correction, though, so this work is never wasted. It is also the point at which paint defects first become clearly visible \u2014 which is why people frequently book correction after having decontamination done, not before."]),
 ],
 "faq": [
   ("How is this different from a good car wash?",
    "A wash removes what is loose. This removes what is chemically bonded into the clear coat, using an iron remover and a clay stage. That bonded layer is what makes clean paint still feel rough and look flat, and no wash of any quality removes it."),
   ("Why does the car turn purple during the process?",
    "That is the iron remover reacting with dissolved iron particles \u2014 mostly embedded brake dust. The colour is the chemical doing its job. On a vehicle that has never had it done, the amount that comes off is usually a surprise."),
   ("Do I need this if I already wax my car?",
    "If you have never had decontamination done, then the wax is bonding to contamination rather than to paint, which is why it never quite looks or lasts like it should. Decon first, protection second, is the order that makes the protection work."),
   ("Will this remove my swirl marks?",
    "No. Swirls are defects in the clear coat and removing them requires machine polishing, which is paint correction. Decontamination often makes swirls more visible, simply because the surface is clean enough to see them for the first time."),
   ("When should I book exterior work in Wisconsin?",
    "April, once the county has finished treating roads, so the decontamination actually holds. September is the other good window if the goal is protection ahead of winter."),
 ],
 "related": ['full-detail', 'paint-correction', 'ceramic-coating'],
},
{
 "slug": "odor-removal",
 "name": "Odor Removal",
 "nav": "Odor Removal",
 "price": "Quoted",
 "title": "Car Odor Removal in Hartford, WI \u2014 Smoke, Pet & Mildew | Sudz Up Detailing",
 "meta": "Car odor removal in Hartford, WI. Smoke, pet, mildew and spill odors removed at the source rather than masked. Assessed and quoted per vehicle. Call 414-286-1609.",
 "h1": "Odor Removal",
 "lede": "Every smell has a physical source somewhere in the vehicle. If you have not removed the source, you have not removed the smell \u2014 you have covered it, and it comes back.",
 "card": "Smoke, pet, mildew and spill odors \u2014 found at the source and removed, not masked.",
 "glance": [("Price", "Quoted"), ("First step", "Find the source"), ("Method", "Removal + extraction"), ("Assessment", "Before we start")],
 "body": [
   ("Why air fresheners and sprays fail",
    ["A smell is airborne molecules coming off a physical thing. Something in the vehicle is releasing them continuously, and it will keep releasing them until it is gone or sealed.",
     "Air fresheners add a second, stronger smell alongside the first. Odor-eliminating sprays chemically neutralise the molecules currently in the air, which genuinely works \u2014 for a few hours, until the source releases more. Neither touches the thing doing the releasing.",
     "This is why people describe the smell as coming back, and why it always seems worse on the first warm day. Heat increases the rate at which the source off-gasses. Nothing changed except the temperature."]),
   ("Finding the source is most of the job",
    ["The single most common mistake, including by detailers, is treating the whole interior rather than finding what is actually causing the problem. That is expensive, it takes hours, and it frequently does not work.",
     "So we look first. Under and behind seats, under carpet where we can lift it, the spare wheel well, cabin air filter and the ducting behind it, seat foam, the boot floor, and the headliner \u2014 which people forget entirely and which is where smoke residue concentrates most heavily.",
     "Sometimes the answer is unglamorous and immediate: something under a seat, a spill in the spare well, a filter that has not been changed in five years. We would far rather find that in twenty minutes and tell you than sell you a full treatment you did not need."]),
   ("The four kinds we see, and what each actually needs",
    ["Smoke is the hardest, because tar condenses onto every surface including the headliner and the inside of the ducts, and because it is genuinely cumulative over years. It needs surface-by-surface cleaning rather than a single treatment, and with a heavily smoked vehicle the honest outcome is often major reduction rather than total elimination.",
     "Pet odor is usually in the foam and the carpet backing rather than on the surface, because the source is liquid that soaked in. Extraction is the answer, and it usually takes more than one pass.",
     "Mildew means water got in and stayed, and the real job is finding the leak. A leaking seal, a blocked sunroof drain or a windscreen surround will re-wet the carpet within weeks, so treating the smell without finding the water is money spent twice.",
     "Spills \u2014 milk being the worst by a distance \u2014 are extraction jobs, and how well they go depends almost entirely on how long ago it happened."]),
   ("Wisconsin has a fifth kind",
    ["Every winter we get vehicles where nothing was spilled, nothing lives in the car, nobody smokes, and it still smells. That is trapped moisture, and it is close to a local specialty.",
     "Short winter trips never warm the cabin enough to dry out what boots brought in, so it sits in the carpet backing. Road salt in that same backing is hygroscopic \u2014 it actively draws in and holds moisture \u2014 so the carpet never gets a chance to dry between trips. Repeat daily from December and by February you have a genuinely unpleasant smell with no identifiable cause.",
     "That one responds well, because the fix is exactly what extraction is for. It is also why we push interior work in January rather than waiting for spring."]),
   ("What we will tell you before we start",
    ["We assess before quoting, because the range on this work is enormous and a number given over the phone would be a guess.",
     "We will also tell you if we think the result will fall short. Heavily smoked vehicles, long-standing pet damage soaked into foam, and mildew where the leak is still active all have honest ceilings. In some cases the real answer is replacing a component \u2014 a cabin filter, sometimes carpet or foam \u2014 rather than cleaning it, and we will say so even though it is not work we are selling you.",
     "If the smell turns out to be part of a wider interior problem, the <a href=\"/services/interior-detailing/\">interior detail</a> may cover it. If the car needs everything, the <a href=\"/services/full-detail/\">full detail</a> is better value than booking separately."]),
 ],
 "faq": [
   ("Can you get cigarette smoke out completely?",
    "Sometimes, and it depends heavily on how long and how heavily the vehicle was smoked in. Tar condenses onto every surface including the headliner and the air ducting, so it is a surface-by-surface job rather than a single treatment. With a long-term heavy smoker's car, the honest outcome is usually major reduction rather than complete elimination, and we will say so before taking your money."),
   ("Do you use ozone?",
    "Ozone has a real but narrow use, and it is not a substitute for removing the source. Treating a vehicle with ozone while the source is still in it gets you a car that smells of ozone for a few days and then smells of the original problem again. Source first, always."),
   ("My car smells and nothing was ever spilled in it \u2014 what is it?",
    "In winter, almost always trapped moisture in the carpet backing, held there by road salt that draws in and retains water. Short trips never warm the cabin enough to dry it out. It responds well to extraction."),
   ("Why do you need to see the car before quoting?",
    "Because the range is enormous. A cabin filter and a spill in the spare well is a short job; a decade of smoke in a headliner is not. Quoting either one over the phone would mean guessing, and we would rather look."),
   ("Will the smell come back?",
    "Not if the source is gone. If it returns, it means either the source was not fully removed or something is re-creating it \u2014 most often an active water leak. That is why we look for the leak on any mildew job rather than just treating the carpet."),
 ],
 "related": ['interior-detailing', 'full-detail', 'interior-protection'],
},
{
 "slug": "paint-correction",
 "name": "Paint Correction",
 "nav": "Paint Correction",
 "price": "Quoted",
 "title": "Paint Correction & Swirl Removal in Hartford, WI | Sudz Up Detailing",
 "meta": "Paint correction in Hartford, WI. Machine polishing to remove swirl marks, wash scratches and oxidation. Assessed and quoted per vehicle. Call or text 414-286-1609.",
 "h1": "Paint Correction",
 "lede": "Correction removes defects from your clear coat rather than filling or hiding them. It is the only process that actually fixes swirl marks, and it is finite \u2014 which is why it has to be done carefully.",
 "card": "Machine polishing to permanently remove swirls, scratches and oxidation.",
 "glance": [("Price", "Quoted per vehicle"), ("Method", "Machine polishing"), ("Assessed", "Under inspection light"), ("Best months", "June or September")],
 "body": [
   ("What swirl marks actually are",
    ["Swirl marks are thousands of fine scratches in the clear coat, each one too small to see individually. You notice them as a spiderweb or halo pattern around a point light source \u2014 direct sun, a streetlight, a torch held close to the panel.",
     "They are damage, not dirt. Nothing you wash the car with will remove them, because there is nothing sitting on the surface to remove. The surface itself has been cut.",
     "The overwhelming majority come from wash technique rather than from the road. Automatic brush washes drag whatever the previous vehicle left across your paint. Drying with a towel that has picked up grit does it. Washing with one bucket and reloading a dirty mitt does it. Years of small, well-intentioned damage accumulates into a finish that looks permanently dull because light scatters instead of reflecting."]),
   ("How correction works, and why it is finite",
    ["The clear coat on your car is a layer of lacquer over the colour, typically somewhere in the region of forty to sixty microns on a modern factory finish \u2014 thinner than a sheet of paper.",
     "Correction works by levelling. A machine polisher with an abrasive compound removes a controlled few microns of clear coat, taking the surface down to the base of the scratches so what remains is flat and reflects light uniformly. The scratch is not filled. The surface around it is lowered to meet it.",
     "Which is why this is a finite resource. Every correction consumes clear coat, and you cannot put it back. A car can typically take a handful of proper corrections in its life. This is the entire reason we assess before quoting and the reason we will sometimes recommend doing less than you asked for. A shop that will happily do aggressive correction on a car that has already had it twice is selling you a problem you will not see until the clear coat fails."]),
   ("Assessment: the part that determines everything",
    ["Correction cannot be quoted from a photograph or a phone call, and any quote given that way is a guess.",
     "We inspect under focused light, which is the only way to see the true defect pattern \u2014 daylight hides most of it and a bright showroom hides the rest. What we are looking for is what kind of defects are present, how deep they run, whether the clear coat has enough left to work with, and whether previous correction has already been done.",
     "Some defects will not come out. If a scratch catches your fingernail, it is usually through the clear coat, and levelling to its base would remove more clear than is safe. Deep stone chips are through to primer or metal. We will tell you which of your defects are coming out and which are not, before you commit to anything."]),
   ("One stage or multiple",
    ["A single-stage correction uses one compound and pad combination to remove the majority of lighter defects. It typically recovers most of the gloss for a fraction of the time and cost, and for a daily-driven car it is very often the right answer.",
     "Multi-stage means cutting more aggressively first, then refining with progressively finer steps to remove the haze that the cutting stage leaves behind. It gets closer to a genuinely defect-free finish and it takes substantially longer.",
     "The honest framing is diminishing returns. Going from neglected to noticeably better is fast. Going from very good to nearly perfect takes several times as long as everything before it and consumes more clear coat. Which one is right depends on the car, how it is used and what you actually want from it \u2014 and that is a conversation, not a package."]),
   ("Correction and coating belong together",
    ["A <a href=\"/services/ceramic-coating/\">ceramic coating</a> is clear and it seals whatever is underneath it. Coating a swirled car locks the swirls in for the life of the coating, and removing them later means removing the coating first.",
     "So if you are considering both, correction comes first, always, and they are done as one job. That sequence is not upselling \u2014 it is the only order that makes sense, and doing it the other way round wastes the coating.",
     "The paint also has to be fully decontaminated before correction begins, since polishing over bonded contamination drags it across the panel. That work is covered on the <a href=\"/services/exterior-detailing/\">exterior detailing page</a> and is part of any correction job."]),
 ],
 "faq": [
   ("Why can you not quote paint correction over the phone?",
    "Because the work depends entirely on what the defects are, how deep they run and how much clear coat the car has left \u2014 none of which is visible in a photo. A phone quote would be a guess, and correction is not something to guess at, since every pass permanently removes clear coat."),
   ("Will correction remove every scratch?",
    "No. As a rough test, if a scratch catches your fingernail it is likely through the clear coat and levelling to its base would remove more clear than is safe. Fine swirls, wash marring, light water spot etching and oxidation come out well. Deep scratches and stone chips do not."),
   ("How long does correction last?",
    "The defects are permanently gone \u2014 they do not grow back. What determines how long the finish stays that way is how the car is washed afterwards. Going back to an automatic brush wash will rebuild the same swirl pattern within a year or two."),
   ("Can I have correction more than once?",
    "A few times over a car's life, depending on how much clear coat it started with and how aggressive each correction was. It is a finite resource, which is why we assess first and will sometimes recommend a lighter approach than you came in asking for."),
   ("Should I get correction or just a ceramic coating?",
    "If the paint has defects and you want both, correction has to come first \u2014 a coating is clear and seals in whatever is underneath it. Coating over swirls locks them in for the life of the coating."),
 ],
 "related": ['ceramic-coating', 'exterior-detailing', 'full-detail'],
},
{
 "slug": "interior-protection",
 "name": "Interior Protection",
 "nav": "Interior Protection",
 "price": "Quoted",
 "title": "Interior Protection \u2014 Fabric & Leather Coating in Hartford, WI | Sudz Up Detailing",
 "meta": "Interior protection in Hartford, WI. Fabric sealant, leather and vinyl coating applied after a detail so spills, salt and UV do less damage. Call or text 414-286-1609.",
 "h1": "Interior Protection",
 "lede": "Everything else we do is repair. This is the one service that works ahead of the damage instead of after it \u2014 and the damage it prevents is largely the kind you cannot undo.",
 "card": "Fabric sealant and leather or vinyl coating applied to a freshly detailed interior.",
 "glance": [("Price", "Quoted"), ("Applied", "After a detail"), ("Covers", "Fabric, leather, vinyl"), ("Best month", "July")],
 "body": [
   ("Prevention is the only real fix for some of this",
    ["Most interior damage can be improved after the fact. Some cannot, and that is the category this service exists for.",
     "A dashboard that has gone chalky and started to craze from years of UV is not recoverable. Leather that has dried out and cracked at the bolster is not recoverable. A light-coloured fabric seat that took a red drink and sat for a week is often permanently marked. Cleaning helps all three look better; none of them go back to what they were.",
     "Protection is cheap relative to what it prevents, and it is genuinely boring \u2014 you never see it work. The evidence is a four-year-old interior that still looks like a two-year-old one."]),
   ("Fabric sealant, and what it actually does",
    ["A fabric sealant bonds to individual fibres and changes their surface energy, so liquid beads on top of the weave instead of immediately wicking down into the backing.",
     "That does not make a seat spill-proof and we will not tell you it does. What it does is buy time. An untreated cloth seat takes a spilled drink into the foam within seconds, at which point extraction is the only option and complete removal is not guaranteed. A treated seat holds it on the surface long enough that a towel handles it. That difference is the whole product.",
     "It also slows the daily grind \u2014 body oils, food residue and general soiling working into the fibre \u2014 which is what makes a driver's seat look tired years before the rest of the interior does."]),
   ("Leather and vinyl coating",
    ["Automotive leather is almost always coated rather than raw. There is a polymer finish over the hide, and that finish is what fails \u2014 not the leather beneath it. Once it cracks, you are looking at repair or replacement.",
     "What kills it is a combination of UV, heat and abrasion, concentrated almost entirely on the driver's outer bolster, which takes the friction of getting in and out twice a day, and on whichever panels get direct sun.",
     "A protective coating adds a sacrificial layer that takes the abrasion and blocks a meaningful amount of UV. It also keeps the surface from drying, which is what makes leather stiff before it cracks. We finish these matte for the same reason we finish dashboards matte \u2014 glare off a glossy seat or dash is genuinely distracting at low sun angles."]),
   ("Why July matters here more than people think",
    ["Interiors take their worst damage in high summer, and almost nobody treats it as a seasonal problem the way they treat winter salt.",
     "Sustained sun through a windscreen dries plasticiser out of dash plastics and moisture out of leather. A parked car in July builds cabin temperatures far above ambient, and that heat accelerates every one of those processes. A vehicle that sits in a work car park all day, every day, through a Wisconsin summer is taking real cumulative damage while nothing visible happens.",
     "The practical implication is that protection is worth applying in spring or early summer rather than autumn. Applied in October it spends its first five months protecting against a season that was never the threat."]),
   ("How this fits with everything else",
    ["Protection is always applied to a freshly cleaned surface, never over an existing one. Sealing a dirty seat locks the soiling into the fibre and makes it harder to remove later, so this is booked alongside an <a href=\"/services/interior-detailing/\">interior detail</a> or a <a href=\"/services/full-detail/\">full detail</a> rather than on its own.",
     "It is worth most on vehicles that are about to face the hardest conditions rather than ones that already have. A new or newly bought car, a family vehicle carrying kids and food daily, a work truck, a light-coloured interior, or a car with a long daily commute in the sun.",
     "It is worth least on an interior that is already damaged. Protecting a cracked dash preserves the crack. We will tell you if that is what we are looking at."]),
 ],
 "faq": [
   ("Does fabric protection make seats spill-proof?",
    "No, and anyone who tells you otherwise is overselling it. It makes liquid bead on the surface instead of wicking straight into the foam, which buys you the time to blot it with a towel. That is a real difference, but it is time, not immunity."),
   ("How long does interior protection last?",
    "It wears with use rather than expiring on a date, so the driver's seat and the surfaces that get sun will need renewing well before the rest. High-touch areas are the ones to watch."),
   ("Is it worth it on an older car?",
    "It depends whether the damage has already happened. On a tired but intact interior, yes \u2014 it slows what is coming. On a dash that has already crazed or leather that has already cracked, protection preserves the current state rather than improving it, and we will tell you that rather than take the booking."),
   ("Can you apply this without a detail?",
    "We would rather not. Protection bonds to whatever surface it meets, so applying it over existing soiling seals that soiling into the fibre and makes it harder to remove later. It goes on after cleaning, as part of the same visit."),
   ("When is the best time of year to have it done?",
    "Spring or early summer, before the sun does its damage rather than after. July is the hardest month of the year on interiors and almost nobody thinks of it that way."),
 ],
 "related": ['interior-detailing', 'full-detail', 'odor-removal'],
},
{
 "slug": "ceramic-coating",
 "name": "Ceramic Coating",
 "nav": "Ceramic Coating",
 "price": "From $599",
 "title": "Ceramic Coating in Hartford, WI | Sudz Up Detailing",
 "meta": "Ceramic coating in Hartford, WI. Paint decontamination, prep and coating application from $599. Drive in from anywhere in southeast Wisconsin. Call or text 414-286-1609.",
 "h1": "Ceramic Coating",
 "lede": "A ceramic coating is a semi-permanent layer bonded to your paint. It makes the car easier to wash, holds gloss for far longer than wax, and stands up to Wisconsin road salt in a way nothing you apply by hand every few months will.",
 "card": "Semi-permanent paint protection \u2014 decontamination, prep and coating application.",
 "glance": [("Starting price", "$599"), ("Prep", "Assessed per vehicle"), ("Typical time", "Multi-day"), ("Best for", "Salt, gloss, easier washing")],
 "body": [
   ("What a ceramic coating actually does",
    ["A coating bonds to the clear coat and forms a hard, slick layer on top of it. Water beads and runs off instead of sitting, dirt has less to grip, and washing gets substantially faster because most of what lands on the car does not bond to it.",
     "The gloss is the part people notice first, but the durability is the part that matters here. Wax gives you a few months in a Wisconsin winter. A coating holds through the salt season and keeps holding.",
     "What it will not do is make the paint invincible. It resists chemical etching and makes washing gentler on the finish, but it is not armour against stone chips, and it does not stop scratches from an automatic car wash brush. Anyone telling you otherwise is selling you something."]),
   ("Preparation is most of the job",
    ["The coating itself takes a fraction of the time. Everything before it is where the work is, and it is the part that determines whether the result is worth paying for.",
     "Paint gets washed, then chemically decontaminated to strip iron fallout and road film, then clayed to pull embedded contamination out of the clear coat. A coating applied over contamination locks that contamination in, permanently, under a layer you cannot easily remove.",
     "How much correction the paint needs on top of that depends entirely on the vehicle. Some cars need very little. Others carry years of swirl marks that will show through a coating and be sealed under it. We assess your paint and tell you what it needs before quoting, rather than applying a fixed process to every car regardless of condition."]),
   ("Wisconsin salt, specifically",
    ["Road salt is the reason most people in Washington County end up asking about coatings. It is corrosive, it sits in every lower panel and wheel arch through the whole winter, and it accelerates the failure of clear coat that is already sun-tired.",
     "A coating gives salt less to hold onto and makes a winter wash far more effective, because the grime releases instead of needing to be scrubbed. That matters: scrubbing salt off paint by hand is itself a common source of swirl marks.",
     "The best time to have a coating applied is before the salt starts, not after a winter of it has already done its work."]),
   ("Timing and what to expect",
    ["This is not a same-day service. Preparation and curing take time, and rushing either step produces a worse result than not coating at all. Plan on leaving the vehicle with us for more than a day.",
     "Coatings need to cure before the car sees rain or a wash. We will tell you exactly how long for the product going on your vehicle and what to avoid in that window.",
     "Aftercare is straightforward but it is not nothing. Coated cars still need washing, just far less effort per wash. We will walk you through it when you collect."]),
 ],
 "faq": [
   ("How much does ceramic coating cost?", "Pricing starts at $599 and depends on vehicle size and how much preparation the paint needs. We assess the paint and give you a firm figure before any work starts."),
   ("How long does a ceramic coating last?", "It depends on the product and on how the vehicle is washed and stored. We will tell you the expected life of the specific coating we recommend for your vehicle rather than quoting a headline number that may not apply."),
   ("Does my paint need correcting first?", "That depends on its condition. Some vehicles need very little, others carry years of swirls that would be sealed under the coating. We assess it and tell you honestly what it needs before quoting."),
   ("Can I run it through an automatic car wash afterwards?", "You can, but we would rather you did not. Brush washes are a leading cause of swirl marks, and a coating does not prevent that. Touchless or a proper hand wash gets far more out of the coating you paid for."),
   ("Is it worth it if my car is older?", "Often yes, particularly for salt protection, but it depends on the state of the clear coat. If the clear coat is already failing, a coating will not rescue it and we will say so rather than take the money."),
 ],
 "related": ['paint-correction', 'exterior-detailing', 'full-detail'],
},
{
 "slug": "truck-and-suv-detailing",
 "name": "Truck & SUV Detailing",
 "nav": "Truck & SUV",
 "price": "From $150",
 "title": "Truck & SUV Detailing in Hartford, WI | Sudz Up Detailing",
 "meta": "Truck and SUV detailing in Hartford, WI. Work trucks, family SUVs and third-row vehicles. $150 interior, $250 full detail. Call or text 414-286-1609.",
 "h1": "Truck & SUV Detailing",
 "lede": "Trucks and SUVs are priced separately because they genuinely take longer. More surface area, more seats, more cargo space and usually more in it.",
 "card": "Work trucks, family SUVs and third-row vehicles. More space, more time.",
 "glance": [("Interior only", "$150"), ("Full detail", "$250"), ("Covers", "Trucks, SUVs, vans"), ("Third row", "Included")],
 "body": [
   ("Why the price is different",
    ["We charge $150 for the interior service and $250 for the full detail on trucks and SUVs, against $135 and $200 for cars. That is not an arbitrary surcharge — it reflects real additional work.",
     "A three-row SUV has roughly twice the interior volume of a sedan, two extra footwells, a considerably larger cargo area, more glass, and more door jambs. The exterior has more panel area, taller sides and larger wheels. On a truck there is a bed liner, a tailgate, and often a set of running boards that collect an extraordinary amount of grit.",
     "We would rather price it honestly upfront than quote a car price on the phone and adjust it when you arrive, which is a practice we have heard about often enough from customers to know it happens."]),
   ("Work trucks",
    ["A working pickup carries material a passenger car never sees: construction dust, sawdust, feed, fertiliser, mud in layers, and grease from tools and hands.",
     "The high-value areas on a work truck are almost all hidden. Under the rubber mats, where soil compacts into a hard layer. Along the seat rails. Behind and under the rear seat of a crew cab, which on many trucks folds up and reveals a storage area that has never been emptied. The vents, which have been drawing in dust for years.",
     "Running boards and door sills deserve specific mention. You step on them every time you get in, so they carry the abrasive material that then goes into your carpet. Cleaning the carpet without cleaning the sills means you re-contaminate the floor within a week."]),
   ("Family SUVs and third rows",
    ["A family SUV has the opposite problem: not industrial material, but a very large number of small organic deposits in very awkward places.",
     "Third rows are the worst-served area in any vehicle. They are rarely used, rarely vacuumed, and things fall into the seat mechanism and stay there. Second row footwells beside child seat bases collect crushed food that has been ground into the carpet by feet. The cargo area under the load floor holds everything that has rolled back there over a decade.",
     "We fold and move seating to reach these areas, and we lift the load floor. If child seats are fitted, we can remove them where it is safe to do so — cleaning around a car seat is close to pointless. If you would prefer to refit them yourself, tell us and we will leave them out. That is genuinely your call."]),
   ("What we need to know when you book",
    ["Tell us honestly what condition the vehicle is in. There is no judgement involved and it is not a negotiation tactic — it determines how much time we set aside and what we bring.",
     "The specific things worth mentioning: any spill you know about, whether pets travel in the vehicle, whether anyone smokes in it, whether it has been used for anything agricultural or construction related, and whether the cargo area has had anything wet left in it.",
     "If a vehicle is substantially rougher than described when it arrives, we will call you with a revised figure before we start rather than presenting it at collection. That is how we would want it handled."]),
 ],
 "faq": [
   ("Why do trucks and SUVs cost more to detail?", "More interior volume, extra footwells and rows, larger cargo area, more glass and jambs, more panel area outside. It reflects genuine additional time rather than an arbitrary surcharge."),
   ("Do you clean third-row seating?", "Yes, and it usually needs it most. Third rows are rarely vacuumed and debris falls into the seat mechanism. We fold and move seating to reach it properly."),
   ("Do you detail work trucks?", "Yes. The value on a work truck is mostly in the hidden areas — under mats, along seat rails, behind the rear seat of a crew cab, and in the vents."),
   ("What if my vehicle is much dirtier than I described?", "We will call you with a revised figure before starting rather than surprising you at collection."),
 ],
 "related": ['full-detail', 'interior-detailing', 'odor-removal'],
},
]
