# -*- coding: utf-8 -*-
"""
Service x city pages: /services/<service>/<city>/

THE RULE FOR THIS FILE. Every entry is hand-written for that specific
combination and must answer one question: why does THIS service in THIS town
need its own page? If the honest answer is "it doesn't", the combination does
not get built. A page whose local content would work equally well with the
town name swapped out is exactly the thing that gets a local site filtered,
and it is worse than not having the page at all.

Practically that means each entry needs a real local hook -- a specific road,
employer, lake, track, subdivision pattern, industry, commute or seasonal
event -- that changes what we actually find in vehicles from that town for
that service. Population figures and "conveniently located near" filler do
not count.

Build order is deliberate: combinations with the strongest local hook first.
A weak combination is left unbuilt rather than padded.

Sources for local facts: Washington County / Ozaukee County / Waukesha County
public information, WisDOT, Wisconsin DNR, and venue operators. Anything not
verified stays out.
"""

# (service_slug, city_slug) -> content
# h1/title/meta/lede/glance/body/faq are all per combination.
SERVICE_CITIES = [

{
 "service": "interior-detailing",
 "city": "slinger-wi",
 "title": "Interior Car Detailing in Slinger, WI | Sudz Up Detailing",
 "meta": "Interior car detailing for Slinger, WI drivers. Ten minutes from our Hartford shop. Track dust, commuter wear and winter salt handled properly. Call 414-286-1609.",
 "h1": "Interior Detailing in Slinger, Wisconsin",
 "lede": "Slinger is about ten minutes from our shop, and it sends us a kind of interior work we do not get from anywhere else in the county.",
 "glance": [("From our shop", "About 10 minutes"), ("Cars", "$135"), ("SUVs & trucks", "$150"), ("Booking", "Often same week")],
 "body": [
   ("The Speedway changes what we pull out of Slinger cars",
    ["Slinger Super Speedway runs a quarter-mile high-banked asphalt oval right in the village, and on race nights the paddock and the surrounding lots fill with vehicles that have spent an evening parked next to a track surface being scrubbed by tyres.",
     "What that produces is a very fine, dark rubber-and-asphalt dust that behaves differently from ordinary road dirt. It is light enough to stay airborne for hours, so it settles through open windows and into the cabin rather than staying on the outside of the car. Then it works into seat stitching, seat belt webbing and the felt lining of door pockets, where it is stubborn precisely because it is greasy rather than gritty.",
     "You cannot vacuum it out. A vacuum needs airflow across a surface and this material is bonded into fibre. It needs compressed air to break it loose first and then extraction to lift it, which is the same reason we do that sequence on every interior but it matters more here than on a car that has only seen supermarket car parks."]),
   ("Two very different Slinger vehicles",
    ["The village has grown a lot on the residential side, and a good share of what we see is the newer-subdivision commuter profile: a car that runs Highway 60 and then I-41 south toward Milwaukee five days a week, with all the wear that implies concentrated in the driver's quarter of the cabin.",
     "The other half is the older village core and the surrounding farmland, and those vehicles carry a completely different problem set. Field dust in spring, hay chaff, and the fine grit that comes off gravel drives and settles into every horizontal surface in the car.",
     "We treat those as separate jobs even though they book as the same service. A commuter car needs the driver's seat, sill and floor mat worked hard and the rest done normally. A farm vehicle needs the whole cabin blown out before anything else happens, because starting with a vacuum just redistributes the dust."]),
   ("Winter, and why we push January here",
    ["Highway 60 through Slinger gets treated early and often, and the I-41 interchange means a lot of local vehicles pick up brine from a much wider road network than the village itself.",
     "That salt ends up in the carpet backing, and because it draws in and holds moisture, a Slinger commuter car that does short trips in January never dries out between drives. That is what produces the February smell people blame on a spill they cannot find.",
     "January is our quietest month and it is when the salt is actually sitting in the carpet, so it is both the most effective and the easiest time to get a Slinger vehicle booked in."]),
 ],
 "faq": [
   ("How far is your shop from Slinger?",
    "About ten minutes down WI-83. We are at 2948 WI-83 in Hartford. Call or text 414-286-1609 before you head over so we can confirm we are on site."),
   ("Do you deal with race night dust?",
    "Regularly. It is greasy rather than gritty, so it bonds into seat stitching and belt webbing where a vacuum cannot reach it. Compressed air first, then extraction, is what actually removes it."),
   ("Can I get in the same week?",
    "Usually, yes. Slinger is close enough that local vehicles are easy for us to slot in. January is by far the easiest month to book."),
 ],
},

{
 "service": "interior-detailing",
 "city": "west-bend-wi",
 "title": "Interior Car Detailing in West Bend, WI | Sudz Up Detailing",
 "meta": "Interior detailing for West Bend, WI drivers. High-mileage commuter cars, river-valley damp and winter salt handled properly. About 20 minutes from our shop. Call 414-286-1609.",
 "h1": "Interior Detailing in West Bend, Wisconsin",
 "lede": "West Bend is the largest community we serve, and its vehicles arrive with the most consistent wear pattern of anywhere in the county.",
 "glance": [("From our shop", "About 20 minutes"), ("Cars", "$135"), ("SUVs & trucks", "$150"), ("Common issue", "Driver's-quarter wear")],
 "body": [
   ("County-seat mileage concentrates the damage",
    ["West Bend is the county's employment centre, which means West Bend vehicles are doing real daily mileage rather than weekend errands. That shows up in the cabin in a very specific and very lopsided way.",
     "A high-mileage commuter wears out one quarter of its interior and leaves the rest nearly untouched. The driver's outer seat bolster goes first, from the friction of getting in and out twice a day. Then the steering wheel develops a polished patch at ten and two. Then the driver's floor mat holds ground-in dirt far worse than the other three, and the door sill takes a thousand boot scuffs.",
     "We treat that quarter as its own job with its own time budget. It is the part of the car you look at every single day, and it is the part a rushed detail always averages out across the whole cabin."]),
   ("The Milwaukee River holds damp longer than the rest of the county",
    ["The city sits on the Milwaukee River, and the low ground near the water holds humidity noticeably longer into spring than the higher ground west toward Hartford.",
     "For vehicles that park outside near the river, that means condensation forms under floor mats and stays there. If you have ever lifted a mat and found the carpet underneath damp when nothing was spilled, that is the mechanism, and it is far more common in West Bend cars than in cars from the hills around Erin or Richfield.",
     "Damp carpet plus road salt in the backing is the combination that produces a persistent musty smell. Surface cleaning will not touch it. Extraction pulls the moisture and the salt out together, which is the only thing that actually resolves it."]),
   ("Worth the twenty minutes",
    ["West Bend has its own options, so the honest question is why drive to Hartford. The answer is that we book one vehicle at a time rather than rotating between several, and interior work is where that difference is most visible.",
     "Dwell time is most of interior detailing. Chemicals need to sit. Carpet needs to be extracted, allowed to release and extracted again. None of that survives a schedule with another car waiting.",
     "Drop the vehicle in the morning and it is a twenty minute run each way. For an interior service you are usually looking at getting it back the same day."]),
 ],
 "faq": [
   ("How long does the drive from West Bend take?",
    "About twenty minutes to 2948 WI-83 in Hartford. Most West Bend customers drop off in the morning and collect the same day for interior work."),
   ("My carpet is damp but nothing was spilled \u2014 what is that?",
    "Condensation under the floor mats, which is common in vehicles parked outside near the Milwaukee River where humidity lingers. Combined with road salt in the carpet backing, it is the usual cause of a musty smell with no obvious source."),
   ("Why does only the driver's side look worn?",
    "Because that is where all the use is. On a high-mileage commuter the driver's bolster, wheel, mat and sill take essentially all the wear while the rest of the cabin stays close to new. We budget time to that quarter specifically."),
 ],
},

{
 "service": "odor-removal",
 "city": "kewaskum-wi",
 "title": "Car Odor Removal in Kewaskum, WI | Sudz Up Detailing",
 "meta": "Car odor removal for Kewaskum, WI. Dog, field, hunting season and damp-carpet smells removed at the source, not masked. Call or text 414-286-1609.",
 "h1": "Odor Removal in Kewaskum, Wisconsin",
 "lede": "Kewaskum sits at the north end of our area, right against the Kettle Moraine, and the odor work we get from up there is genuinely different from what comes out of the suburbs.",
 "glance": [("From our shop", "About 25 minutes"), ("Price", "Quoted"), ("Common source", "Dogs, field, damp"), ("First step", "Find the source")],
 "body": [
   ("Rural vehicles carry different smells",
    ["The Northern Unit of the Kettle Moraine State Forest starts just outside Kewaskum, and the village sits surrounded by working farmland. Vehicles from up there do things that suburban cars do not.",
     "Dogs are the most common single source, and specifically wet dogs after a field or a trail. The smell people describe is not really the dog, it is bacteria in the moisture the dog left in the seat foam and the carpet backing. That is why it fades when the car is dry and comes roaring back on the first humid day.",
     "The second most common is organic field material tracked in on boots. Mud, silage, manure, decaying plant matter. It works down into the carpet backing where it stays damp and continues to break down, which is a genuinely biological process rather than a cleaning problem."]),
   ("Hunting season is its own category",
    ["Every autumn we get vehicles that carried game, wet gear, or both, and those are among the harder jobs we do because the source is often blood or fluid that soaked into the boot carpet or the spare wheel well and was cleaned only on the surface.",
     "The spare well is the place people never look. It is below the load floor, it is not visible, and liquid that gets in there has nowhere to drain. We lift the floor and check it on every odor job for exactly that reason, and on hunting-season vehicles it is the source more often than not.",
     "If it soaked into the boot carpet backing rather than sitting on top of it, extraction is the answer and it usually takes more than one pass."]),
   ("Why we look before we quote",
    ["The range on this work is enormous, and quoting a rural odor job over the phone would mean guessing. Something under a seat is twenty minutes. Fluid that has been in the spare well since November is not.",
     "We will also tell you when the honest answer is replacement rather than cleaning. Foam that has absorbed a large volume of organic liquid and sat for months sometimes cannot be recovered, and we would rather tell you that than take money for a treatment that gets you halfway.",
     "If the vehicle also needs general cleaning, the <a href=\"/services/interior-detailing/\">interior detail</a> may cover part of it and the <a href=\"/services/full-detail/\">full detail</a> is better value than booking separately."]),
 ],
 "faq": [
   ("Why does the dog smell come back on humid days?",
    "Because the source is bacteria in moisture that soaked into seat foam and carpet backing. Dry conditions suppress it; humidity reactivates it. Removing the moisture and the organic material is what actually stops it, rather than treating the air."),
   ("Do you handle vehicles used in hunting season?",
    "Yes, and we always lift the load floor and check the spare wheel well. Fluid that gets in there cannot drain and is the source far more often than people expect."),
   ("How far is Kewaskum from your shop?",
    "About twenty-five minutes down to 2948 WI-83 in Hartford. Odor work is assessed before we quote, so call or text 414-286-1609 and we will arrange a look."),
 ],
},

{
 "service": "full-detail",
 "city": "oconomowoc-wi",
 "title": "Full Interior & Exterior Detailing in Oconomowoc, WI | Sudz Up Detailing",
 "meta": "Full interior and exterior detailing for Oconomowoc, WI. Lake Country vehicles, boat-tow grime and beach sand handled properly. $200 cars, $250 SUVs. Call 414-286-1609.",
 "h1": "Full Detailing for Oconomowoc, Wisconsin",
 "lede": "Oconomowoc is Lake Country, and lake vehicles take a specific kind of beating that a standard detail schedule does not account for.",
 "glance": [("From our shop", "About 25 minutes"), ("Cars", "$200"), ("SUVs & trucks", "$250"), ("Peak need", "End of summer")],
 "body": [
   ("Lake vehicles are wet vehicles",
    ["Oconomowoc sits between Lac La Belle, Fowler Lake and Okauchee Lake, and a large share of what we see from there spends its summer hauling people and gear to and from water.",
     "That produces a combination we rarely see elsewhere in one vehicle: wet swimsuits and towels sitting on seats, sand ground into carpet, and sunscreen transferred onto every hard surface and every seat back. Sunscreen is the underrated one. It is oily, it holds dirt, and on light-coloured leather and vinyl it will stain if it is left through a hot week.",
     "The wet-and-sandy combination is worse than either alone. Wet sand tracked onto carpet dries into a crust bonded to the fibre, and a household vacuum passes straight over it without lifting anything. It needs to be broken up mechanically and extracted."]),
   ("Towing changes the exterior half",
    ["A vehicle that tows a boat trailer accumulates things that a commuter car does not. Ramp grit thrown up behind the trailer coats the rear of the vehicle. Tar and road film build up on the lower panels from summer highway miles. And the rear bumper and tailgate take repeated contact from loading gear.",
     "Lake water also leaves mineral deposits. Water thrown up at a ramp dries on hot paint and leaves spotting that is not dirt sitting on the surface but mineral bonded to it, and washing does nothing for it. That comes off in the decontamination stage.",
     "This is why a full detail suits Lake Country vehicles better than either half on its own. The exterior needs decontamination and the interior needs extraction, and doing one without the other on a boat-towing vehicle leaves half the summer in place."]),
   ("Time it for the end of the season",
    ["The instinct is to detail before summer so the car looks good for it. For a lake vehicle that is backwards.",
     "Everything that damages the interior and the paint happens between June and September. Detailing in May means the work is undone by July. Detailing in September means the sand, sunscreen, mineral spotting and tar all come out at once, and the paint gets protected heading into the salt season.",
     "September is also the right month for anyone considering a <a href=\"/services/ceramic-coating/\">ceramic coating</a>, because the summer damage can be corrected first and conditions still support a proper cure."]),
 ],
 "faq": [
   ("How far is Oconomowoc from your shop?",
    "About twenty-five minutes. A full detail is a full-day booking, so plan on dropping the vehicle in the morning and collecting it later that day."),
   ("Will you get sunscreen off leather?",
    "Usually, and how completely depends on how long it sat and how hot the car got. Caught within a few weeks it comes off well. Left through a hot summer on light-coloured leather it can leave a shadow, and we will tell you which you are looking at before starting."),
   ("When should a lake vehicle be detailed?",
    "September, once the season is over. Detailing in spring means the work gets undone by July. Doing it at the end pulls out the whole summer at once and protects the paint before salt season."),
 ],
},

{
 "service": "full-detail",
 "city": "mequon-wi",
 "title": "Full Interior & Exterior Detailing for Mequon, WI | Sudz Up Detailing",
 "meta": "Full interior and exterior detailing for Mequon, WI drivers. One vehicle a day, not a rotation. $200 cars, $250 SUVs and trucks. About 30 minutes. Call 414-286-1609.",
 "h1": "Full Detailing for Mequon, Wisconsin",
 "lede": "Mequon drivers pass a lot of detailers on the way here, so this page is mostly an argument about why some of them do it anyway.",
 "glance": [("From our shop", "About 30 minutes"), ("Cars", "$200"), ("SUVs & trucks", "$250"), ("Booking", "One vehicle per day")],
 "body": [
   ("The honest case for the drive",
    ["We are not going to pretend Mequon is short of options. It is a well-served part of Ozaukee County and there are competent detailers considerably closer to you than Hartford.",
     "What we offer that most volume shops do not is that we book one vehicle a day for a full detail rather than running three in parallel. That sounds like a small operational difference and it is actually the whole product, because most of the value in detailing is dwell time and the second pass.",
     "Chemicals need to sit before they are agitated. Carpet needs to be extracted, allowed to release, then extracted again. Paint needs to be assessed after it is clean, which is the only point at which its actual condition is visible. Every one of those steps is the first thing cut when another car is waiting on the same bay."]),
   ("Garage-kept cars have the opposite problem to commuters",
    ["A lot of what comes to us from Mequon is well-maintained, garage-kept and low-mileage, and those vehicles need a different approach from a high-mileage commuter.",
     "The interior is usually in good condition, so the work is preservation rather than recovery: keeping leather from drying at the bolsters, keeping the dash from taking UV damage, and dealing with the fine dust that accumulates in a car that is driven gently and often sits.",
     "The exterior is where the real work is, and it is almost always wash-induced. A cherished car that has been through automatic washes for years carries a swirl pattern that is invisible in a garage and obvious in direct sun. That is not something a full detail fixes \u2014 it needs <a href=\"/services/paint-correction/\">paint correction</a> \u2014 but a full detail is where you first see it clearly, because the paint has to be decontaminated before defects are visible at all."]),
   ("What the logistics actually look like",
    ["It is roughly thirty minutes each way, and a full detail is a full-day booking, so this is a drop-off rather than a wait.",
     "Most Mequon customers drop off in the morning and collect late afternoon. If you are combining it with correction or coating, that becomes a multi-day job and we will tell you the real timeline before you commit rather than an optimistic one.",
     "Call or text 414-286-1609 and we will be straight with you about whether the drive is worth it for what you actually need. If it is a wash and a vacuum, it is not, and we will say so."]),
 ],
 "faq": [
   ("Why drive to Hartford when there are detailers in Mequon?",
    "The only real answer is that we book one vehicle a day for a full detail instead of rotating between several, and dwell time is most of what makes detailing work. If what you need is a wash and a vacuum, the drive is not worth it and we will tell you so."),
   ("Is this a drop-off or can I wait?",
    "Drop-off. A full detail takes most of a working day. Most Mequon customers leave the vehicle in the morning and collect it in the late afternoon."),
   ("My car is garage-kept \u2014 do I need a full detail?",
    "Often what a garage-kept car actually needs is exterior decontamination and correction rather than a full clean, because the paint carries years of wash-induced swirls while the interior is close to new. We would rather assess it and recommend the narrower service than sell you the bigger one."),
 ],
},

{
 "service": "ceramic-coating",
 "city": "germantown-wi",
 "title": "Ceramic Coating for Germantown, WI | Sudz Up Detailing",
 "meta": "Ceramic coating for Germantown, WI drivers. Real protection against I-41 corridor brine and winter salt. From $599, prep assessed per vehicle. Call 414-286-1609.",
 "h1": "Ceramic Coating for Germantown, Wisconsin",
 "lede": "Germantown sits on the I-41 corridor, which makes it one of the strongest cases for coating anywhere in our area \u2014 and one of the places the honest downside matters most.",
 "glance": [("From our shop", "About 20 minutes"), ("From", "$599"), ("Prep", "Assessed per vehicle"), ("Best month", "September")],
 "body": [
   ("Corridor miles are what coatings are actually for",
    ["A large share of Germantown vehicles run I-41 south toward Milwaukee or north toward Fond du Lac daily, and interstate winter miles are a different exposure from village driving.",
     "Interstate lanes get treated first, most often and most heavily, and at highway speed you are not just driving over brine, you are driving through a continuous mist of it thrown up by everything around you. That mist reaches the whole vehicle rather than just the lower panels, and it dries into a film across the paint.",
     "A coating does not stop salt reaching the paint and nobody should tell you it does. What it does is make the surface far less willing to hold it. Brine film releases with a rinse instead of needing to be scrubbed off, and scrubbing is where winter paint damage actually comes from \u2014 not from the salt itself but from people dragging it across their own clear coat trying to remove it."]),
   ("The maintenance obligation nobody mentions when selling it",
    ["Here is the part that matters more for a Germantown commuter than for most people. A coating is not a substitute for washing. It is a surface that makes washing effective.",
     "A coated car that is never washed through a winter of corridor miles ends up with brine film bonded on top of the coating, at which point you have the same problem you started with plus a bill. A coated car that gets rinsed regularly through winter stays genuinely clean with very little effort, which is the actual benefit.",
     "So if you commute I-41 and you are not going to rinse the car every couple of weeks in winter, be honest with yourself about that before spending the money. We would rather tell you that up front than have you feel it did not deliver."]),
   ("Prep is the price variable",
    ["The $599 starting figure covers the coating on paint that is in good condition. What moves it is what has to happen before the coating goes on.",
     "A coating is clear and it seals in whatever is under it. If the paint carries swirls from years of automatic washes, coating it locks those in for the life of the coating, and removing them later means removing the coating first. So the paint has to be decontaminated, and often corrected, before anything is applied.",
     "That is why we assess rather than quote a flat number. A three-year-old garage-kept car might need decontamination only. A daily-driven corridor car that has been through brush washes for five winters may need <a href=\"/services/paint-correction/\">correction</a> first, and that is the larger part of the job."]),
 ],
 "faq": [
   ("Will a ceramic coating protect my car from road salt?",
    "It does not stop salt reaching the paint. It makes the surface far less willing to hold brine film, so it rinses off instead of needing to be scrubbed \u2014 and scrubbing is where most winter paint damage actually comes from."),
   ("Do I still have to wash a coated car?",
    "Yes, and on an I-41 commute that matters more than most. A coating makes washing effective, it does not replace it. Never washing a coated car through winter gets you brine bonded on top of the coating."),
   ("Why is the price a starting figure rather than fixed?",
    "Because prep is the variable. Coating is clear, so it seals in whatever is underneath. Paint in good condition needs decontamination only; paint with years of wash swirls needs correction first, and that is the bigger part of the job."),
   ("When should I book it?",
    "September. Temperatures and humidity still support a proper cure, summer damage can be corrected first, and the coating goes on with a full winter of corridor brine ahead of it."),
 ],
},
{
 "service": "interior-detailing",
 "city": "hartford-wi",
 "title": "Interior Car Detailing in Hartford, WI | Sudz Up Detailing",
 "meta": "Interior car detailing in Hartford, WI from the shop on WI-83. Pike Lake sand, downtown short-trip damp and salt handled properly. $135 cars, $150 SUVs. Call 414-286-1609.",
 "h1": "Interior Detailing in Hartford, Wisconsin",
 "lede": "This is the town we work in every day, and after a few years of it we can usually guess which part of Hartford a vehicle comes from before the owner tells us.",
 "glance": [("From our shop", "Local"), ("Cars", "$135"), ("SUVs & trucks", "$150"), ("Booking", "Often same week")],
 "body": [
   ("Pike Lake is in more Hartford cars than anywhere else",
    ["The Pike Lake Unit of the Kettle Moraine State Forest is minutes from the shop, and from June through August we pull a genuinely surprising volume of sand out of Hartford vehicles specifically.",
     "Beach sand behaves differently from road grit. It arrives wet, on feet and towels and bag bottoms, and it works down through the carpet pile while it is still damp. Then it dries in place and forms a crust bonded to the fibre rather than sitting loose on top of it.",
     "That crust is why a household vacuum achieves nothing against it. The nozzle passes over a surface that has effectively become solid, and the sand does not move. It has to be broken up mechanically first, worked out of the pile, and then extracted. People who have tried to deal with it themselves usually arrive convinced the sand is permanent."]),
   ("Downtown cars and subdivision cars have opposite problems",
    ["Vehicles that mostly do short trips around Main Street and the mill pond never get their engines properly warm in winter, which means cabin moisture never fully clears between drives. Those are the cars that turn up in March smelling musty with nothing spilled in them.",
     "The newer subdivisions on the edges of the city produce the opposite profile: real daily mileage down WI-83 and Highway 60 toward Milwaukee and Waukesha. That gives you highway grit worked into lower carpet, sun-baked dash tops from cars sitting in park-and-ride lots, and console debris from people eating on the road.",
     "Same town, same service, genuinely different work. The short-trip car needs extraction to pull moisture and salt out of the backing. The commuter needs the driver's quarter treated as its own job."]),
   ("Being local is the actual advantage",
    ["Hartford vehicles get the shortest turnaround we offer and the most scheduling flexibility, simply because everything comes through 2948 WI-83 anyway.",
     "For regular customers we can usually accommodate short notice when something comes up, and drop-offs are straightforward rather than a logistics exercise.",
     "If you are selling a vehicle, tell us when you are listing it. We would rather sequence the work a day or two before your photographs than have it sit collecting dust in a driveway for a fortnight."]),
 ],
 "faq": [
   ("Can I really not get beach sand out myself?",
    "Not with a household vacuum, no. Wet sand dries into a crust bonded to the carpet fibre, and a vacuum nozzle passes straight over it. It has to be broken up mechanically and extracted, which is a different process from vacuuming."),
   ("Can I get a same-week appointment in Hartford?",
    "Usually. Hartford is our base, so local vehicles are the easiest for us to slot in. Call or text 414-286-1609 and we will tell you honestly what we have open."),
   ("My car smells musty and nothing was spilled in it.",
    "Common in short-trip vehicles. Winter drives around town never warm the cabin enough to dry out the moisture your boots brought in, and road salt in the carpet backing holds it there. Extraction resolves it; surface cleaning does not."),
 ],
},
{
 "service": "interior-detailing",
 "city": "erin-wi",
 "title": "Interior Car Detailing in Erin, WI | Sudz Up Detailing",
 "meta": "Interior car detailing for Erin, WI. Golf season debris, gravel-road dust and Holy Hill traffic handled properly. About 15 minutes from our Hartford shop. Call 414-286-1609.",
 "h1": "Interior Detailing in Erin, Wisconsin",
 "lede": "Erin is rural, hilly and home to a championship golf course, and between those three things it sends us interiors unlike anywhere else in the county.",
 "glance": [("From our shop", "About 15 minutes"), ("Cars", "$135"), ("SUVs & trucks", "$150"), ("Peak season", "Golf season")],
 "body": [
   ("Golf season leaves a very specific mess",
    ["Erin Hills sits in the town and drew national attention when it hosted the U.S. Open, and from spring through autumn a meaningful share of Erin vehicles are carrying clubs, shoes and bags several times a week.",
     "The problem is not the clubs, it is the shoes and the boot. Spiked or soft-spiked golf shoes carry damp grass clippings and sand from bunkers, and both go straight into the boot carpet where the bag sits. Grass is the difficult one. Chlorophyll staining is among the hardest interior stains to remove fully, and it sets faster than people expect \u2014 a bag left on boot carpet overnight after a wet round will often mark it.",
     "Bunker sand compounds it. It is finer than beach sand and it works deep into the boot carpet and the spare wheel well, where it stays until someone lifts the load floor. We check that well on every Erin vehicle because it is almost always where the sand ended up."]),
   ("Gravel drives and hill roads",
    ["The town is rural with large lots, and a lot of Erin properties sit at the end of long gravel or crushed-stone drives.",
     "That produces fine limestone dust that gets tracked in at both ends of every trip and settles into dash vents, seat stitching and the felt of door pockets. It is pale, so on dark interiors it shows immediately and people notice it far more than the same volume of dark road grit.",
     "The Kettle Moraine terrain adds the rest. Steep, winding roads mean more lateral movement in the cabin, so loose debris migrates into seat gaps and under seats rather than staying on the floor where you can see it."]),
   ("Autumn brings other people's traffic",
    ["Holy Hill draws heavy visitor traffic through the fall colour season, and the roads through Erin carry a lot of it.",
     "Practically that means more time in slow traffic on leaf-covered rural roads, and wet leaves tracked into vehicles. Leaf tannin stains light carpet and upholstery, and like grass it sets as it dries rather than waiting politely.",
     "October is the month to book if your vehicle does that season every year. Getting the staining out before it has spent a winter setting makes a real difference to how completely it lifts."]),
 ],
 "faq": [
   ("Can you get grass stains out of boot carpet?",
    "Often substantially, sometimes completely, and it depends heavily on how long it sat. Chlorophyll is one of the harder interior stains and it sets as it dries, so a bag left overnight after a wet round is worse than one dealt with the same day."),
   ("Why is there sand in my spare wheel well?",
    "Bunker sand is fine enough to work through boot carpet, and the spare well is below the load floor where nothing disturbs it. We lift and check it on every vehicle from Erin, because that is usually where it has collected."),
   ("How far is Erin from your shop?",
    "About fifteen minutes. Call or text 414-286-1609 and we can usually fit local vehicles in the same week."),
 ],
},
{
 "service": "interior-detailing",
 "city": "germantown-wi",
 "title": "Interior Car Detailing in Germantown, WI | Sudz Up Detailing",
 "meta": "Interior car detailing for Germantown, WI. Family vehicles, car seats, school-run wear and commuter mileage handled properly. About 20 minutes. Call 414-286-1609.",
 "h1": "Interior Detailing in Germantown, Wisconsin",
 "lede": "Germantown sends us more family vehicles than anywhere else we serve, and family vehicles fail in a completely predictable pattern that most detailing skips.",
 "glance": [("From our shop", "About 20 minutes"), ("Cars", "$135"), ("SUVs & trucks", "$150"), ("Most common", "Family vehicles")],
 "body": [
   ("What a car seat does to the seat under it",
    ["The single most common thing we find in a Germantown vehicle is a child seat that has not been removed in two years, and the upholstery beneath it in a condition the owner has genuinely never seen.",
     "Two things happen under there. Crumbs, drink spills and general debris funnel down the sides of the seat base and collect in the seam and the crevice at the back, where nothing reaches them. And the seat belt path and the anchor points trap material in gaps a few millimetres wide.",
     "The second is compression. A car seat under tension for years leaves permanent indentation, and while cleaning improves the appearance considerably, the compression itself does not fully recover. We tell people that before we start rather than after, because it is the one thing a detail cannot undo.",
     "If you can, remove the seats before dropping the vehicle. If you would rather not disturb the fitting, tell us and we will work around them \u2014 but the result underneath will be limited by what we can reach."]),
   ("The school-run and grocery-run wear pattern",
    ["Germantown's growth has been heavily residential, and a lot of local driving is short, repetitive trips \u2014 school, sports, shops \u2014 rather than long commutes.",
     "That produces a distinctive profile: heavy rear-cabin wear, which almost no other vehicle type has. Rear floor mats destroyed while the fronts look fine. Door cards scuffed at kid height. Rear seat backs marked from shoes. Boot floors carrying sports kit residue and the ground-in grit that comes with it.",
     "We budget time to the rear cabin on these specifically. Standard practice is to work the front thoroughly and give the back a pass, which is exactly backwards for this kind of vehicle."]),
   ("Food is the underrated one",
    ["Eating in the car is close to universal in family vehicles, and the consequences go somewhere people do not look.",
     "Dairy is the worst by a wide margin. Milk or yoghurt that gets into a seat seam or down a console gap and is not fully removed will smell within days and keep smelling, because the source is protein breaking down in a warm enclosed space. It is the most common cause of the family-car smell nobody can locate.",
     "If that is the actual problem, cleaning the interior may not solve it on its own \u2014 that is <a href=\"/services/odor-removal/\">odor removal</a>, and it starts with finding where the liquid ended up rather than treating the whole cabin."]),
 ],
 "faq": [
   ("Should I take the car seats out before bringing it in?",
    "If you can, yes. The upholstery underneath is usually the worst area in the vehicle and we cannot reach it properly with seats fitted. If you would rather not disturb the fitting we will work around them, but the result under there will be limited."),
   ("Will the dent under the car seat come out?",
    "Cleaning improves how it looks, but compression from years under tension does not fully recover. We would rather tell you that up front than have you expecting it."),
   ("My family car smells and I cannot find why.",
    "Nine times out of ten it is dairy \u2014 milk or yoghurt down a seat seam or console gap. It is protein breaking down in a warm space, so it keeps producing smell until the source is physically removed."),
 ],
},
{
 "service": "odor-removal",
 "city": "west-bend-wi",
 "title": "Car Odor Removal in West Bend, WI | Sudz Up Detailing",
 "meta": "Car odor removal for West Bend, WI. Smoke, damp and spill odors traced to the source rather than masked. About 20 minutes from our Hartford shop. Call 414-286-1609.",
 "h1": "Odor Removal in West Bend, Wisconsin",
 "lede": "West Bend has the highest turnover of used vehicles in our area, and a large share of the odor work we get from there arrives with a car that somebody just bought.",
 "glance": [("From our shop", "About 20 minutes"), ("Price", "Quoted"), ("Common case", "Just-bought vehicles"), ("First step", "Find the source")],
 "body": [
   ("Somebody else's smell in a car you just bought",
    ["The most common West Bend odor job is a vehicle bought within the last month where the smell only became obvious after a week of ownership.",
     "There is a reason for that timing. A car being sold has usually had a surface clean and something fragranced applied, and both of those genuinely work \u2014 for a week or two. Once the masking fades and the vehicle warms up in the sun, the original source starts off-gassing again and the buyer discovers what they actually purchased.",
     "It is also why people so often describe it as the smell appearing rather than returning. From their point of view it was not there when they bought it, which is entirely true and entirely misleading."]),
   ("Where a previous owner's smell actually lives",
    ["Because we did not clean the car the first time, we have to assume nothing and check everywhere, which is different from working on a vehicle whose history you know.",
     "Smoke is the most common and the most stubborn, and the headliner is the place people never think of. Tar condenses upward onto it and it is the last surface anybody cleans before a sale. The cabin air filter is second \u2014 if it has not been changed, every fan setting pushes the previous owner's air through it.",
     "After that it is the usual sequence: under and behind seats, under carpet where it lifts, the spare wheel well, and seat foam. On a bought-in vehicle the spare well is worth checking early, because it is genuinely never cleaned before a sale."]),
   ("What we can tell you before you spend anything",
    ["We assess before quoting on every odor job, and on a just-bought vehicle that assessment is worth having even if you decide to do nothing.",
     "Sometimes the answer is a cabin filter and twenty minutes. Sometimes it is a decade of smoke in a headliner, where the honest outcome is major reduction rather than elimination. Occasionally the real answer is that a component needs replacing rather than cleaning, and we will say so even though it is not work we are selling you.",
     "If the vehicle also needs a general reset \u2014 which a just-bought car usually does \u2014 the <a href=\"/services/full-detail/\">full detail</a> is better value than booking the two separately."]),
 ],
 "faq": [
   ("I bought a car and the smell showed up a week later. Why?",
    "Because it was masked rather than removed. A fragranced product applied before a sale genuinely works for a week or two; once it fades and the car warms up, the original source starts off-gassing again."),
   ("Where does previous-owner smoke smell actually sit?",
    "Mostly the headliner and the cabin air filter. Tar condenses upward onto the headliner and it is the last surface anyone cleans before selling, while an unchanged filter pushes the previous owner's air through the vents on every setting."),
   ("Is it worth getting a used car assessed even if I do nothing?",
    "Often, yes. Knowing whether you are looking at a twenty minute fix or a ceiling you cannot get past is useful information, and we will tell you honestly which one it is."),
 ],
},
{
 "service": "full-detail",
 "city": "jackson-wi",
 "title": "Full Interior & Exterior Detailing in Jackson, WI | Sudz Up Detailing",
 "meta": "Full interior and exterior detailing for Jackson, WI. Work vehicles, shift-pattern wear and I-41 winter miles. $200 cars, $250 SUVs and trucks. Call 414-286-1609.",
 "h1": "Full Detailing for Jackson, Wisconsin",
 "lede": "Jackson runs on shift work and light industry, and vehicles that live around a shift pattern wear differently from vehicles that live around an office day.",
 "glance": [("From our shop", "About 20 minutes"), ("Cars", "$200"), ("SUVs & trucks", "$250"), ("Common type", "Work vehicles")],
 "body": [
   ("Shift-pattern vehicles get the worst of both",
    ["The village has a substantial industrial and distribution presence, and a lot of Jackson vehicles belong to people working shifts rather than a nine to five.",
     "That matters more than it sounds. A shift vehicle sits outside a facility for eight to twelve hours at a stretch, often overnight, which means it takes a full cycle of dew and refreeze every single day rather than sitting in a garage. Repeated wetting and drying on paint is what drives contaminant bonding, and it is why shift vehicles frequently carry more embedded fallout than their mileage would suggest.",
     "On the inside, the pattern is coffee, food eaten in the car at odd hours, and a driver's seat that gets used hard twice a day in work clothing. Workwear is abrasive in a way office clothing is not, and it accelerates bolster wear noticeably."]),
   ("Industrial fallout is a real thing, not a sales line",
    ["Vehicles parked near industrial and rail activity pick up airborne metallic particulate, and it lands on horizontal paint surfaces \u2014 bonnet, roof, boot lid \u2014 where it embeds and then corrodes in place.",
     "On light-coloured paint it shows as tiny rust-coloured specks that will not wash off, because they are not on the surface. That is precisely what the iron removal stage of the exterior half is for, and Jackson vehicles routinely produce a dramatic reaction from it.",
     "The full explanation of that process lives on the <a href=\"/services/exterior-detailing/\">exterior detailing page</a>. The short version is that no wash of any quality removes it and it keeps corroding until something dissolves it."]),
   ("Why the full service suits these vehicles",
    ["A Jackson work vehicle usually needs both halves rather than one. The exterior has bonded contamination that only decontamination removes, and the interior has concentrated driver-side wear plus food and drink residue.",
     "Doing one without the other leaves the vehicle looking half-addressed, and on a car that takes daily outdoor exposure the protection applied to clean paint is doing real work rather than just adding gloss.",
     "It is a full-day drop-off, so shift workers usually leave it on a rest day. Call or text 414-286-1609 and we will work around the pattern rather than assuming a weekday."]),
 ],
 "faq": [
   ("What are the little rust-coloured specks on my paint?",
    "Embedded iron particles, usually from brake dust or nearby industrial and rail activity. They land on horizontal panels, embed in the clear coat and corrode in place. Washing does nothing; a chemical iron remover dissolves them."),
   ("Does parking outside overnight really matter?",
    "More than people expect. A vehicle taking a full dew and refreeze cycle every day spends far more time wet than a garaged one, and repeated wetting is what drives contaminants to bond to paint."),
   ("Can you work around shift patterns?",
    "Yes. A full detail is a full-day drop-off, so tell us what your rota looks like and we will schedule around it rather than assuming you are free on a weekday."),
 ],
},
{
 "service": "exterior-detailing",
 "city": "richfield-wi",
 "title": "Exterior Detailing & Decontamination in Richfield, WI | Sudz Up Detailing",
 "meta": "Exterior detailing for Richfield, WI. Rural road film, gravel chipping and farm-season fallout removed properly. About 15 minutes from our Hartford shop. Call 414-286-1609.",
 "h1": "Exterior Detailing in Richfield, Wisconsin",
 "lede": "Richfield is large, rural and hilly, and its roads do things to paint that suburban streets simply do not.",
 "glance": [("From our shop", "About 15 minutes"), ("Price", "Quoted"), ("Key stage", "Iron + clay decon"), ("Local factor", "Rural road film")],
 "body": [
   ("County roads leave a different film",
    ["Richfield covers a lot of ground and most of its driving happens on county trunks and rural two-lanes rather than maintained urban streets.",
     "Rural roads are treated less often in winter and later after a storm, which means more time spent driving on partially cleared surfaces throwing slush rather than on wet-and-clear pavement. That slush carries more suspended solids than road spray does, and it packs into wheel arches and behind mud flaps where it stays for weeks.",
     "In summer the same roads carry oil and tar that softens in heat and gets thrown onto lower panels and rocker sills. Tar is not removed by washing at any temperature or pressure \u2014 it needs a solvent stage, which is part of decontamination rather than part of a wash."]),
   ("Gravel and the chipping problem",
    ["Broken shoulders and gravel drives throw stone, and Richfield vehicles carry more chipping on leading edges \u2014 bonnet, mirrors, front bumper, the leading edge of the roof \u2014 than vehicles from anywhere else we serve.",
     "Decontamination will not fix a chip and we will not pretend otherwise. What it does do is stop the damage progressing, because a chip through the clear coat exposes the layers beneath, and contamination sitting in and around it accelerates what happens next.",
     "Cleaned and protected paint around a chip is meaningfully more stable than contaminated paint around one. If chipping is widespread on a vehicle you intend to keep, that is a conversation about <a href=\"/services/ceramic-coating/\">protection</a> or film rather than about cleaning."]),
   ("Farm season fallout",
    ["The town is surrounded by working farmland, and spring and autumn both bring field activity that reaches vehicles on the surrounding roads.",
     "Spring is dust and, in places, drift from field application. Autumn is harvest dust and chaff. Both settle on paint and both are more chemically active than ordinary road dirt \u2014 agricultural residue can be mildly alkaline and it does not simply rinse off once it has dried on warm paint.",
     "That is another job for the decontamination stage rather than the wash stage, and it is the main reason we push exterior work in Richfield for late spring and late autumn rather than mid-season."]),
 ],
 "faq": [
   ("Why does tar not come off when I wash the car?",
    "Because it is not water-soluble. No pressure or temperature removes it \u2014 it needs a solvent stage, which is part of decontamination rather than washing."),
   ("Will this fix my stone chips?",
    "No. Decontamination does not repair chips. What it does is stabilise the paint around them, since contamination sitting in and around exposed layers accelerates what happens next."),
   ("When should a rural vehicle be done?",
    "Late spring after the roads finish being treated, and late autumn after harvest activity ends. Mid-season work gets undone by the season it is sitting in the middle of."),
 ],
},
{
 "service": "odor-removal",
 "city": "allenton-wi",
 "title": "Car Odor Removal in Allenton, WI | Sudz Up Detailing",
 "meta": "Car odor removal for Allenton, WI. Farm, livestock, fuel and damp odors traced to the source rather than masked. About 15 minutes. Call or text 414-286-1609.",
 "h1": "Odor Removal in Allenton, Wisconsin",
 "lede": "Allenton is a small farming community, and agricultural odor work is a genuinely different discipline from cleaning up after a spilled coffee.",
 "glance": [("From our shop", "About 15 minutes"), ("Price", "Quoted"), ("Common source", "Farm, fuel, damp"), ("First step", "Find the source")],
 "body": [
   ("Agricultural odor gets into places domestic odor does not",
    ["A farm vehicle is a working tool, and what it carries goes well beyond what a car normally sees. Feed, silage, livestock bedding, and organic material on boots and clothing at every trip.",
     "The important difference is volume and depth. A domestic spill is a defined event in a defined place. Agricultural material arrives continuously in small quantities over years, so it is distributed rather than localised \u2014 in the carpet backing across the whole floor, in the seat foam, in the felt behind door cards, and under the load floor.",
     "That changes the approach. On a domestic job most of the work is finding the one source. Here the source is everywhere in small amounts, so it becomes a systematic extraction job across the whole cabin rather than a targeted one."]),
   ("Fuel and chemical smells are their own problem",
    ["Diesel is the one we get asked about most, and it is genuinely difficult. It soaks into carpet backing and foam, it does not evaporate readily, and it continues to release for a very long time.",
     "Honest expectation setting matters here more than anywhere. A small diesel spill caught quickly usually comes out. A container that emptied into a boot and sat for a season often does not come out completely, and in some cases the correct answer is replacing the affected carpet section rather than cleaning it.",
     "We will tell you which of those you are looking at after we have seen it. What we will not do is take money for a treatment we already expect to fall short."]),
   ("The damp-and-organic combination",
    ["The most common Allenton case is not dramatic at all. It is a work vehicle where organic material has been ground into carpet over years and the carpet never fully dries, because doors get opened in rain and boots come in wet.",
     "Permanently damp carpet with organic material in it is an active biological process, not a stain. It will keep producing smell for as long as both conditions hold, which is why cleaning the surface changes nothing for more than a few days.",
     "Extraction addresses both at once \u2014 it removes the material and it pulls the moisture out of the backing. That is usually more than one pass on a vehicle that has been like this for years."]),
 ],
 "faq": [
   ("Can you get diesel smell out?",
    "Sometimes. Caught quickly, usually yes. A container that emptied into a boot and sat for a season often does not come out completely, and the honest answer is sometimes replacing the affected carpet rather than cleaning it. We will tell you which after seeing it."),
   ("Why does cleaning the carpet not fix the smell?",
    "Because on a farm vehicle the material is distributed through the carpet backing and foam rather than sitting on top, and the carpet never fully dries. That combination is an ongoing biological process, so surface cleaning buys a few days."),
   ("Is it worth doing on a working farm truck?",
    "Often, and it usually needs more than one extraction pass. We will be straight about what will and will not come back before you commit to anything."),
 ],
},
{
 "service": "paint-correction",
 "city": "west-bend-wi",
 "title": "Paint Correction & Swirl Removal in West Bend, WI | Sudz Up Detailing",
 "meta": "Paint correction for West Bend, WI. Automatic-wash swirl marks removed by machine polishing. Assessed and quoted per vehicle. About 20 minutes. Call 414-286-1609.",
 "h1": "Paint Correction for West Bend, Wisconsin",
 "lede": "West Bend has more automatic car washes per driver than anywhere else in our area, and almost every correction job we get from there traces back to them.",
 "glance": [("From our shop", "About 20 minutes"), ("Price", "Quoted"), ("Usual cause", "Automatic washes"), ("Best months", "June or September")],
 "body": [
   ("The unlimited wash club problem",
    ["Monthly unlimited wash memberships are popular in West Bend, and they create a pattern we see constantly: a car that is washed far more often than average and has visibly worse paint than average.",
     "That is not a coincidence and it is not the wash being unusually bad. It is arithmetic. Every pass through a brush wash drags material across your clear coat, and each pass adds a small amount of marring. Wash weekly for three years and you have run the car through well over a hundred and fifty cycles of that.",
     "Frequency is the variable people never account for. A car washed monthly at the same facility accumulates the same damage four times more slowly. The membership is not the problem in itself \u2014 the problem is that paying monthly rationally encourages you to go weekly."]),
   ("What that damage actually looks like",
    ["Brush-wash marring has a recognisable signature. Rather than the random scratching you get from poor hand washing, it tends toward a directional pattern of fine parallel marks following the brush path, heaviest on flat horizontal panels and on the flanks where brush pressure is greatest.",
     "You will see it as a haze or a halo around point light sources \u2014 direct sun, a streetlight, a torch held close. In a garage or on an overcast Wisconsin day it is close to invisible, which is exactly why people are surprised when it is pointed out.",
     "The good news is that it is usually shallow. Wash marring is generally the most correctable kind of paint damage there is, and a single-stage correction frequently recovers the great majority of it."]),
   ("What it makes sense to do afterwards",
    ["Correction removes the defects permanently, but nothing stops you rebuilding them. Going straight back to a weekly brush wash will reproduce the same pattern within a year or two, and clear coat is finite \u2014 you cannot keep correcting indefinitely.",
     "The practical answer is usually not to give up convenience entirely, but to change the frequency and the type. A touchless wash does not remove bonded contamination, but it also does not drag anything across the paint, which makes it a reasonable maintenance option between proper washes.",
     "This is also the main argument for pairing correction with a <a href=\"/services/ceramic-coating/\">ceramic coating</a>. A coated surface releases dirt with far less contact, which is what actually reduces the need for aggressive washing in the first place."]),
 ],
 "faq": [
   ("I wash my car constantly and the paint still looks bad. Why?",
    "Very likely because of how often, not how little. Each pass through a brush wash adds fine marring, so a weekly wash accumulates damage roughly four times faster than a monthly one at the same facility."),
   ("Is brush-wash damage correctable?",
    "Usually yes, and it is among the more correctable kinds of paint damage because it tends to be shallow. A single-stage correction frequently recovers most of it."),
   ("Do I have to stop using car washes after correction?",
    "Not entirely, but going back to weekly brush washing will rebuild the same pattern within a year or two, and clear coat is finite. Reducing frequency, switching to touchless for maintenance, or coating the paint are the practical options."),
 ],
},
{
 "service": "interior-detailing",
 "city": "sussex-wi",
 "title": "Interior Car Detailing in Sussex, WI | Sudz Up Detailing",
 "meta": "Interior car detailing for Sussex, WI. Construction dust in seat stitching and vents, new-build footwell grit. $135 cars, $150 SUVs. About 25 minutes. Call 414-286-1609.",
 "h1": "Interior Detailing in Sussex, Wisconsin",
 "lede": "The single most common thing in a Sussex cabin is dust from a house that is not yours, and it is a genuinely awkward kind of dust to remove.",
 "glance": [("From our shop", "About 25 minutes"), ("Cars", "$135"), ("SUVs & trucks", "$150"), ("Common issue", "Construction dust")],
 "body": [
   ("Gypsum is not like ordinary dust",
    ["Drywall dust is the one that catches people out. It is finer than road dust, it is pale enough to show on a dark interior within days, and it is slightly hygroscopic \u2014 it takes on moisture from the air and clumps rather than staying loose.",
     "That clumping is why it resists a vacuum. Loose dust moves with airflow. Damp gypsum sits in the bottom of a seat seam or a vent louvre as a soft paste and stays there. It also leaves a faint white haze on dark plastics that people mistake for the material fading.",
     "The sequence that removes it is dry first: compressed air to break it loose and lift it into the open cabin, then vacuum, then surface cleaning last. Wet-cleaning a gypsum-dusted dash first just spreads a thin plaster film across it."]),
   ("The vents are the problem nobody sees",
    ["Construction dust gets into the HVAC system, because the cabin intake pulls it in every time the vehicle sits with the fan running near an active site.",
     "The cabin air filter catches some. What gets past it coats the inside of the ducts and settles on the vent louvres, and every time the fan runs it pushes a small amount back into the cabin. This is why a Sussex vehicle can be cleaned thoroughly and have a fine white dust reappear on the dash within a week.",
     "We clean the louvres and check the filter on every Sussex vehicle. If the filter is loaded, we will tell you \u2014 replacing it is the difference between the clean holding and the clean failing."]),
   ("Footwells in the first year",
    ["New landscaping, bare soil, fresh mulch and unfinished drives mean that for roughly the first year in a new build, everything on the ground around the house ends up in the footwells.",
     "It is coarse rather than fine, so it grinds. Carpet fibre under a driver's heel with grit in it wears through noticeably faster, and new-build footwells are frequently more worn at twelve months than a five-year-old car's. Getting it out is the only thing that slows that down.",
     "If the vehicle is also carrying construction dust on the paint, the <a href=\"/services/full-detail/\">full detail</a> handles both sides rather than booking twice."]),
 ],
 "faq": [
   ("Why does white dust keep coming back on my dash?",
    "It is in the ducts and on the vent louvres, and every fan cycle pushes a little back out. Cleaning the cabin without cleaning the vents and checking the filter means it returns within a week."),
   ("Can you get drywall dust out of seat seams?",
    "Yes, but it has to be blown out with compressed air before anything else. It takes on moisture and clumps, so a vacuum alone leaves it sitting in the seam as a paste."),
   ("How far is Sussex from your shop?",
    "About twenty-five minutes to 2948 WI-83 in Hartford. Interior work is usually a same-day collection."),
 ],
},
{
 "service": "ceramic-coating",
 "city": "sussex-wi",
 "title": "Ceramic Coating for Sussex, WI | Sudz Up Detailing",
 "meta": "Ceramic coating for Sussex, WI. New cars in new-construction neighbourhoods take alkaline dust damage from day one. Protection first, not cleanup later. From $599. Call 414-286-1609.",
 "h1": "Ceramic Coating for Sussex, Wisconsin",
 "lede": "Sussex is the one place we serve where the case for coating a new car is strongest, and it is entirely because of what is in the air.",
 "glance": [("From our shop", "About 25 minutes"), ("From", "$599"), ("Prep", "Assessed per vehicle"), ("Best timing", "At purchase")],
 "body": [
   ("Alkaline dust and a brand new clear coat",
    ["A new car arrives in a construction neighbourhood with a clear coat that has never been touched, and within a season it has a bonnet that looks years older than the rest of the vehicle. The reason is chemistry, not neglect.",
     "Concrete, mortar and gypsum dust are all alkaline. When they land on paint that is damp \u2014 dew, rain, a wash that was not dried \u2014 and then dry in place, they bond to the surface and, over repeated cycles, begin to etch it. Horizontal panels take the worst of it because that is where dust lands and where dew sits longest.",
     "Washing does nothing once it has bonded. It needs decontamination, and by the time the owner notices it is often already into the clear coat rather than on it."]),
   ("What a coating does about that",
    ["A coating does not stop dust landing. What it changes is whether the dust bonds. A coated surface is chemically far less receptive, so alkaline film releases with a rinse instead of needing to be scrubbed or clayed off.",
     "That matters twice over in Sussex. Once because it stops the etching cycle before it starts. And again because scrubbing bonded film off unprotected paint is how new cars pick up wash marring in their first year \u2014 the owner is trying to remove damage and creating a different kind.",
     "It also makes the ongoing maintenance trivial. Rinse the dust off every couple of weeks while the build continues and the paint stays genuinely clean with almost no effort."]),
   ("Why the timing is the whole point",
    ["The argument here is not that coating is better than correction. It is that on a new car in a construction zone, coating early means correction is never needed.",
     "Coated at purchase, the paint needs decontamination only \u2014 there is nothing to correct yet \u2014 so the job is close to the $599 starting figure. Coated after a year of dust exposure, the paint has bonded contamination and often the beginnings of etching, so it needs <a href=\"/services/paint-correction/\">correction</a> first and the job is considerably larger.",
     "Same coating, same car. The only variable is when. If you are moving into a Sussex build with a new or recent vehicle, do it now rather than later."]),
 ],
 "faq": [
   ("Will a coating stop construction dust landing on my car?",
    "No. It stops the dust bonding. Alkaline film on a coated surface rinses off; on bare paint it bonds when it dries and begins to etch over repeated cycles."),
   ("Why coat a car that is already clean and new?",
    "Because that is when the job is smallest. Coated at purchase, the paint needs decontamination only. Coated after a year of construction exposure, it usually needs correction first and the job is considerably larger."),
   ("How far is Sussex from your shop?",
    "About twenty-five minutes to 2948 WI-83 in Hartford. Coating is multi-day when prep is involved and we will give you the real timeline."),
 ],
},
{
 "service": "full-detail",
 "city": "menomonee-falls-wi",
 "title": "Full Detailing & Lease Return Prep in Menomonee Falls, WI | Sudz Up Detailing",
 "meta": "Full interior and exterior detailing for Menomonee Falls, WI. Lease and allowance vehicle return prep to inspection standard. $200 cars, $250 SUVs. Call 414-286-1609.",
 "h1": "Full Detailing for Menomonee Falls, Wisconsin",
 "lede": "The Falls sends us more vehicles that are about to be handed back than anywhere else, and handback is a different job from a detail done for yourself.",
 "glance": [("From our shop", "About 25 minutes"), ("Cars", "$200"), ("SUVs & trucks", "$250"), ("Common job", "Lease return prep")],
 "body": [
   ("An inspection is not a buyer",
    ["A private buyer looks at a car and forms an impression. A lease-return or fleet-return inspector works from a checklist with charge thresholds, and they are looking specifically for the things the checklist prices.",
     "That changes the target. Wear-and-tear charges typically key on things like interior stains beyond a certain size, odors, upholstery damage, scuffed door sills, and paint defects that exceed a stated threshold. A vehicle can look perfectly presentable and still fail on four line items, each of which is billed.",
     "So a return prep is not about making the car look nice. It is about taking specific line items off the inspection sheet, and knowing which ones are addressable is most of the value."]),
   ("What is addressable and what is not",
    ["Odor is addressable and it is the highest-value item, because it is frequently billed as a flat charge regardless of cause. Stains on cloth and light leather are usually addressable if they are surface rather than dye transfer. Door sill scuffing and dash haze come up well. Wash marring on paint is addressable with light correction and it is worth doing on a return, since paint condition is frequently a charged item.",
     "Deep scratches through the clear coat, torn upholstery, cracked dash plastics and curb-rashed wheels are not detailing problems and we will not pretend they are. We will tell you which items on your vehicle fall into each category before you spend anything, because on a return the honest number is the whole point."]),
   ("The company-car version",
    ["Allowance and fleet vehicles come back on a similar checklist and with an additional wrinkle: the person handing it back is frequently not the person who drove it hardest.",
     "A sales vehicle that has carried samples, food, and three years of highway miles arrives with concentrated driver's-side interior wear and paint that has never been decontaminated. The full detail addresses both halves in one day, and on a company vehicle it is usually the cheapest thing that can be done to it relative to what the return charges would be.",
     "Book a few weeks ahead of the return date rather than the day before. If something needs a second pass, you want the time to do it."]),
 ],
 "faq": [
   ("Can you get a car through a lease return inspection?",
    "For the items that are detailing problems \u2014 odor, surface stains, sill scuffing, dash haze, wash marring \u2014 usually yes. Deep scratches, tears and cracked plastics are not, and we will tell you which category each item on your car falls into before you spend anything."),
   ("How far ahead of the return should I book?",
    "A few weeks, not the day before. If something needs a second pass, you want the time for it."),
   ("How far is Menomonee Falls from your shop?",
    "About twenty-five minutes to 2948 WI-83 in Hartford. A full detail is a full-day drop-off."),
 ],
},
{
 "service": "odor-removal",
 "city": "hartland-wi",
 "title": "Car Odor Removal in Hartland, WI \u2014 Wet Dog, Trail Mud & Gear | Sudz Up Detailing",
 "meta": "Car odor removal for Hartland, WI. Wet dog, river water, trail mud and damp gear odors traced to the source rather than masked. About 25 minutes. Call 414-286-1609.",
 "h1": "Odor Removal in Hartland, Wisconsin",
 "lede": "Hartland is an outdoor town, and almost every odor job we get from there comes down to something that got wet and stayed wet.",
 "glance": [("From our shop", "About 25 minutes"), ("Price", "Quoted"), ("Common source", "Wet dog, wet gear"), ("First step", "Find the source")],
 "body": [
   ("Wet dog is not a dog problem",
    ["Dogs that have been in the Bark River or on a muddy trail get into the car wet, and the smell that follows is not really the dog. It is bacteria breeding in the moisture the dog left behind in the seat foam and the boot carpet.",
     "That is why the smell has a weather pattern. It fades when the car dries out and comes roaring back on the first humid morning, and it is why owners so often say it was fine for a week and then returned. Nothing came back. The bacteria were always there; the humidity reactivated them.",
     "Treating the air does nothing for this. Removing the moisture and the organic material from the foam and the backing does, and on a vehicle that has done a summer of river trips it usually takes more than one extraction pass."]),
   ("Gear that went in the boot damp",
    ["The second Hartland source is equipment. Wet trail shoes, damp packs, a kayak spray skirt, a wetsuit, cycling kit after a rainy ride. It goes in the boot damp, the boot is closed, and it sits.",
     "A closed boot with wet gear in it is a humidity chamber, and the boot carpet takes on moisture from the gear even when nothing is actually leaking. Do that a few times a month through a season and the carpet backing never dries fully between trips.",
     "We check the spare wheel well on every one of these. It is below the load floor, water that gets in there has nowhere to drain, and on outdoor vehicles it is the actual source far more often than the carpet above it."]),
   ("What we look for before quoting",
    ["We assess before quoting on all odor work, and on an outdoor vehicle the assessment is specifically about how far the moisture has travelled.",
     "Surface-level, recent, one source: a short job. Season-long, into the foam, plus a damp spare well: a longer one. Occasionally the honest answer is that foam that has absorbed a lot of organic liquid over a long period will not fully recover, and we will say so rather than sell a treatment we expect to fall short.",
     "If the vehicle also has trail mud through the rear cabin \u2014 which it usually does \u2014 the <a href=\"/services/interior-detailing/\">interior detail</a> may be the better booking with odor work folded in."]),
 ],
 "faq": [
   ("Why does the dog smell come and go?",
    "Because the source is bacteria in trapped moisture, not the dog. Dry weather suppresses it, humidity reactivates it. Removing the moisture and the material is what stops it for good."),
   ("Nothing is wet in the car but it smells damp. Why?",
    "Gear that went in damp and was closed in the boot. The carpet takes on moisture from it even without a leak, and the spare wheel well below the load floor is where it collects. We check that first."),
   ("How far is Hartland from your shop?",
    "About twenty-five minutes to 2948 WI-83 in Hartford. Call or text 414-286-1609 and we will arrange a look before quoting."),
 ],
},
{
 "service": "interior-detailing",
 "city": "kewaskum-wi",
 "title": "Interior Car Detailing in Kewaskum, WI | Sudz Up Detailing",
 "meta": "Interior car detailing for Kewaskum, WI. Kettle Moraine camping gear, Long Lake sand and northern-unit trail grit. $135 cars, $150 SUVs. About 25 minutes. Call 414-286-1609.",
 "h1": "Interior Detailing in Kewaskum, Wisconsin",
 "lede": "Kewaskum is the gateway to the northern Kettle Moraine, and the vehicles that use it that way come back carrying the forest.",
 "glance": [("From our shop", "About 25 minutes"), ("Cars", "$135"), ("SUVs & trucks", "$150"), ("Peak season", "Camping season")],
 "body": [
   ("Camping season and what a weekend leaves behind",
    ["The Northern Unit of the Kettle Moraine State Forest starts just past the village, and from spring through autumn a lot of Kewaskum vehicles are doing weekends at Long Lake and Mauthe Lake with a load of gear.",
     "A camping weekend leaves a distinctive residue. Campfire smoke in the headliner and the seat fabric, which is the thing people notice first and struggle to remove because it is in the ceiling rather than on the floor. Pine needles and bark in every rear-cabin gap. Cooler meltwater in the boot. And sand, because both lakes have beaches, tracked in on wet feet and dried into a crust in the carpet.",
     "Each of those needs a different approach and none of them is a vacuum job. Smoke residue is surface cleaning on the headliner. Needles need compressed air to get them out of seat rails and gaps. Sand needs mechanical breaking and extraction."]),
   ("The headliner is the part that gets skipped",
    ["Headliners are the most under-cleaned surface in any vehicle, and on a camping vehicle they are frequently the most contaminated.",
     "Smoke rises, and campfire smoke that came in on clothing and gear settles upward into the headliner fabric where it sits. It is also where the smell lives. Cleaning the seats and the carpet of a smoky vehicle without touching the headliner leaves the largest reservoir of the smell exactly where it was.",
     "Headliners have to be cleaned carefully \u2014 too much moisture and the adhesive under the fabric lets go \u2014 but they can be cleaned, and on a Kewaskum vehicle after a season of weekends it makes the largest difference of any single surface."]),
   ("Off-season",
    ["Winter empties the campgrounds, and a Kewaskum vehicle's problems switch to the rural-road profile: county trunks that are treated later and less, slush packed into arches, and salt in the carpet backing from the walk across a gravel drive.",
     "That makes late autumn the natural booking time \u2014 after the last camping weekend and before the first salt. If a vehicle does both seasons hard, doing it once properly at that point beats two half-jobs."]),
 ],
 "faq": [
   ("Can you get campfire smell out of a car?",
    "Usually, and the headliner is the key. Smoke settles upward into the ceiling fabric, and cleaning everything else while leaving the headliner leaves the largest reservoir in place. It has to be cleaned carefully, but it can be."),
   ("How do you get pine needles out of seat rails?",
    "Compressed air first, to blow them out of the gaps a vacuum cannot generate airflow inside, then vacuum. It is the same sequence we use on every interior but on a camping vehicle it is doing most of the work."),
   ("When should a camping vehicle be detailed?",
    "Late autumn, after the last trip and before the first road salt. One proper reset at that point beats a spring and an autumn half-job."),
 ],
},
{
 "service": "exterior-detailing",
 "city": "lannon-wi",
 "title": "Exterior Detailing & Decontamination in Lannon, WI | Sudz Up Detailing",
 "meta": "Exterior detailing for Lannon, WI. Limestone quarry dust bonded to paint removed by chemical and clay decontamination, not washing. About 25 minutes. Call 414-286-1609.",
 "h1": "Exterior Detailing in Lannon, Wisconsin",
 "lede": "Lannon vehicles are our clearest demonstration of the difference between washing and decontamination, because the thing on the paint is alkaline stone.",
 "glance": [("From our shop", "About 25 minutes"), ("Price", "Quoted"), ("Key stage", "Clay decon"), ("Local factor", "Quarry dust")],
 "body": [
   ("Why quarry dust does not rinse",
    ["The quarries around Lannon produce dolomitic limestone, and the fine dust they release is calcium-magnesium carbonate \u2014 alkaline, extremely fine, and mineral rather than organic.",
     "Mineral dust behaves differently from road grime on paint. When it lands dry it sits loose and a rinse moves it. But when it lands on dew or is rained on and then dries, the minerals recrystallise on the surface and bond to the clear coat. At that point water does not touch it, and neither does soap, because there is nothing water-soluble left to dissolve.",
     "This is the chalky cast Lannon owners describe on the bonnet and roof that survives every wash. It is not dirt. It is a thin mineral layer bonded to the paint, and the only thing that removes it is mechanical decontamination."]),
   ("The clay stage does the work here",
    ["On most vehicles the chemical iron remover is the dramatic stage and clay is the finishing touch. On a Lannon vehicle that reverses.",
     "Bonded mineral film is exactly what clay is for. Lubricated and drawn across the panel, it shears the recrystallised layer off level with the clear coat, and on a car that has never had it done the amount that comes off is startling \u2014 the clay goes grey within a panel or two and has to be folded repeatedly. It is slow, it is by hand, and it is the reason a decontaminated Lannon vehicle feels like glass afterwards.",
     "Iron removal still matters \u2014 haul truck brake dust is real \u2014 but it is the secondary stage here rather than the primary one."]),
   ("Protection is not optional afterwards",
    ["Decontaminating a Lannon vehicle and leaving the paint bare is a job that lasts until the next dew cycle in a dust cloud.",
     "Protection is what makes the work hold. Sealant or, better, a <a href=\"/services/ceramic-coating/\">ceramic coating</a> gives the paint a surface that mineral dust does not readily bond to, so the next rinse actually removes it instead of the film rebuilding within weeks.",
     "On a vehicle that lives in the village, we would not do the decontamination without the protection. It is the difference between a result and an afternoon."]),
 ],
 "faq": [
   ("Why does the chalky film on my paint survive every wash?",
    "Because it is bonded mineral, not dirt. Limestone dust that dries on damp paint recrystallises onto the clear coat, and nothing water-soluble remains for a wash to dissolve. Clay decontamination shears it off."),
   ("Is the clay stage really necessary?",
    "On a Lannon vehicle it is the main event. Chemical iron removal handles brake dust; only mechanical clay removes bonded mineral film."),
   ("Will it just come back?",
    "If the paint is left bare, yes, within weeks. Sealant or a coating gives the surface something mineral dust does not readily bond to, so the next rinse actually removes it."),
 ],
},

]
