# -*- coding: utf-8 -*-
"""
Service page content. Written to reflect only what Sudz Up Detailing actually
offers — no ceramic coating, paint correction, PPF or window tint, because
generating demand for services the business cannot fulfil is worse than useless.
"""

SERVICES = [
{
 "slug": "interior-car-detailing",
 "name": "Interior Car Detailing",
 "nav": "Interior Detailing",
 "price": "From $135",
 "title": "Interior Car Detailing in Hartford, WI | Sudz Up Detailing",
 "meta": "Interior car detailing in Hartford, WI. Vacuum, VRP treatment, spot stain removal, door jambs and glass. $135 cars, $150 SUVs and trucks. Call 414-286-1609.",
 "h1": "Interior Car Detailing",
 "lede": "The Sudz Quick Clean is our interior service. It is the package most people actually need, and it is where a detail makes the biggest difference to how a vehicle feels day to day.",
 "card": "Full interior reset — vacuum, VRP treatment, spot stains, jambs and glass.",
 "glance": [("Cars", "$135"), ("SUVs & trucks", "$150"), ("Typical time", "1–2 hours"), ("Package", "Sudz Quick Clean")],
 "body": [
   ("What is actually included",
    ["The Sudz Quick Clean covers a complete interior vacuum, vinyl, rubber and plastic treatment across the hard surfaces, spot stain removal, door jambs cleaned, and windows cleaned inside and out.",
     "That list is short because we would rather do five things properly than list fifteen and rush them. The order matters as much as the contents. We work top down and dry to wet, because cleaning a dashboard after you have shampooed the carpet just puts dust back onto a damp surface."]),
   ("The vacuum is not the quick part",
    ["Most of the time on an interior detail goes into the vacuum, and most of that goes into places a normal vacuum never reaches.",
     "Seats get moved fully forward and fully back so we can get at the rails and the carpet underneath, which is where the majority of debris in any vehicle collects. Floor mats come out and get done separately, and the carpet under them gets cleaned — that surface is frequently dirtier than the mat that was covering it. We use compressed air to blow debris out of seat seams, seat belt buckle recesses, centre console gaps and air vents before vacuuming, because a vacuum nozzle cannot generate airflow inside a 3mm gap.",
     "Cargo areas get the load floor lifted and the spare wheel well cleared. On SUVs and estates, that space collects an extraordinary amount of grit and it is almost never touched."]),
   ("Vinyl, rubber and plastic treatment",
    ["VRP treatment is the step people misunderstand most. It is not a shine product. Its job is to clean the hard surfaces properly and then put a protective layer back onto plastics that lose plasticiser to UV over time.",
     "Untreated dashboards in Wisconsin have a hard life. Sun through the windscreen for years dries the surface out, and once it goes chalky and starts to crack, no product reverses it. Regular treatment slows that considerably.",
     "We apply it to a matte finish rather than a wet gloss. A glossy dash reflects into the windscreen and is genuinely distracting when the sun is low, which in a Wisconsin winter afternoon is most of the drive home."]),
   ("Spot stain removal, and what that means honestly",
    ["Spot stain removal in the Quick Clean means targeted treatment of individual marks — a coffee ring, a scuff on a door card, a patch on a seat base. It is not a full shampoo and extraction of every surface.",
     "Whether a stain lifts depends on what it is and how long it has been there. Water-based spills caught within days usually come out completely. Coffee and soda respond well. Grease and oil need a solvent approach and often come out fully. Ink, dye transfer from clothing, and heavy chlorophyll staining from grass are the hardest, and sometimes the honest answer is a substantial improvement rather than complete removal.",
     "If a vehicle has widespread staining rather than a few spots, we will tell you before we start that it needs more than the Quick Clean covers, and quote it properly."]),
   ("Door jambs and glass — the tells",
    ["Door jambs are the single clearest indicator of whether a detail was done properly. They are what you look at every time you open the door, and they are what a car wash never touches. Cleaning them takes minutes and it changes the whole impression of the vehicle.",
     "Interior glass is the other tell. Windscreens develop a film from plastic off-gassing combined with road dust, and it is the reason oncoming headlights scatter and dazzle at night. We do interior glass in two stages, because a single pass with a household spray usually smears the film into something worse than it started."]),
 ],
 "faq": [
   ("How long does an interior detail take?", "Typically one to two hours for the Sudz Quick Clean, depending on vehicle size and condition. We would rather take the time and do it properly than rush to a fixed clock."),
   ("Is interior detailing worth it if my car looks fine?", "Usually more than people expect. Most of what a vacuum misses is under the seats, in the rails and in the seams. The difference tends to be in how the vehicle smells and feels rather than how it photographs."),
   ("Does the Quick Clean include shampooing all the carpets?", "No. It includes targeted spot stain removal. If a vehicle needs full extraction across all surfaces, we will tell you that before starting and quote it properly rather than under-deliver."),
   ("Do you clean inside the air vents?", "We clear what is reachable with compressed air and detail brushes. If dust has built up deeper in the blower housing, we will tell you honestly rather than pretend a surface clean has resolved it."),
 ],
 "related": ["full-interior-exterior-detail", "stain-and-odor-removal", "truck-and-suv-detailing"],
},
{
 "slug": "exterior-wash-and-polish",
 "name": "Exterior Wash & Polish",
 "nav": "Exterior Wash & Polish",
 # Page stays live, indexed and reachable via related links, but is kept out
 # of the services hub grid and the nav dropdown.
 "hidden": True,
 "price": "Part of VIP",
 "title": "Exterior Car Wash & Polish in Hartford, WI | Sudz Up Detailing",
 "meta": "Exterior hand wash, polish, wheel cleaning and tire shine in Hartford, WI. Included in the Sudz Up VIP Clean from $200. Call or text 414-286-1609.",
 "h1": "Exterior Wash & Polish",
 "lede": "Our exterior work — hand wash, polish, wheels cleaned and tires shined — comes as part of the Sudz Up VIP Clean. Here is what that actually involves and why it is not the same as a drive-through.",
 "card": "Hand wash, polish, wheels cleaned and tires shined. Part of the VIP Clean.",
 "glance": [("Included in", "Sudz Up VIP Clean"), ("Cars", "$200 (full VIP)"), ("SUVs & trucks", "$250 (full VIP)"), ("Method", "Hand wash")],
 "body": [
   ("Why a drive-through wash is not the same thing",
    ["An automatic wash puts the same spinning material across every vehicle that came before yours, carrying whatever grit came off them. That is the mechanism behind the fine circular swirl marks you see on a dark car in direct sunlight.",
     "A proper hand wash controls that. Dirt gets rinsed off before anything touches the paint, wash media is kept clean between panels, and the dirtiest areas — lower panels, behind the wheels — are done last so their grit does not get carried up onto cleaner paint.",
     "This matters more on dark colours and on older single-stage paint, where swirls show immediately. It matters less on light silver, where they are nearly invisible. We are not going to pretend it is life-changing on a white work truck, but on a black car it is the difference between clean and properly clean."]),
   ("Wisconsin-specific: brine, not just salt",
    ["Wisconsin road treatment includes liquid brine applied ahead of storms. It is worth understanding because it changes when you should wash.",
     "Brine goes down on dry roads before the weather arrives. It dries into a white film that is easy to miss on a light-coloured vehicle. Because it is hygroscopic, it pulls moisture from the air and stays chemically active long after the road is dry — which means a car parked in a heated garage after a brine run is actively corroding while it sits.",
     "The practical consequence is that winter washing is not cosmetic maintenance, it is corrosion control. The areas that matter most are the ones nobody looks at: inside the wheel arches, along the rocker panels, in the door jambs and around the tailgate seams. Our exterior work covers jambs and arches specifically because that is where brine sits."]),
   ("What polish does and does not do",
    ["Polish in our VIP service is a finishing step. It cleans up light surface contamination and leaves a uniform, protected finish with real gloss.",
     "It is important to be clear about the ceiling here. This is not multi-stage machine paint correction, and it will not remove deep scratches, sanding marks or failed clear coat. If you can catch a fingernail in a scratch, polish will not remove it. What it does do is dramatically improve a finish that has gone dull from accumulated road film, light oxidation and organic deposit — and that describes most vehicles over three years old in this climate.",
     "The improvement is often most dramatic on vehicles that live outside under trees. Years of pollen, sap film and dust build a layer that owners mistake for the paint having faded. Frequently it has not."]),
   ("Wheels and tires",
    ["Wheels take more chemical and thermal abuse than any other part of a vehicle. Brake dust is hot metallic particulate that physically embeds into wheel finish, and if it is left across a whole winter it starts to pit the coating.",
     "We clean wheel faces, barrels where accessible, and the tires themselves before dressing them. Tire dressing goes on properly rather than being sprayed on and left to sling black streaks down your paint on the first drive — which is what happens with the aerosol approach, and it is why we apply and wipe rather than apply and walk away."]),
 ],
 "faq": [
   ("Can I book just the exterior wash and polish?", "Our exterior work is packaged inside the Sudz Up VIP Clean, which is the full interior and exterior service at $200 for cars and $250 for SUVs and trucks. Call or text 414-286-1609 to talk about what you need."),
   ("Will polishing remove scratches?", "Light surface dulling and contamination, yes. Deep scratches you can catch a fingernail in, no. This is a finishing polish rather than multi-stage paint correction, and we would rather set that expectation honestly."),
   ("Should I wash my car in winter in Wisconsin?", "Yes, more than in summer. Liquid brine stays chemically active long after the road is dry, so a salted vehicle sitting in a garage is actively corroding. Wheel arches, rockers and door jambs matter more than the panels you can see."),
   ("Do you wash by hand?", "Yes. Automatic washes carry grit from previous vehicles across your paint, which is what causes swirl marks. Hand washing with clean media and a proper rinse sequence avoids that."),
 ],
 "related": ["full-interior-exterior-detail", "interior-car-detailing", "truck-and-suv-detailing"],
},
{
 "slug": "full-interior-exterior-detail",
 "name": "Full Interior & Exterior Detail",
 "nav": "Full Detail (VIP)",
 "price": "From $200",
 "title": "Full Car Detail in Hartford, WI | Sudz Up VIP Clean",
 "meta": "Full interior and exterior car detail in Hartford, WI. Complete interior plus wash, polish, wheels and tires. $200 cars, $250 SUVs and trucks. Call 414-286-1609.",
 "h1": "Full Interior & Exterior Detail",
 "lede": "The Sudz Up VIP Clean is everything in the interior service plus the full exterior treatment. It is the package to book when you want the whole vehicle reset in one visit.",
 "card": "Everything in the interior service plus wash, polish, wheels and tires.",
 "glance": [("Cars", "$200"), ("SUVs & trucks", "$250"), ("Covers", "Interior + exterior"), ("Package", "Sudz Up VIP Clean")],
 "body": [
   ("Everything, in the right order",
    ["The VIP Clean includes the complete interior vacuum, vinyl, rubber and plastic treatment, spot stain removal, door jambs and glass — then adds the exterior hand wash and polish, wheels cleaned and tires shined.",
     "Doing both together is not just a bundle for convenience. It is genuinely better work, because sequence matters. Wheels and lower panels are the dirtiest part of any vehicle, and doing them in the same session as the interior means we are not opening clean doors with dirty hands or letting arch grit find its way back into a freshly cleaned sill.",
     "Door jambs are the clearest example. A jamb sits between the interior and exterior worlds. Cleaning the cabin but not the jamb leaves an obvious dirty frame around otherwise clean work, and it is the first thing anyone notices when they open the door."]),
   ("Who should book this rather than the Quick Clean",
    ["There are four situations where the VIP is clearly the right call, and we would rather tell you which one you are in than upsell by default.",
     "You are selling the vehicle. Full stop — book the VIP, and do it before you take photographs.",
     "You are coming out of a Wisconsin winter. Salt has been in the jambs, arches and carpets for months, and doing only the interior leaves the corrosive half of the problem untouched.",
     "You have not detailed the vehicle in over a year. At that point there is exterior contamination that a wash alone will not shift, and the polish step is doing real work.",
     "You are driving a distance to reach us. If you are coming from Kewaskum or Germantown, splitting the work over two visits is a poor use of your time.",
     "If none of those apply and the vehicle is in decent shape outside, the Quick Clean is probably enough and we will say so."]),
   ("What a full detail cannot do",
    ["We would rather be clear about the ceiling than have you disappointed at collection.",
     "A detail does not repair. Cracked dash tops, torn seat fabric, sagging headliners, worn-through bolsters, stone chips and clear coat that has already failed are all beyond it. Deep scratches remain deep scratches. A cigarette smoke odour that has permeated a headliner over years can be substantially reduced but rarely eliminated entirely.",
     "What a full detail does is bring everything that is still structurally sound back to as good as it can look. On most vehicles between three and twelve years old, that gap is much bigger than the owner expects — which is why the reaction at collection is usually surprise rather than mild satisfaction."]),
   ("Timing and preparation",
    ["The VIP takes meaningfully longer than the Quick Clean. Vehicle size and condition drive it, so we will give you a realistic window when you book rather than a number that sounds good on the phone.",
     "Two things help enormously. First, take personal belongings out beforehand — we work faster and you are not relying on us to decide what is rubbish and what matters. Second, tell us about any specific problem: a spill you know about, a smell, a stain you have already tried to treat yourself. Products previously applied to a stain change how we approach it, and knowing saves us both time."]),
 ],
 "faq": [
   ("What is the difference between the Quick Clean and the VIP Clean?", "The Quick Clean is interior only — vacuum, VRP treatment, spot stains, jambs and glass. The VIP adds the full exterior: hand wash, polish, wheels cleaned and tires shined."),
   ("How much is a full detail?", "The Sudz Up VIP Clean is $200 for cars and $250 for SUVs and trucks. Final pricing depends on vehicle condition, and we quote before starting rather than adjusting at collection."),
   ("How long does a full detail take?", "Longer than the one to two hours of the Quick Clean, with size and condition being the main factors. We give a realistic window when you book."),
   ("Should I empty my car before a detail?", "Yes, please. Removing personal belongings lets us work faster and means we are not making judgement calls about what matters to you."),
 ],
 "related": ["interior-car-detailing", "exterior-wash-and-polish", "stain-and-odor-removal"],
},
{
 "slug": "stain-and-odor-removal",
 "name": "Stain & Odor Removal",
 "nav": "Stain & Odor Removal",
 "price": "Quoted",
 "title": "Car Stain & Odor Removal in Hartford, WI | Sudz Up Detailing",
 "meta": "Car interior stain and odor removal in Hartford, WI. Spills, pet odor, smoke and mildew assessed honestly before we start. Call or text 414-286-1609.",
 "h1": "Stain & Odor Removal",
 "lede": "Most odour problems are a moisture problem, not an air problem. Understanding that is the difference between fixing a smell and covering it up for two weeks.",
 "card": "Spills, pet odour, mildew and smoke — assessed honestly before we start.",
 "glance": [("Assessment", "Before we start"), ("Method", "Source removal + extraction"), ("Included in", "Spot work on both packages"), ("Heavy cases", "Quoted separately")],
 "body": [
   ("Why air fresheners never work",
    ["An air freshener adds a smell on top of a smell. Within a week or two the added fragrance fades and the original problem is exactly where it was, because the source has not moved.",
     "Almost every persistent vehicle odour comes from organic material that got into a porous surface — carpet, carpet backing, or seat foam — and has been decomposing since. Milk, food, sweat, pet accidents, spilled drinks, wet fabric. Bacteria break it down and the byproducts are what you smell.",
     "There is no product that neutralises this from the air, because the material generating it is still sitting in the foam. The only approach that genuinely works is finding the source, physically removing it through hot water extraction, and drying the area thoroughly so you do not create a damp environment that restarts the process."]),
   ("How we find the source",
    ["Locating the source is often the hardest part and it is the part people skip. Liquid does not stay where it was spilled. It runs to the lowest point of the carpet pan, which is usually under a seat, along a seat rail, or beneath the sound deadening.",
     "A spill on a rear seat frequently ends up in the footwell in front of it. A drink knocked over in a cup holder can run through the console and appear under the carpet on the transmission tunnel. This is why cleaning the visible mark achieves nothing — the visible mark is rarely where the material actually is.",
     "We check under mats, along the rails, in the seat base foam and under the load floor. If a smell is coming from the ventilation system rather than the carpet, that is a different problem again and we will tell you, because no amount of interior cleaning fixes a contaminated evaporator or a saturated cabin filter."]),
   ("What comes out, what improves, and what stays",
    ["We would rather set expectations correctly at the quote than at the collection.",
     "Generally removable: fresh water-based spills, coffee, soda, most food staining, mud, and general soil accumulation. These usually come out completely with extraction.",
     "Usually substantially improved: pet odour and dander, older organic spills, mildew from damp gear, sweat saturation in seat bases. Expect a big improvement rather than a guarantee of perfection, especially where material has reached the sound deadening under the carpet.",
     "Difficult to eliminate entirely: long-term cigarette smoke that has permeated the headliner and every soft surface over years, ink and dye transfer, heavy chlorophyll grass staining on light carpet, and anything involving fuel or oil that soaked into foam.",
     "If we do not think we can meaningfully improve a particular problem, we will tell you that rather than take your money and hope."]),
   ("Drying is half the job",
    ["Extraction that is not followed by proper drying can leave a vehicle worse off than before. Introducing moisture into carpet and foam and then closing the doors on it is how you create mildew.",
     "This is the most common failure we see in vehicles that have been shampooed elsewhere or by the owner with a rental machine. The surface looks better for a few days, then a musty smell appears that was not there before. That is not bad luck, it is trapped moisture.",
     "It is also why we would rather not rush a heavily contaminated interior in a short window. If a vehicle needs proper drying time, we will tell you when you book rather than hand it back damp."]),
 ],
 "faq": [
   ("Can you get pet smell out of a car?", "Usually a substantial improvement. Pet odour lives in seat foam and carpet backing rather than in the air, so it needs source removal and hot water extraction. Complete elimination depends on how deep and how long it has been there."),
   ("Will you get cigarette smoke out?", "Long-term smoke that has permeated the headliner and every soft surface over years can be significantly reduced but rarely eliminated entirely. We will give you an honest read before starting."),
   ("Why did my car smell musty after I shampooed it myself?", "Almost always trapped moisture. Introducing water into carpet and foam without thorough drying creates mildew. Drying is genuinely half the job."),
   ("Can you find a smell if I do not know where it is coming from?", "Usually. Liquid runs to the lowest point of the carpet pan, so it is often under a seat or a rail rather than where it was spilled. We check under mats, rails, seat foam and the load floor."),
 ],
 "related": ["interior-car-detailing", "full-interior-exterior-detail"],
},
{
 "slug": "truck-and-suv-detailing",
 "name": "Truck & SUV Detailing",
 "nav": "Truck & SUV",
 "price": "From $150",
 "title": "Truck & SUV Detailing in Hartford, WI | Sudz Up Detailing",
 "meta": "Truck and SUV detailing in Hartford, WI. Work trucks, family SUVs and third-row vehicles. $150 interior, $250 full detail. Call or text 414-286-1609.",
 "h1": "Truck & SUV Detailing",
 "lede": "Trucks and SUVs are priced separately because they genuinely take longer. More surface area, more seats, more cargo space and usually more in it.",
 "card": "Work trucks, family SUVs and third-row vehicles. More space, more time.",
 "glance": [("Interior only", "$150"), ("Full detail", "$250"), ("Covers", "Trucks, SUVs, vans"), ("Third row", "Included")],
 "body": [
   ("Why the price is different",
    ["We charge $150 for the interior service and $250 for the full detail on trucks and SUVs, against $135 and $200 for cars. That is not an arbitrary surcharge — it reflects real additional work.",
     "A three-row SUV has roughly twice the interior volume of a sedan, two extra footwells, a considerably larger cargo area, more glass, and more door jambs. The exterior has more panel area, taller sides and larger wheels. On a truck there is a bed liner, a tailgate, and often a set of running boards that collect an extraordinary amount of grit.",
     "We would rather price it honestly upfront than quote a car price on the phone and adjust it when you arrive, which is a practice we have heard about often enough from customers to know it happens."]),
   ("Work trucks",
    ["A working pickup carries material a passenger car never sees: construction dust, sawdust, feed, fertiliser, mud in layers, and grease from tools and hands.",
     "The high-value areas on a work truck are almost all hidden. Under the rubber mats, where soil compacts into a hard layer. Along the seat rails. Behind and under the rear seat of a crew cab, which on many trucks folds up and reveals a storage area that has never been emptied. The vents, which have been drawing in dust for years.",
     "Running boards and door sills deserve specific mention. You step on them every time you get in, so they carry the abrasive material that then goes into your carpet. Cleaning the carpet without cleaning the sills means you re-contaminate the floor within a week."]),
   ("Family SUVs and third rows",
    ["A family SUV has the opposite problem: not industrial material, but a very large number of small organic deposits in very awkward places.",
     "Third rows are the worst-served area in any vehicle. They are rarely used, rarely vacuumed, and things fall into the seat mechanism and stay there. Second row footwells beside child seat bases collect crushed food that has been ground into the carpet by feet. The cargo area under the load floor holds everything that has rolled back there over a decade.",
     "We fold and move seating to reach these areas, and we lift the load floor. If child seats are fitted, we can remove them where it is safe to do so — cleaning around a car seat is close to pointless. If you would prefer to refit them yourself, tell us and we will leave them out. That is genuinely your call."]),
   ("What we need to know when you book",
    ["Tell us honestly what condition the vehicle is in. There is no judgement involved and it is not a negotiation tactic — it determines how much time we set aside and what we bring.",
     "The specific things worth mentioning: any spill you know about, whether pets travel in the vehicle, whether anyone smokes in it, whether it has been used for anything agricultural or construction related, and whether the cargo area has had anything wet left in it.",
     "If a vehicle is substantially rougher than described when it arrives, we will call you with a revised figure before we start rather than presenting it at collection. That is how we would want it handled."]),
 ],
 "faq": [
   ("Why do trucks and SUVs cost more to detail?", "More interior volume, extra footwells and rows, larger cargo area, more glass and jambs, more panel area outside. It reflects genuine additional time rather than an arbitrary surcharge."),
   ("Do you clean third-row seating?", "Yes, and it usually needs it most. Third rows are rarely vacuumed and debris falls into the seat mechanism. We fold and move seating to reach it properly."),
   ("Do you detail work trucks?", "Yes. The value on a work truck is mostly in the hidden areas — under mats, along seat rails, behind the rear seat of a crew cab, and in the vents."),
   ("What if my vehicle is much dirtier than I described?", "We will call you with a revised figure before starting rather than surprising you at collection."),
 ],
 "related": ["interior-car-detailing", "full-interior-exterior-detail", "stain-and-odor-removal"],
},
]
