# -*- coding: utf-8 -*-
"""
Vehicle-type pages (/vehicles/<slug>/) and situation pages (/situations/<slug>/).

Vehicle pages own the *shape* of the vehicle -- what its layout does to how it
gets dirty and how it has to be cleaned. Situation pages own the *moment* --
why someone is booking now and what the goal actually is. Neither reuses
service-page process copy; they link to it.
"""

VEHICLES = [
{
 "slug": "truck-detailing",
 "name": "Truck Detailing",
 "nav": "Trucks",
 "title": "Pickup Truck Detailing in Hartford, WI \u2014 Cabs, Beds & Work Trucks | Sudz Up",
 "meta": "Pickup truck detailing in Hartford, WI. Crew cabs, bed liners, work-truck interiors and the underside. Interior $150, full $250. Call or text 414-286-1609.",
 "h1": "Pickup Truck Detailing",
 "lede": "A truck is not a big car. The bed, the cab layout and the way it is used all change what needs doing and where the time goes.",
 "glance": [("Interior", "$150"), ("Full detail", "$250"), ("Bed", "Included"), ("Underside", "On request")],
 "body": [
   ("The bed is a separate job",
    ["A truck bed collects a category of material that never enters a car: gravel, mulch, lumber debris, soil, spilled fuel, and the residue of whatever was hauled. A spray-in liner holds liquid in its texture and absorbs oil and fuel into its surface. A drop-in liner traps everything under it, where it corrodes the bed floor unseen.",
     "We clean beds properly \u2014 liner out where it comes out, floor underneath addressed, drain holes cleared \u2014 because a truck detail that skips the bed has skipped a third of the vehicle."]),
   ("Cab layouts and where the dirt goes",
    ["Regular cabs concentrate everything into a small space and the floor behind the seats becomes a shelf that never gets cleaned. Extended cabs have jump seats that fold and trap material underneath. Crew cabs have a rear bench that is used for gear far more often than people, with a floor that has never seen a vacuum.",
     "Under-seat storage on modern trucks is the place nobody opens. It holds tools, rope, spilled fluids and, frequently, the source of a smell the owner has been trying to find for months. We open it on every truck."]),
   ("Work truck interiors",
    ["A work truck cab is used hard by someone in workwear, and workwear is abrasive. Driver's seat bolsters wear through faster than in any other vehicle type. Floor mats are destroyed. Door sills are bare plastic. The console holds every drink of every working day.",
     "That cab needs the driver's quarter treated as its own job with its own time budget, and it needs the food-and-drink residue handled with compressed air and targeted cleaning rather than a wipe. The <a href=\"/services/interior-detailing/\">interior detail</a> covers the process; on a work truck it takes longer and we price it as a truck rather than a car for that reason."]),
   ("The underside",
    ["Trucks go where cars do not \u2014 sites, tracks, launch ramps, frozen lakes \u2014 and the underside picks up what those places leave. Packed mud, ramp grit, lake slush, road brine held in every recess of the frame and the arches.",
     "We address the underside and arches on every full detail. On a truck that has done a winter of site work or a season on the ice, that is the most contaminated surface on the vehicle and it is the one a wash never reaches."]),
 ],
 "faq": [
   ("Do you clean the bed?", "Yes, as part of the truck. Liner out where it comes out, floor underneath cleaned, drain holes cleared. A truck detail that skips the bed has skipped a third of the vehicle."),
   ("Why do trucks cost more than cars?", "Because there is more of them and more places for material to go \u2014 bed, rear cab, under-seat storage, a larger underside. It is not a surcharge; it is time."),
   ("Do you do the underside?", "On every full detail, yes. On trucks that have done site work or been on the ice it is the most contaminated surface on the vehicle."),
 ],
},
{
 "slug": "suv-detailing",
 "name": "SUV Detailing",
 "nav": "SUVs",
 "title": "SUV Detailing in Hartford, WI \u2014 Third Rows, Cargo Areas & Family Wear | Sudz Up",
 "meta": "SUV detailing in Hartford, WI. Third-row seating, cargo areas, load floors and the family wear pattern. Interior $150, full $250. Call or text 414-286-1609.",
 "h1": "SUV Detailing",
 "lede": "The thing that makes an SUV useful \u2014 the space behind the second row \u2014 is the thing that makes it hard to keep clean, because nobody sits there and nobody cleans there.",
 "glance": [("Interior", "$150"), ("Full detail", "$250"), ("Third row", "Included"), ("Load floor", "Lifted")],
 "body": [
   ("The third row",
    ["Third-row seats fold, and when they are folded they trap everything that was on them and everything that falls into the hinge gaps. When they are up, the floor beneath them is the least accessible carpet in the vehicle.",
     "We fold and raise them both ways and clean in every position. The hinge channels and the gaps around the base are where crumbs, coins and the general debris of years collect, and they need compressed air before anything else because a vacuum cannot reach into them."]),
   ("The cargo area",
    ["An SUV cargo area is where the sports kit, the shopping, the dog and the gear go, and its carpet is the most abused surface in the vehicle. Under it is a load floor, and under that is a spare wheel well or a storage tray that collects everything that leaked through.",
     "We lift the load floor on every SUV. The spare well is where spilled liquid ends up, where sand and grit collect, and where the source of a persistent smell very often turns out to be. It is also the surface nobody has ever cleaned."]),
   ("Family wear, on a larger scale",
    ["Most SUVs are family vehicles, and family vehicles wear from the back forward. Rear footwells destroyed while the front is fine. Door cards scuffed at kid height. Seat backs marked by shoes. On an SUV that pattern extends to a third row and a cargo area, so the proportion of the vehicle that is wearing hard is larger than in a car.",
     "We budget time to the rear two-thirds of an SUV specifically, which is the opposite of standard practice and the right way round for this kind of vehicle."]),
   ("Height and the exterior",
    ["SUVs have more roof, and roofs are where fallout lands and dew sits longest. They also have more lower panel, arch and rocker area exposed to road spray. The exterior half of a <a href=\"/services/full-detail/\">full detail</a> on an SUV is simply larger, which is why it is priced as one."]),
 ],
 "faq": [
   ("Do you clean under the third row?", "Yes, in both positions. The hinge channels and the floor beneath are where years of debris collect and they need compressed air before a vacuum can do anything."),
   ("Do you lift the load floor?", "On every SUV. The spare well underneath is where spilled liquid, sand and the source of most persistent smells end up, and it is almost never cleaned."),
   ("Why is an SUV priced the same as a truck?", "Because the volume is similar \u2014 third row, cargo area, larger exterior. It is time, not a surcharge."),
 ],
},
{
 "slug": "minivan-detailing",
 "name": "Minivan Detailing",
 "nav": "Minivans",
 "title": "Minivan Detailing in Hartford, WI \u2014 The Family Vehicle Done Properly | Sudz Up",
 "meta": "Minivan detailing in Hartford, WI. Stow-and-go wells, sliding door tracks, captain's chairs and the most intensive family wear of any vehicle. Interior $150, full $250. Call 414-286-1609.",
 "h1": "Minivan Detailing",
 "lede": "A minivan is the hardest interior in consumer motoring, and it has three features that no other vehicle has and every one of them collects dirt.",
 "glance": [("Interior", "$150"), ("Full detail", "$250"), ("Stow wells", "Cleared"), ("Door tracks", "Cleaned")],
 "body": [
   ("Stow-and-go wells",
    ["Vans with seats that fold into the floor have wells under the floor where the seats go, and those wells are open cavities that collect everything that falls through. Crumbs, toys, coins, spilled drink that ran down the seat and into the well, and the general sediment of a family's years.",
     "We fold the seats into the wells and out of them and clean the wells empty. It is the single most neglected space in any vehicle we work on, and on a van it is frequently where the smell is."]),
   ("Sliding door tracks",
    ["Sliding doors run on tracks, and tracks are channels that collect grit, crumbs and spilled liquid. That material grinds under the rollers, it holds moisture, and it is the reason sliding doors get stiff and noisy.",
     "We clear and clean the tracks on every van. It is a small thing that makes the doors work properly again and removes a reservoir of debris that a vacuum cannot reach."]),
   ("Captain's chairs and the gaps between them",
    ["Second-row captain's chairs create a walkway between them and gaps on both sides of each seat, and those gaps are where a child's dropped food, crayons and juice go. Below the seats are rails and mounting hardware that trap material.",
     "Compressed air into every gap and rail first, then vacuum, then the seats themselves. On a van with captain's chairs that step alone can take longer than a full interior on a small car."]),
   ("The most intensive family wear there is",
    ["Everything about the family-vehicle pattern \u2014 back-forward wear, under-car-seat contamination, dairy in seams, sports kit in the cargo area \u2014 happens in a minivan at higher intensity and across more seats and more floor. It is the vehicle we most often recommend fabric protection on afterwards, because it is the vehicle where the next spill is a certainty.",
     "The <a href=\"/guides/detailing-a-car-with-kids/\">family car guide</a> covers what to do between visits. The <a href=\"/services/interior-detailing/\">interior detail</a> covers the process, and on a minivan it is priced as an SUV because it is at least that much vehicle."]),
 ],
 "faq": [
   ("Do you clean the stow-and-go wells?", "Yes, seats folded in and out and the wells cleaned empty. It is the most neglected space in any vehicle we see and it is frequently where a van's smell is coming from."),
   ("Can you make the sliding doors run smoother?", "Often, yes \u2014 cleaning the tracks removes the grit that grinds under the rollers. It is not a mechanical repair, but it fixes the most common cause of stiff doors."),
   ("Is a minivan priced as an SUV?", "Yes. It is at least that much vehicle and usually more work."),
 ],
},
{
 "slug": "leather-and-luxury-interiors",
 "name": "Leather & Luxury Interiors",
 "nav": "Leather & Luxury",
 "title": "Leather & Luxury Interior Detailing in Hartford, WI | Sudz Up Detailing",
 "meta": "Leather and luxury interior detailing in Hartford, WI. Coated leather, Alcantara, real wood and piano-black trim cleaned with the right product for each surface. Call or text 414-286-1609.",
 "h1": "Leather & Luxury Interior Detailing",
 "lede": "A luxury interior is not harder to clean than a standard one. It is easier to damage, because every surface in it is a different material with a different failure mode.",
 "glance": [("Approach", "Surface by surface"), ("Leather", "Cleaned then fed"), ("Alcantara", "Dry method"), ("Gloss trim", "No abrasives")],
 "body": [
   ("Leather is coated, and the coating is what fails",
    ["Almost all automotive leather has a polymer topcoat over the hide, and that topcoat is what you see, touch and clean. It is also what cracks. The hide beneath it is usually fine; the coating dries out, stiffens, and splits at the bolsters where it flexes most.",
     "So cleaning leather is cleaning a coating, and the wrong product does real harm. Aggressive cleaners strip it. Silicone-heavy conditioners sit on top and attract dirt. What works is a pH-appropriate cleaner with gentle agitation, then a conditioner that actually penetrates the coating and keeps it supple. On an older luxury interior that sequence is the difference between leather that ages and leather that cracks."]),
   ("Alcantara and suede-type fabrics",
    ["Alcantara is a synthetic microfibre and it does not tolerate water-based cleaning the way cloth does. Wet it and it mats; rub it wet and it pills. Oil from hands and hair discolours it and standard cleaners make that worse.",
     "It needs a dry or near-dry method \u2014 a dedicated cleaner applied sparingly, worked with a soft brush, lifted with a microfibre \u2014 and it needs the nap restored afterwards. It is slow and it is not something a general interior clean does well."]),
   ("Wood, piano black and metal",
    ["Real wood trim has a lacquer finish that scratches and clouds under abrasive cleaners. Piano-black plastic scratches if you look at it wrong and shows every swirl under sun. Brushed metal shows fingerprints and marks if cleaned with the wrong cloth.",
     "Each gets its own product and its own cloth. None of them get anything with an abrasive in it. The polish that makes a dash look good will haze a piano-black console permanently."]),
   ("Why it is worth doing properly",
    ["The gap between a well-kept and a neglected luxury interior at resale is large, and most of the damage \u2014 cracked bolsters, matted Alcantara, hazed gloss trim \u2014 is permanent once it happens. The <a href=\"/services/interior-protection/\">interior protection</a> page covers what prevents it. Cleaning surface by surface with the right product for each is what keeps it from happening in the first place."]),
 ],
 "faq": [
   ("Is leather harder to clean than cloth?", "No, but it is easier to damage. The coating over the hide is what you are cleaning, and aggressive cleaners strip it while heavy conditioners attract dirt. The right product and sequence matter more than effort."),
   ("Can you clean Alcantara?", "Yes, with a dry or near-dry method and a soft brush. Water-based cleaning mats it. It is slow and it is not something a general clean does well."),
   ("Will you use a polish on my piano-black trim?", "No. Anything abrasive hazes gloss trim permanently. It gets a dedicated non-abrasive product and its own cloth."),
 ],
},
]

SITUATIONS = [
{
 "slug": "before-you-sell",
 "name": "Before You Sell",
 "nav": "Selling Your Car",
 "title": "Detailing Before You Sell a Car: What Moves the Price | Sudz Up Detailing, Hartford WI",
 "meta": "Detailing before a private sale or trade-in in Hartford, WI. What buyers actually judge, the order to do it in, and when to time it against the listing. Call or text 414-286-1609.",
 "h1": "Detailing Before You Sell",
 "lede": "A full detail is the cheapest thing you can do to a car before you sell it, and the reason is not that it looks nicer. It is what a buyer decides the condition means.",
 "glance": [("Best service", "Full detail"), ("Timing", "1\u20132 days before listing"), ("Buyer judges", "Smell, seat, paint in sun"), ("Photos", "After, not before")],
 "body": [
   ("What a buyer is actually judging",
    ["A private buyer walks up to a car and forms an impression in the first minute, and it is built from three things in roughly this order: the smell when the door opens, the condition of the driver's seat, and the paint in whatever light is available.",
     "None of those is about the mechanicals. All of them are about what the buyer believes about how the car was treated. A clean-smelling car with a decent driver's seat and paint that reflects properly reads as maintained, and a buyer who believes a car was maintained does not negotiate as hard. That is the entire value proposition, and it is worth a great deal more than the cost of the detail."]),
   ("The order to do things in",
    ["Detail first, then photograph, then list. Every version of doing it in a different order costs money.",
     "Photographing a dirty car and detailing it later means the listing photos undersell it and the buyers who click through are already discounting. Detailing it two weeks before listing means it has collected dust and a fortnight of use by the time anyone sees it. The right sequence is a <a href=\"/services/full-detail/\">full detail</a> a day or two before the photographs, photographs the same day, listing the day after."]),
   ("What is worth doing and what is not",
    ["Worth it: odor, always \u2014 a car that smells of dog or smoke is discounted before the buyer sits down. Interior surfaces and the driver's quarter. Paint decontamination and protection, so it reflects in the buyer's driveway. Interior glass, which affects how the whole cabin reads.",
     "Sometimes worth it: light <a href=\"/services/paint-correction/\">paint correction</a> on a higher-value car where the swirls are obvious in sun. The return on correction is real on a car worth enough that condition moves the price by hundreds rather than tens.",
     "Not worth it: fixing things that are honestly worn. A twelve-year-old car with a worn driver's bolster is a twelve-year-old car. Buyers expect it. Trying to hide it reads as hiding something."]),
   ("Trade-in versus private",
    ["A dealer appraiser is judging faster and against a different standard: reconditioning cost. A car that arrives detailed is a car they do not have to recondition, and that shows up in the number. It is a smaller effect than in a private sale, but it is still worth more than the detail costs on most vehicles.",
     "If you are choosing between the two, a detailed car does better in both, and the private sale is where it does best."]),
 ],
 "faq": [
   ("Is it worth detailing a car before selling it?", "Almost always. A buyer's impression is built from smell, the driver's seat and paint in sun, and all three are what a detail addresses. It moves what the buyer believes about the car's history."),
   ("When should I detail it?", "A day or two before the photographs, and photograph the same day. Two weeks early means it has collected use by the time anyone sees it."),
   ("Should I get paint correction before selling?", "On a higher-value car with obvious swirls in sun, often yes. On a modest car, decontamination and protection is usually enough."),
   ("Does it help at a dealer trade-in?", "Yes, though less than in a private sale. A car that needs no reconditioning appraises better."),
 ],
},
{
 "slug": "just-bought-used",
 "name": "Just Bought a Used Car",
 "nav": "Just Bought Used",
 "title": "Detailing a Used Car You Just Bought: The First-Week Reset | Sudz Up Detailing",
 "meta": "What to do with a used car in its first week: a full reset that removes the previous owner, finds what the sale clean hid, and gives you a known baseline. Hartford, WI. Call 414-286-1609.",
 "h1": "Just Bought a Used Car",
 "lede": "You do not know who was in it or what they did in it. One full detail at the start gives you a car whose condition you actually know, and it usually finds a few things.",
 "glance": [("Best service", "Full detail"), ("Timing", "First week"), ("Also check", "Cabin filter, spare well"), ("Goal", "A known baseline")],
 "body": [
   ("What a sale clean hides",
    ["A car being sold has almost always had a surface clean and something fragranced applied. Both genuinely work for a week or two. Then the fragrance fades, the car warms up in the sun, and whatever was underneath starts off-gassing again.",
     "That is the mechanism behind the used-car smell that appears a fortnight after purchase. It was not there when you bought it, in the sense that you could not smell it. It was there in every other sense. A full detail in the first week takes the car back to what it actually is, and it is far better to know that in week one than in month three."]),
   ("What we find",
    ["The cabin air filter is almost never changed before a sale, and it is a reservoir of the previous owner's air. The spare wheel well is almost never cleaned, and it holds whatever leaked through the boot carpet over the car's life. Under-seat storage and the gaps around seat bases hold what the previous owner dropped.",
     "We also find the things a buyer's inspection misses: a damp patch under a mat that says a seal leaks, a headliner that says the car was smoked in, a repainted panel that behaves differently under clay. None of that changes whether you bought a good car. All of it is worth knowing."]),
   ("Making it yours",
    ["There is a practical value and there is a less tangible one. The practical value is a known baseline \u2014 you know what the interior smells like, what the paint condition is under the contamination, and what was in the corners. Anything that appears after that is new.",
     "The other value is that a car that has been fully reset feels like yours rather than someone else's. That sounds soft and it is not. It changes how you treat it."]),
   ("Protection at the start",
    ["A used car in its first week is the second-best time to protect it, after a new car on day one. The interior is as clean as it is going to be; the paint has just been decontaminated. <a href=\"/services/interior-protection/\">Fabric and leather protection</a> and a sealant or <a href=\"/services/ceramic-coating/\">coating</a> on the paint go on to a clean surface, which is the only way they work properly, and they mean the next owner's problems start from a better place."]),
 ],
 "faq": [
   ("The car smelled fine when I bought it and now it does not. Why?", "The sale clean masked it. A fragrance applied before a sale genuinely works for a week or two; once it fades and the car warms up, the original source is back. It was always there."),
   ("What should I check on a used car in the first week?", "The cabin air filter, the spare wheel well under the boot floor, under the floor mats for damp, and the headliner for smoke. A full detail checks all of it."),
   ("Is it worth protecting a used car?", "Yes, in the first week \u2014 the interior and paint are as clean as they will be, and protection only works on a clean surface."),
 ],
},
{
 "slug": "new-car-protection",
 "name": "New Car Protection",
 "nav": "New Car",
 "title": "Protecting a New Car From Day One: Coating, Interior Protection & Prep | Sudz Up",
 "meta": "What to do with a brand new car in the first month: why dealer prep is not protection, what transport marring is, and why protection at the start costs least. Hartford, WI. Call 414-286-1609.",
 "h1": "Protecting a New Car",
 "lede": "The first month is the only time a car is genuinely clean, and it is the only time protection goes on without anything to fix first. Every month after that, the same job costs more.",
 "glance": [("Best timing", "First month"), ("Paint", "Decon + coat"), ("Interior", "Fabric / leather protection"), ("Dealer prep", "Is not protection")],
 "body": [
   ("Dealer prep is not protection",
    ["A new car has been on a transporter, in a compound, through a dealer wash and a delivery clean. None of that is protection. The dealer wash is frequently a brush wash, and transport and prep marring on brand-new paint is common enough that we see it on most new vehicles we assess under inspection light.",
     "So a new car is not a blank surface. It is a nearly-blank surface with light marring and a coating of transport contamination on it, and the first job is to decontaminate and, where needed, correct that before anything protective goes on. Coating over transport marring locks it in."]),
   ("Why the first month is cheapest",
    ["Protection bonds to whatever surface it meets. On a new car that surface needs decontamination only \u2014 there is nothing to correct beyond light transport marring \u2014 so a <a href=\"/services/ceramic-coating/\">coating</a> job is close to its starting price.",
     "After a year of Wisconsin exposure the same car has bonded fallout, brine film, and a season of wash marring. Now the coating needs correction first and the job is considerably larger. Same car, same product; the only variable is when.",
     "The interior is the same story. <a href=\"/services/interior-protection/\">Fabric and leather protection</a> on a new interior is prevention. On a two-year-old interior it is preservation of whatever damage has already happened."]),
   ("What protection actually buys",
    ["It does not make the car immune to anything. What it does is change the surface so contamination releases instead of bonding \u2014 brine rinses off, tree sap wipes off, a spilled drink beads long enough to reach a towel. Over years that is the difference between a car that looks its age and one that does not.",
     "It also changes the maintenance routine. A coated car through a Wisconsin winter needs rinsing, not scrubbing, and scrubbing is where paint damage actually comes from."]),
   ("If the dealer sold you a coating",
    ["Some are good, some were applied by whoever was available over paint that was never prepared. If you have one, we can assess it under inspection light and tell you honestly whether it is doing anything. If it was applied over marring, the marring is now permanent for the life of the coating, and knowing that early is better than finding it in the sun next summer."]),
 ],
 "faq": [
   ("Does a new car need paint correction?", "Often light correction, yes. Transport and dealer-prep marring on new paint is common and coating over it locks it in. We assess under inspection light before coating anything."),
   ("Why coat a new car rather than wait?", "Because the job is smallest now. After a year of exposure it needs correction first and costs considerably more. Same product, same car; timing is the only variable."),
   ("Is the dealer's coating any good?", "Sometimes. We can assess it under inspection light and tell you honestly whether it is doing anything and whether it was applied over marring."),
 ],
},
]
